#include "analysis.hpp"
#include "caller_trace.hpp"
#include <algorithm>
#include <array>
#include <cmath>
#include <fstream>
#include <functional>
#include <iostream>
#include <iterator>
#include <stdexcept>

namespace {
void Require(bool condition,const std::string& message){if(!condition)throw std::runtime_error(message);}
aoe::TargetInfo Target(uint64_t base=0x140000000){aoe::TargetInfo target;target.mode=aoe::TraceMode::Caller020A;target.pid=1;target.creationTime=2;target.base=base;target.size=0xF3B000;target.traceRva=aoe::Caller020ARva;target.traceAddress=base+target.traceRva;target.verified=true;target.image.sha256=aoe::ApprovedHash;return target;}
aoe::Event Event(uint64_t returnRva,double ms,uint16_t operation=0x020A){aoe::Event event;event.ms=ms;event.qpc=int64_t(ms*1000);event.threadId=7;event.rip=0x1407BB160;event.rsp=0x2222;event.rcx=1;event.rdx=2;event.r8=3;event.r9=4;event.returnReadable=true;event.returnInModule=true;event.returnRva=returnRva;event.returnAddress=0x140000000+returnRva;event.caller020A.captured=true;event.caller020A.operationPointer=event.r9;event.caller020A.operationWord0={true,0,2,operation};aoe::ClassifyCaller020A(event);return event;}
}

unsigned CallerTraceTests(const std::filesystem::path& artifacts){unsigned passed=0;auto check=[&](const char* name,const std::function<void()>& test){test();++passed;std::cout<<"[PASS] "<<name<<'\n';};
    check("caller mode resolves exact 0x7BB160 RVA and 12 second default",[]{Require(aoe::Caller020ARva==0x7BB160,"constant");Require(aoe::TraceRva(aoe::TraceMode::Caller020A)==0x7BB160,"mode RVA");Require(std::string(aoe::ModeName(aoe::TraceMode::Caller020A))=="0x020A Caller 7BB160","mode name");Require(aoe::DefaultCaptureSecondsForMode(aoe::TraceMode::Caller020A)==12,"default duration");});
    check("caller trace resolves dynamic module bases",[]{uint64_t address=0;Require(aoe::ResolveTraceAddress(0x7FF600000000,0xF3B000,aoe::Caller020ARva,address)&&address==0x7FF6007BB160,"first base");Require(aoe::ResolveTraceAddress(0x7FF700000000,0xF3B000,aoe::Caller020ARva,address)&&address==0x7FF7007BB160,"second base");});
    check("entry snapshot decodes true return address from RSP and return RVA",[]{auto target=Target();uint64_t stackReturn=target.base+aoe::Known853B10ReturnRva;uint16_t operation=0x020A;aoe::Event event;event.rsp=reinterpret_cast<uint64_t>(&stackReturn);event.r9=reinterpret_cast<uint64_t>(&operation);aoe::SnapshotCaller020AEntry(GetCurrentProcess(),target,event);Require(event.returnReadable&&event.returnInModule&&event.returnAddress==stackReturn&&event.returnRva==aoe::Known853B10ReturnRva,"return decode");});
    check("operationWord0 decodes from R9 and classifies 0209",[]{auto target=Target();uint64_t stackReturn=target.base+0x81209;uint16_t operation=0x0209;aoe::Event event;event.rsp=reinterpret_cast<uint64_t>(&stackReturn);event.r9=reinterpret_cast<uint64_t>(&operation);aoe::SnapshotCaller020AEntry(GetCurrentProcess(),target,event);Require(event.caller020A.operationWord0.readable&&event.caller020A.operationWord0.value==0x0209,"word0");Require(event.caller020A.operation0209&&!event.caller020A.operation020A,"0209 class");});
    check("operationWord0 classifies 020A",[]{auto event=Event(0x81209,1,0x020A);Require(event.caller020A.operation020A&&!event.caller020A.operation0209,"020A class");});
    check("return 0x85404E is known 853B10 path",[]{auto event=Event(aoe::Known853B10ReturnRva,1);Require(event.caller020A.known853B10Path,"known path");auto other=Event(0x81209,2);Require(!other.caller020A.known853B10Path,"other path");});
    check("invalid R9 fails safely without classification",[]{auto target=Target();uint64_t stackReturn=target.base+0x81209;aoe::Event event;event.rsp=reinterpret_cast<uint64_t>(&stackReturn);event.r9=1;aoe::SnapshotCaller020AEntry(GetCurrentProcess(),target,event);Require(!event.caller020A.operationWord0.readable&&event.caller020A.operationWord0.error!=0&&!event.caller020A.operation0209&&!event.caller020A.operation020A,"invalid R9");});
    check("invalid return address fails safely",[]{auto target=Target();uint16_t operation=0x020A;aoe::Event event;event.rsp=1;event.r9=reinterpret_cast<uint64_t>(&operation);aoe::SnapshotCaller020AEntry(GetCurrentProcess(),target,event);Require(!event.returnReadable&&!event.returnInModule&&event.returnReadError!=0,"invalid RSP");Require(event.caller020A.operation020A,"independent R9 read");});
    check("020A events group by return RVA",[]{aoe::Capture capture;capture.target=Target();capture.events={Event(0x81209,100),Event(0x81209,1100),Event(0x797F7F,200),Event(0x81209,2100),Event(0x81209,2200,0x0209)};auto summary=aoe::BuildCaller020ASummary(capture);Require(summary.operation020ACount==4&&summary.callerGroups.size()==2,"groups");Require(summary.callerGroups[0].returnRva==0x81209&&summary.callerGroups[0].count==3,"dominant group");});
    check("caller grouping detects approximately 1000 ms periodic timing",[]{aoe::Capture capture;capture.target=Target();capture.events={Event(0x81209,100),Event(0x81209,1095),Event(0x81209,2100),Event(0x81209,3090)};auto summary=aoe::BuildCaller020ASummary(capture);const auto& group=summary.callerGroups.front();Require(group.near1000msPeriodic&&std::abs(group.meanDeltaMs-996.6666667)<0.001&&group.medianDeltaMs==995,"periodic metrics");Require(summary.dominantPeriodicAvailable&&summary.dominantReturnRva==0x81209,"dominant periodic");});
    check("known path periodic summary stays descriptive",[]{aoe::Capture capture;capture.target=Target();capture.events={Event(aoe::Known853B10ReturnRva,0),Event(aoe::Known853B10ReturnRva,1000),Event(aoe::Known853B10ReturnRva,2000)};auto summary=aoe::BuildCaller020ASummary(capture);auto text=aoe::Caller020ASummaryText(summary,capture.target.base);Require(text.find("+853B10 path is runtime-confirmed")!=std::string::npos&&text.find("scheduler ownership")!=std::string::npos,"interpretation bounded");});
    check("static direct calls to 7BB160 are the disassembled approved-build set",[]{const auto calls=aoe::DirectCallsitesToCaller020A();const std::array<uint64_t,7> expected{0x81204,0x797F7A,0x7A9617,0x7C6D6D,0x7D9268,0x7F091D,0x854049};Require(calls.size()==expected.size(),"callsite count");for(size_t i=0;i<expected.size();++i)Require(calls[i].callRva==expected[i]&&calls[i].returnRva==expected[i]+5,"call/return RVA");});
    check("caller trace JSON serializes events groups and direct callsites",[&]{aoe::Capture capture;capture.id=1700;capture.label=aoe::Label::Aoe;capture.utc="2026-09-17T00:00:00Z";capture.synthetic=true;capture.complete=true;capture.frequency=1000000;capture.startQpc=1;capture.endQpc=12000001;capture.requestedSeconds=12;capture.durationMs=12000;capture.target=Target();capture.events={Event(aoe::Known853B10ReturnRva,100),Event(aoe::Known853B10ReturnRva,1100),Event(aoe::Known853B10ReturnRva,2100)};auto analysis=aoe::Analyze(capture);std::string error;auto path=artifacts/L"caller_020a.json";Require(aoe::ExportJson(path,capture,analysis,error),error);std::ifstream input(path);std::string json((std::istreambuf_iterator<char>(input)),{});for(auto token:{"\"traceMode\":\"0x020A Caller 7BB160\"","\"operationWord0\":522","\"operation020A\":true","\"returnRva\":\"0x85404E\"","\"known853B10Path\":true","\"operation020ACount\":3","\"callerGroups\"","\"near1000msPeriodic\":true","\"directCallsites\"","\"callRva\":\"0x81204\"",aoe::Caller020ALimitation})Require(json.find(token)!=std::string::npos,token);});
    return passed;
}
