#include "initial_2x.hpp"
#include <cmath>
#include <fstream>
#include <functional>
#include <iostream>
#include <iterator>
#include <stdexcept>

namespace {
void Require(bool condition,const std::string& message){if(!condition)throw std::runtime_error(message);}
aoe::TargetInfo Target(uint64_t base=0x140000000){aoe::TargetInfo t;t.mode=aoe::TraceMode::Initial2x;t.pid=420;t.creationTime=9001;t.base=base;t.size=0x1000000;t.traceRva=aoe::InitialCallRva;t.traceAddress=base+aoe::InitialCallRva;t.verified=true;t.image.sha256=aoe::ApprovedHash;t.runtime.initialNxAvailable=true;t.runtime.initialPrepRva=aoe::InitialPrepareRva;t.runtime.initialCallRva=aoe::InitialCallRva;t.runtime.initialReturnRva=aoe::InitialReturnRva;t.runtime.producerRva=aoe::ProducerRva;return t;}
aoe::Initial2xExperiment Experiment(uint32_t count=2,const aoe::TargetInfo& target=Target()){auto e=aoe::CreateInitial2xExperiment(target,true,count);e.armQpc=1000;e.frequency=1000;return e;}
aoe::InitialCallSnapshot Call(uint16_t word=0x0209,uint32_t tid=7,int64_t qpc=1100){aoe::InitialCallSnapshot c;c.operationReadable=true;c.operationWord0=word;c.threadId=tid;c.qpc=qpc;c.rip=0x147F091D;c.rsp=0x5000;c.r12=0x12;c.r13=0x13;c.r14=0x14;c.r15=0x15;c.rsi=0x16;c.rdi=0;c.rcx=0x13;c.rdx=0x15;c.r8=0x14;c.r9=0x16;return c;}
aoe::InitialReturnAction Return(aoe::Initial2xExperiment& e,uint32_t tid=7,uint64_t rsp=0x5000,uint64_t r12=0x12,uint64_t r13=0x13,uint64_t r14=0x14,uint64_t r15=0x15,uint64_t rsi=0x16,uint64_t rdi=0){return aoe::ObserveInitialReturn(e,tid,rsp,r12,r13,r14,r15,rsi,rdi);}
aoe::Initial2xExperiment Complete(uint32_t count){auto e=Experiment(count);Require(aoe::ObserveInitialCall(e,Call())==aoe::InitialCallAction::FirstAccepted,"first call");for(uint32_t observed=1;observed<=count;++observed){if(observed<count){Require(Return(e)==aoe::InitialReturnAction::Redirect,"intermediate return redirects");aoe::CommitInitialRedirect(e,true);Require(e.redirectsPerformed==observed,"redirect count");Require(aoe::ObserveInitialCall(e,Call(0x0209,7,1100+10*observed))==aoe::InitialCallAction::SecondObserved,"replayed call observed");}else Require(Return(e)==aoe::InitialReturnAction::Completed,"final return completes");}return e;}
}

unsigned Initial2xTests(const std::filesystem::path& artifacts){unsigned passed=0;auto check=[&](const char* name,const std::function<void()>& test){test();++passed;std::cout<<"[PASS] "<<name<<'\n';};
    check("Initial Nx preserves proven RVAs and dynamic base resolution",[]{Require(aoe::InitialPrepareRva==0x7F0900&&aoe::InitialCallRva==0x7F091D&&aoe::InitialReturnRva==0x7F0922,"exact RVAs");for(uint64_t base:{0x140000000ull,0x7FF69D570000ull}){uint64_t address=0;Require(aoe::ResolveTraceAddress(base,0x1000000,aoe::InitialCallRva,address)&&address==base+0x7F091D,"dynamic call address");Require(aoe::ResolveTraceAddress(base,0x1000000,aoe::InitialReturnRva,address)&&address==base+0x7F0922,"dynamic return address");}});
    check("count range accepts 1 through 100 and rejects out of range",[]{Require(aoe::ValidInitialCallCount(1)&&aoe::ValidInitialCallCount(100),"bounds accepted");Require(!aoe::ValidInitialCallCount(0)&&!aoe::ValidInitialCallCount(101),"out of range rejected");uint32_t value=0;Require(aoe::ParseInitialCallCount(L"1",value)&&value==1,"parse minimum");Require(aoe::ParseInitialCallCount(L"100",value)&&value==100,"parse maximum");Require(!aoe::ParseInitialCallCount(L"0",value)&&!aoe::ParseInitialCallCount(L"101",value)&&!aoe::ParseInitialCallCount(L"2x",value),"invalid edit rejected");Require(!aoe::CreateInitial2xExperiment(Target(),true,0).armed&&!aoe::CreateInitial2xExperiment(Target(),true,101).armed,"invalid ARM state rejected");});
    check("only operation 0x0209 starts replay state",[]{auto e=Experiment();Require(aoe::ObserveInitialCall(e,Call(0x020A))==aoe::InitialCallAction::Ignore&&!e.repeatPending,"020A ignored");auto unreadable=Call();unreadable.operationReadable=false;Require(aoe::ObserveInitialCall(e,unreadable)==aoe::InitialCallAction::Ignore,"unreadable ignored");Require(aoe::ObserveInitialCall(e,Call())==aoe::InitialCallAction::FirstAccepted&&e.repeatPending&&e.initialCallsObserved==1,"0209 accepted");});
    check("first return requires same thread and matching RSP",[]{auto e=Experiment();aoe::ObserveInitialCall(e,Call());Require(Return(e,8)==aoe::InitialReturnAction::Ignore&&e.repeatPending,"wrong thread ignored");Require(Return(e,7,0x5008)==aoe::InitialReturnAction::Aborted&&e.aborted&&!e.redirectClaimed&&!e.ripRedirectPerformed,"RSP mismatch aborts with zero redirect");});
    check("all required nonvolatile registers are validated",[]{for(unsigned changed=0;changed<6;++changed){auto e=Experiment();aoe::ObserveInitialCall(e,Call());uint64_t v[6]={0x12,0x13,0x14,0x15,0x16,0};++v[changed];Require(Return(e,7,0x5000,v[0],v[1],v[2],v[3],v[4],v[5])==aoe::InitialReturnAction::Aborted,"nonvolatile mismatch abort");Require(e.redirectsPerformed==0&&!e.ripRedirectPerformed,"mismatch performs zero redirect");}});
    check("N=1 completes one initial call with zero redirects",[]{auto e=Complete(1);Require(e.completed&&e.initialCallsObserved==1&&e.redirectsPerformed==0&&!e.ripRedirectPerformed,"N=1 invariant");Require(e.initialCallTimestamps.size()==1&&e.initialCallIntervalsMs.empty(),"N=1 timing");});
    check("N=2 completes two initial calls with one redirect",[]{auto e=Complete(2);Require(e.completed&&e.initialCallsObserved==2&&e.redirectsPerformed==1&&e.redirectCount==1,"N=2 invariant");});
    check("N=5 completes five initial calls with four redirects",[]{auto e=Complete(5);Require(e.completed&&e.initialCallsObserved==5&&e.redirectsPerformed==4,"N=5 invariant");Require(e.initialCallTimestamps.size()==5&&e.initialCallIntervalsMs.size()==4,"N=5 timing");});
    check("N=100 completes without off-by-one or extra redirect",[]{auto e=Complete(100);Require(e.completed&&e.initialCallsObserved==100&&e.redirectsPerformed==99,"N=100 invariant");Require(e.redirectsPerformed<=e.targetInitialCalls-1,"strict maximum");const auto redirects=e.redirectsPerformed;Require(Return(e)==aoe::InitialReturnAction::Ignore&&e.redirectsPerformed==redirects,"final return does not redirect");Require(aoe::ObserveInitialCall(e,Call(0x0209,7,2200))==aoe::InitialCallAction::Ignore&&e.initialCallsObserved==100,"101st call rejected by terminal state");});
    check("configured count is frozen after ARM",[]{uint32_t guiValue=5;auto e=Experiment(guiValue);guiValue=100;Require(e.targetInitialCalls==5&&guiValue==100,"armed state owns frozen count");});
    check("abort stops all later redirects",[]{auto e=Experiment(5);aoe::ObserveInitialCall(e,Call());Require(Return(e)==aoe::InitialReturnAction::Redirect,"first redirect claim");aoe::CommitInitialRedirect(e,true);auto bad=Call(0x020A,7,1110);Require(aoe::ObserveInitialCall(e,bad)==aoe::InitialCallAction::Aborted&&e.aborted,"bad replay operation aborts");const auto redirects=e.redirectsPerformed;Require(Return(e)==aoe::InitialReturnAction::Ignore&&e.redirectsPerformed==redirects,"no redirect after abort");});
    check("failed SetThreadContext commit aborts with zero performed redirect",[]{auto e=Experiment();aoe::ObserveInitialCall(e,Call());Require(Return(e)==aoe::InitialReturnAction::Redirect,"claim");aoe::CommitInitialRedirect(e,false,"injected failure");Require(e.aborted&&!e.ripRedirectPerformed&&e.redirectsPerformed==0&&e.abortReason=="injected failure","abort state");});
    check("producer counters and timestamp series are independent",[]{auto e=Experiment(10);aoe::RecordInitial2xProducer(e,true,0x0209,1050);aoe::RecordInitial2xProducer(e,true,0x0209,1075);aoe::RecordInitial2xProducer(e,true,0x020A,1100);aoe::RecordInitial2xProducer(e,true,0x020A,1205);aoe::RecordInitial2xProducer(e,true,0x0246,1300);Require(e.producer0209Count==2&&e.producer020ACount==2&&e.producerOtherCount==1,"producer classes");Require(e.producer0209Timestamps.size()==2&&e.producer020ATimestamps.size()==2&&e.producer020ADeltas.size()==1&&std::abs(e.producer020ADeltas[0]-105.0)<1e-9,"producer timing");});
    check("standalone Initial Nx JSON exports configured and observed counts",[&]{auto e=Complete(5);std::string error;const auto path=artifacts/L"initial_n_standalone.json";Require(aoe::ExportInitial2xJson(path,e,error),error);std::ifstream input(path);std::string json((std::istreambuf_iterator<char>(input)),{});for(auto token:{"\"mode\":\"AOE Initial Nx\"","\"configuredInitialCalls\":5","\"initialCallsObserved\":5","\"redirectsPerformed\":4","\"maximumCallLimit\":100","\"completed\":true","\"initialCallTimestamps\"","\"initialCallIntervalsMs\"",aoe::Initial2xLimitation})Require(json.find(token)!=std::string::npos,token);});
    check("process restart invalidates pointers and requires new arm",[]{auto target=Target();auto e=Experiment(10,target);aoe::ObserveInitialCall(e,Call());++target.creationTime;Require(!aoe::Initial2xSessionMatches(e,target),"session mismatch detected");aoe::InvalidateInitial2xSession(e,"restart");Require(!e.armed&&e.aborted&&e.pid==0&&e.moduleBase==0&&e.imageSha256.empty()&&!e.repeatPending&&!e.replayInProgress,"runtime identity and pointers invalidated");});
    return passed;
}
