#include "manager_state.hpp"
#include "profile.hpp"
#include "settings.hpp"
#include "ui_layout.hpp"
#include "diagnostics.hpp"
#include <algorithm>
#include <fstream>
#include <functional>
#include <iostream>
#include <iterator>
#include <stdexcept>

namespace {
void Require(bool condition,const std::string& message){if(!condition)throw std::runtime_error(message);}
std::string FileHash(const std::filesystem::path& path){std::ifstream in(path,std::ios::binary);std::vector<uint8_t> bytes((std::istreambuf_iterator<char>(in)),{});return aoe::Sha256(bytes.data(),bytes.size());}
std::vector<uint8_t> PeBytesAtRva(const std::filesystem::path& path,uint32_t rva,size_t count){std::ifstream in(path,std::ios::binary);std::vector<uint8_t> file((std::istreambuf_iterator<char>(in)),{});auto u16=[&](size_t p){if(p+2>file.size())throw std::runtime_error("truncated PE");return uint16_t(file[p]|uint16_t(file[p+1])<<8);};auto u32=[&](size_t p){if(p+4>file.size())throw std::runtime_error("truncated PE");return uint32_t(file[p]|uint32_t(file[p+1])<<8|uint32_t(file[p+2])<<16|uint32_t(file[p+3])<<24);};const size_t pe=u32(0x3C);Require(pe+24<=file.size()&&u32(pe)==0x00004550,"valid PE signature");const auto sections=u16(pe+6),optionalBytes=u16(pe+20);const size_t table=pe+24+optionalBytes;for(uint16_t i=0;i<sections;++i){const size_t s=table+size_t(i)*40;const auto virtualSize=u32(s+8),virtualAddress=u32(s+12),rawSize=u32(s+16),raw=u32(s+20);const uint64_t span=std::max(virtualSize,rawSize);if(rva>=virtualAddress&&uint64_t(rva)-virtualAddress+count<=span){const size_t offset=raw+size_t(rva-virtualAddress);Require(offset+count<=file.size(),"RVA maps inside file");return {file.begin()+offset,file.begin()+offset+count};}}throw std::runtime_error("RVA not mapped by PE section");}
aoe::TargetInfo Target(uint32_t pid=100,uint64_t creation=200,uint64_t base=0x140000000){aoe::TargetInfo t;t.mode=aoe::TraceMode::Initial2x;t.pid=pid;t.creationTime=creation;t.base=base;t.size=0x1000000;t.verified=true;t.image.sha256=aoe::ApprovedHash;t.image.executableRanges.push_back({0,0x1000000});return t;}
}

unsigned ManagerTests(const std::filesystem::path& artifacts){unsigned passed=0;auto check=[&](const char* name,const std::function<void()>& test){test();++passed;std::cout<<"[PASS] "<<name<<'\n';};const auto root=artifacts.parent_path().parent_path().parent_path();const auto profileDir=root/L"profiles";const auto golden=std::filesystem::path(LR"(C:\Users\Public\Documents\4UnityAOETracer\build\Release\4UnityAOETracer.exe)");const auto goldenBefore=FileHash(golden);
    check("manager output is separate from golden project",[&]{auto manager=root/L"build"/L"Release"/L"4UnityAOEManager.exe";Require(std::filesystem::weakly_canonical(manager)!=std::filesystem::weakly_canonical(golden),"separate output paths");Require(root.filename()==L"4UnityAOEManager","manager project root");});
    check("settings create save and load safely",[&]{auto path=artifacts/L"manager-settings"/L"settings.json";aoe::ManagerSettings saved;saved.initialCalls=25;saved.autoAttach=true;saved.autoArm=true;saved.minimizeAfterAutoArm=true;saved.lastSelectedTab=1;std::string error;Require(aoe::SaveSettings(path,saved,error),error);aoe::ManagerSettings loaded;std::string diagnostic;Require(aoe::LoadSettings(path,loaded,diagnostic),diagnostic);Require(loaded.initialCalls==25&&loaded.autoAttach&&loaded.autoArm&&loaded.minimizeAfterAutoArm&&loaded.lastSelectedTab==1,"settings round trip");});
    check("missing and corrupt settings fall back to safe defaults",[&]{auto missing=artifacts/L"missing-settings.json";std::filesystem::remove(missing);aoe::ManagerSettings loaded;std::string diagnostic;Require(aoe::LoadSettings(missing,loaded,diagnostic)&&loaded.initialCalls==2&&!loaded.autoAttach&&!loaded.autoArm&&!loaded.startWithWindows,"missing defaults");auto corrupt=artifacts/L"corrupt-settings.json";std::ofstream(corrupt)<<"{ definitely not json";loaded.initialCalls=100;Require(aoe::LoadSettings(corrupt,loaded,diagnostic)&&loaded.initialCalls==2&&!loaded.autoAttach,"corrupt defaults");});
    check("settings enforce Initial Calls minimum and maximum",[]{auto low=aoe::SafeDefaultSettings();low.initialCalls=0;Require(!aoe::ValidateSettings(low)&&low.initialCalls==2,"zero reset");auto high=aoe::SafeDefaultSettings();high.initialCalls=101;Require(!aoe::ValidateSettings(high)&&high.initialCalls==2,"over maximum reset");auto min=aoe::SafeDefaultSettings();min.initialCalls=1;auto max=aoe::SafeDefaultSettings();max.initialCalls=100;Require(aoe::ValidateSettings(min)&&aoe::ValidateSettings(max),"1 and 100 accepted");});
    check("profile JSON loads and selects only matching SHA",[&]{aoe::BuildProfile profile;std::filesystem::path selected;std::string error;Require(aoe::SelectBuildProfile(profileDir,aoe::ApprovedHash,profile,selected,error),error);Require(profile.schemaVersion==1&&profile.anchors.size()==11&&profile.targetSha256==aoe::ApprovedHash,"known profile loaded");aoe::BuildProfile unknown;Require(!aoe::SelectBuildProfile(profileDir,std::string(64,'A'),unknown,selected,error)&&unknown.anchors.empty(),"unknown SHA rejected");});
    check("all three SHA profiles coexist and select independently",[&]{aoe::BuildProfile oldProfile,previousProfile,newProfile;std::filesystem::path oldPath,previousPath,newPath;std::string error;Require(aoe::SelectBuildProfile(profileDir,aoe::ApprovedHash,oldProfile,oldPath,error),error);Require(aoe::SelectBuildProfile(profileDir,aoe::PreviousPatchHash,previousProfile,previousPath,error),error);Require(aoe::SelectBuildProfile(profileDir,aoe::CurrentPatchHash,newProfile,newPath,error),error);Require(oldPath!=previousPath&&previousPath!=newPath&&oldProfile.targetSha256==aoe::ApprovedHash&&previousProfile.targetSha256==aoe::PreviousPatchHash&&newProfile.targetSha256==aoe::CurrentPatchHash,"separate SHA profiles");Require(oldProfile.runtime.initialCallRva==0x7F091D&&previousProfile.runtime.initialCallRva==0x7F195D&&newProfile.runtime.initialCallRva==0x7F277D,"profile-specific callsites");Require(aoe::ProfileTraceRva(newProfile,aoe::TraceMode::Initial2x)==0x7F277D&&aoe::ProfileTraceRva(newProfile,aoe::TraceMode::Initial2x)!=aoe::InitialCallRva,"old RVA not reused on current SHA");});
    check("current profile carries recovered per-build layout and differential anchors",[&]{aoe::BuildProfile profile;std::filesystem::path path;std::string error;Require(aoe::SelectBuildProfile(profileDir,aoe::CurrentPatchHash,profile,path,error),error);const auto& r=profile.runtime;Require(r.targetInspectorAvailable&&r.targetVectorOffset==0x660&&r.actorIdOffset==0x768&&r.actorTypeOffset==0x7E1&&r.actorEligibilityOffset==0x7CA&&r.actorStatusOffset==0x7E4&&r.actorPositionOffset==0xB0&&r.actorWorldLinkOffset==0x1390&&r.actorWorldLinkOwnerOffset==0x1380&&r.actorWorldPositionOffset==0x70,"recovered layout");Require(r.initialPrepRva==0x7F2760&&r.initialCallRva==0x7F277D&&r.initialReturnRva==0x7F2782&&r.differentialParsedRva==0x6CB73&&r.sharedWorkerRva==0x7BC4C0&&r.typedActorLookupRva==0x7BAF60&&r.producerCallRva==0x7BC817&&r.producerRva==0x99150,"recovered differential and replay chain");Require(r.gameContextPointerRva==0xE6C9C0&&r.selectedTargetOffset==0x2318&&r.selectedTargetWriterRva==0x7F6411&&r.selectedTargetWriterBytes==std::vector<uint8_t>({0x4C,0x89,0x83,0x18,0x23,0x00,0x00})&&r.selectedTargetReaderRvas==std::vector<uint64_t>({0x799891,0x7D7C77}),"selected-target static candidate path and writer fingerprint");Require(r.differentialParsedBytes==std::vector<uint8_t>({0x66,0x47,0x39,0x74,0x6F,0x3C}),"parsed boundary fingerprint");Require(r.actorTreeOffsets[2]==0x1120&&r.targetRecordBytes==8&&r.targetMaximumEntries==32,"record and resolver layout");});
    check("Initial Nx static capability is present and new build requires live validation",[&]{aoe::BuildProfile oldProfile,newProfile;std::filesystem::path path;std::string error,reason;Require(aoe::SelectBuildProfile(profileDir,aoe::ApprovedHash,oldProfile,path,error),error);Require(aoe::RuntimeLayoutSupportsInitialNx(oldProfile.runtime,reason)&&!oldProfile.runtime.liveValidationRequired,reason);Require(aoe::SelectBuildProfile(profileDir,aoe::CurrentPatchHash,newProfile,path,error),error);Require(aoe::RuntimeLayoutSupportsInitialNx(newProfile.runtime,reason)&&newProfile.runtime.liveValidationRequired,"new replay has static anchors and requires same-session live validation");auto broken=oldProfile.runtime;broken.producerCallBytes[0]=0x90;Require(!aoe::RuntimeLayoutSupportsInitialNx(broken,reason)&&reason.find("direct-call")!=std::string::npos,"failed fingerprint prevents arm");});
    check("current profile resolves fresh Inspector addresses without arming replay",[&]{aoe::BuildProfile profile;std::filesystem::path path;std::string error;Require(aoe::SelectBuildProfile(profileDir,aoe::CurrentPatchHash,profile,path,error),error);auto live=Target(301,401,0x140000000);live.size=0xF46000;live.image.imageSize=0xF46000;live.image.sha256=aoe::CurrentPatchHash;live.image.executableRanges={{0x1000,0xCC1C00}};live.runtime=profile.runtime;aoe::ManagerSession session;Require(aoe::BeginManagerSession(profile,live,session,error),error);const auto first=session.anchors[1].address;Require(first==live.base+profile.runtime.initialCallRva&&session.runtime.typedActorLookupRva==0x7BAF60&&!session.runtimeArmed,"static recovery does not arm replay");aoe::InvalidateManagerSession(session,"restart");live.pid=302;live.creationTime=402;live.base=0x7FF600000000;Require(aoe::BeginManagerSession(profile,live,session,error),error);Require(session.anchors[1].address==live.base+profile.runtime.initialCallRva&&session.anchors[1].address!=first&&!session.runtimeArmed,"restart rebased profile addresses and remains disarmed");});
    check("current profile fingerprints match the recovered TClient image",[&]{aoe::BuildProfile profile;std::filesystem::path selected;std::string error;const auto image=std::filesystem::path(aoe::TargetPath);const auto actualSha=FileHash(image);Require(aoe::SelectBuildProfile(profileDir,actualSha,profile,selected,error),error);Require(profile.targetSha256==actualSha,"current TClient hash");const auto& r=profile.runtime;for(const auto& item:std::initializer_list<std::pair<uint64_t,const std::vector<uint8_t>*>>{{r.initialPrepRva,&r.initialPrepBytes},{r.initialCallRva,&r.initialCallBytes},{r.initialReturnRva,&r.initialReturnBytes},{r.sharedWorkerRva,&r.sharedWorkerBytes},{r.producerRva,&r.producerBytes},{r.producerCallRva,&r.producerCallBytes},{r.typedActorLookupRva,&r.typedActorLookupBytes},{r.targetBuilderVectorRva,&r.targetBuilderVectorBytes},{r.differentialParsedRva,&r.differentialParsedBytes},{r.idSerializationRva,&r.idSerializationBytes},{r.typeSerializationRva,&r.typeSerializationBytes}})Require(PeBytesAtRva(image,uint32_t(item.first),item.second->size())==*item.second,"profile fingerprint mismatch");auto broken=r;broken.initialCallBytes[1]^=1;std::string reason;Require(!aoe::RuntimeLayoutSupportsInitialNx(broken,reason),"critical fingerprint/call mismatch blocks replay");});
    check("unknown build cannot auto attach or arm",[]{auto settings=aoe::SafeDefaultSettings();settings.autoAttach=settings.autoArm=true;Require(aoe::NextAutoAction(settings,true,false,false,false,false)==aoe::AutoAction::None,"unknown attach blocked");Require(aoe::NextAutoAction(settings,true,false,false,true,false)==aoe::AutoAction::None,"unknown arm blocked");});
    check("profile resolves RVAs from each live module base",[&]{aoe::BuildProfile profile;std::filesystem::path selected;std::string error;Require(aoe::SelectBuildProfile(profileDir,aoe::ApprovedHash,profile,selected,error),error);std::vector<aoe::ResolvedAnchor> first,second;auto one=Target(1,2,0x140000000),two=Target(1,2,0x7FF600000000);Require(aoe::ResolveAndValidateProfile(profile,one,first,error),error);Require(aoe::ResolveAndValidateProfile(profile,two,second,error),error);Require(first.size()==11&&first[0].address==one.base+first[0].rva&&second[0].address==two.base+second[0].rva&&first[0].address!=second[0].address,"fresh absolute addresses");});
    check("PID creation time and module base changes invalidate session",[&]{aoe::BuildProfile profile;std::filesystem::path selected;std::string error;Require(aoe::SelectBuildProfile(profileDir,aoe::ApprovedHash,profile,selected,error),error);aoe::ManagerSession session;auto original=Target();Require(aoe::BeginManagerSession(profile,original,session,error),error);auto changed=original;++changed.pid;Require(!aoe::ManagerSessionMatches(session,changed),"PID change");changed=original;++changed.creationTime;Require(!aoe::ManagerSessionMatches(session,changed),"creation change");changed=original;changed.base+=0x100000;Require(!aoe::ManagerSessionMatches(session,changed),"base change");aoe::InvalidateManagerSession(session);Require(!session.active&&session.pid==0&&session.creationTime==0&&session.moduleBase==0&&session.anchors.empty(),"all runtime state cleared");});
    check("fresh restart creates fresh resolved session",[&]{aoe::BuildProfile profile;std::filesystem::path selected;std::string error;aoe::SelectBuildProfile(profileDir,aoe::ApprovedHash,profile,selected,error);aoe::ManagerSession session;auto first=Target(10,20,0x140000000);Require(aoe::BeginManagerSession(profile,first,session,error),error);auto oldAddress=session.anchors.front().address;aoe::InvalidateManagerSession(session);auto next=Target(11,30,0x150000000);Require(aoe::BeginManagerSession(profile,next,session,error),error);Require(session.pid==11&&session.creationTime==30&&session.anchors.front().address!=oldAddress,"new session recalculated");});
    check("session invalidation destroys every process debugger and replay field",[&]{aoe::BuildProfile profile;std::filesystem::path selected;std::string error;Require(aoe::SelectBuildProfile(profileDir,aoe::ApprovedHash,profile,selected,error),error);aoe::ManagerSession session;Require(aoe::BeginManagerSession(profile,Target(),session,error),error);session.processHandleValue=0x1234;session.threadIds={41,42};session.breakpointsInstalled=true;session.debugRegisterBookkeeping=true;session.runtimeArmed=true;session.experiment.armed=true;session.experiment.repeatPending=true;session.experiment.initialCallsObserved=3;session.experiment.firstInitialCall.rip=0xDEADBEEF;aoe::InvalidateManagerSession(session,"TClient exited");Require(session.generation==1&&session.pid==0&&session.creationTime==0&&session.processHandleValue==0&&session.moduleBase==0&&session.sha256.empty()&&session.anchors.empty(),"process identity cleared");Require(session.threadIds.empty()&&!session.debuggerAttached&&!session.breakpointsInstalled&&!session.debugRegisterBookkeeping,"debugger identity cleared");Require(!session.runtimeArmed&&!session.experiment.armed&&!session.experiment.repeatPending&&session.experiment.initialCallsObserved==0&&session.experiment.firstInitialCall.rip==0,"experiment destroyed");Require(session.lastEndReason=="TClient exited"&&session.lifecycle==aoe::SessionLifecycle::Invalidating,"end reason preserved");});
    check("restart increments generation and reloads same SHA profile",[&]{aoe::BuildProfile firstProfile,secondProfile;std::filesystem::path firstPath,secondPath;std::string error;Require(aoe::SelectBuildProfile(profileDir,aoe::ApprovedHash,firstProfile,firstPath,error),error);aoe::ManagerSession session;Require(aoe::BeginManagerSession(firstProfile,Target(21,31,0x140000000),session,error),error);Require(session.generation==1,"generation one");aoe::InvalidateManagerSession(session,"exit");Require(aoe::SelectBuildProfile(profileDir,aoe::ApprovedHash,secondProfile,secondPath,error),error);Require(aoe::BeginManagerSession(secondProfile,Target(22,32,0x160000000),session,error),error);Require(session.generation==2&&session.pid==22&&firstPath==secondPath&&secondProfile.targetSha256==aoe::ApprovedHash,"fresh same-SHA session");});
    check("fresh debugger and breakpoint state gates runtime armed display",[&]{aoe::BuildProfile profile;std::filesystem::path selected;std::string error;aoe::SelectBuildProfile(profileDir,aoe::ApprovedHash,profile,selected,error);aoe::ManagerSession session;Require(aoe::BeginManagerSession(profile,Target(),session,error),error);aoe::Initial2xExperiment experiment;experiment.armed=true;Require(!aoe::MarkRuntimeArmed(session,experiment,error)&&!aoe::CanDisplayAutoArmed(session),"breakpoints required");aoe::ApplyDebuggerSnapshot(session,0xCAFE,{51,52},true,true);Require(aoe::MarkRuntimeArmed(session,experiment,error)&&aoe::CanDisplayAutoArmed(session),error);Require(session.processHandleValue==0xCAFE&&session.threadIds.size()==2&&session.debugRegisterBookkeeping,"fresh debugger snapshot");});
    check("auto arm configuration survives runtime invalidation",[]{aoe::ManagerSettings settings=aoe::SafeDefaultSettings();settings.autoAttach=true;settings.autoArm=true;settings.initialCalls=5;aoe::ManagerSession session;session.generation=4;session.runtimeArmed=true;session.breakpointsInstalled=true;aoe::InvalidateManagerSession(session,"exit");Require(settings.autoAttach&&settings.autoArm&&settings.initialCalls==5,"configuration retained");Require(!session.runtimeArmed&&!session.breakpointsInstalled,"runtime cleared");});
    check("failed new-session validation reports exact reason and rejects stale state",[&]{aoe::BuildProfile profile;std::filesystem::path selected;std::string error;aoe::SelectBuildProfile(profileDir,aoe::ApprovedHash,profile,selected,error);aoe::ManagerSession session;Require(aoe::BeginManagerSession(profile,Target(70,80,0x140000000),session,error),error);auto stale=Target(71,81,0x150000000);stale.image.sha256=std::string(64,'A');Require(!aoe::ManagerSessionMatches(session,stale),"stale state rejected");aoe::InvalidateManagerSession(session,"exit");Require(!aoe::BeginManagerSession(profile,stale,session,error),"hash mismatch rejected");Require(error=="Live target hash does not match the selected profile.","exact validation error");Require(!session.active&&!session.profileValid&&!session.runtimeArmed,"failed session inactive");});
    check("auto flow attaches then arms only after validation",[]{auto settings=aoe::SafeDefaultSettings();settings.autoAttach=settings.autoArm=true;Require(aoe::NextAutoAction(settings,true,true,false,false,false)==aoe::AutoAction::Attach,"known process attach");Require(aoe::NextAutoAction(settings,true,true,false,true,false)==aoe::AutoAction::None,"unvalidated arm blocked");Require(aoe::NextAutoAction(settings,true,true,true,true,false)==aoe::AutoAction::Arm,"validated arm");Require(aoe::NextAutoAction(settings,true,true,true,true,true)==aoe::AutoAction::None,"already armed");});
    check("startup setting uses only the named per-user Run value",[]{std::wstring written;bool removed=false;aoe::StartupRegistryIo io{[&](const std::wstring& command,std::string& error){written=command;error.clear();return true;},[&](std::string& error){removed=true;error.clear();return true;}};std::string error;auto exe=std::filesystem::path(LR"(C:\Program Files\4Unity\4UnityAOEManager.exe)");Require(aoe::ApplyStartupSetting(io,true,exe,error)&&written==L"\"C:\\Program Files\\4Unity\\4UnityAOEManager.exe\"","quoted startup command");Require(aoe::ApplyStartupSetting(io,false,exe,error)&&removed,"own value removal");});
    check("profile and settings persist no runtime pointers or identities",[&]{auto profilePath=profileDir/(std::wstring(aoe::ApprovedHash,aoe::ApprovedHash+64)+L".json");std::ifstream p(profilePath);std::string profileJson((std::istreambuf_iterator<char>(p)),{});for(auto forbidden:{"absoluteAddress","moduleBase","threadId","heapPointer","processId","creationTime"})Require(profileJson.find(forbidden)==std::string::npos,forbidden);auto settingsPath=artifacts/L"manager-settings"/L"settings.json";std::ifstream s(settingsPath);std::string settingsJson((std::istreambuf_iterator<char>(s)),{});for(auto forbidden:{"moduleBase","threadId","heapPointer","processId","creationTime"})Require(settingsJson.find(forbidden)==std::string::npos,forbidden);});
    check("three required manager tabs exist",[]{Require(aoe::ManagerTabCount==3,"tab count");Require(std::wstring(aoe::ManagerTabName(aoe::ManagerTab::ResearchRecovery))==L"Research / Recovery","research tab");Require(std::wstring(aoe::ManagerTabName(aoe::ManagerTab::Profiles))==L"Profiles","profiles tab");Require(std::wstring(aoe::ManagerTabName(aoe::ManagerTab::Play))==L"Play","play tab");});
    check("layout calculations fit normal minimum and maximized pages",[]{for(const auto page:{aoe::UiRect{28,122,900,480},aoe::UiRect{36,130,1840,850}}){auto research=aoe::CalculateResearchLayout(page,96);auto profiles=aoe::CalculateProfilesLayout(page,96);auto play=aoe::CalculatePlayLayout(page,96);Require(aoe::RectFits(page,research.heading)&&aoe::RectFits(page,research.viewer),"research fits");for(const auto& button:research.buttons)Require(aoe::RectFits(page,button),"research button fits");Require(aoe::RectFits(page,profiles.summary)&&aoe::RectFits(page,profiles.list),"profiles fits");Require(aoe::RectFits(page,play.status)&&aoe::RectFits(page,play.save)&&aoe::RectFits(page,play.diagnostics),"play fits");}});
    check("layout restore is deterministic and minimum client is enforced",[]{auto before=aoe::MainTabBounds(1100,720,96);auto maximized=aoe::MainTabBounds(1920,1080,96);auto restored=aoe::MainTabBounds(1100,720,96);Require(before.x==restored.x&&before.y==restored.y&&before.width==restored.width&&before.height==restored.height,"restore geometry");Require(maximized.width>before.width&&maximized.height>before.height,"maximize geometry");Require(aoe::MinimumClientWidth96==960&&aoe::MinimumClientHeight96==650,"minimum client");auto highDpi=aoe::MainTabBounds(1440,975,144);Require(highDpi.x==30&&highDpi.y==117,"DPI scaling");});
    check("tab display page layouts use an adjusted client rectangle",[]{auto tab=aoe::MainTabBounds(1200,760,96);aoe::UiRect adjusted{tab.x+8,tab.y+30,tab.width-16,tab.height-38};auto profile=aoe::CalculateProfilesLayout(adjusted,96);Require(profile.heading.x==adjusted.x&&profile.list.x==adjusted.x,"adjusted origin");Require(profile.list.y>=adjusted.y&&profile.list.y+profile.list.height==adjusted.y+adjusted.height,"adjusted bottom");});
    check("tab and diagnostics visibility remains deterministic across transitions",[]{auto research=aoe::CalculatePageVisibility(0,true);Require(research.research&&!research.profiles&&!research.play&&!research.diagnostics,"research");auto playClosed=aoe::CalculatePageVisibility(2,false);Require(playClosed.play&&!playClosed.diagnostics,"play closed");auto playOpen=aoe::CalculatePageVisibility(2,true);Require(playOpen.play&&playOpen.diagnostics,"play open");auto profiles=aoe::CalculatePageVisibility(1,true);Require(profiles.profiles&&!profiles.play&&!profiles.diagnostics,"profiles");});
    check("research Target Inspector layout fits minimum and maximized pages",[]{for(const auto page:{aoe::UiRect{28,122,900,480},aoe::UiRect{36,130,1840,850}}){auto r=aoe::CalculateResearchLayout(page,96);Require(aoe::RectFits(page,r.inspectorHeading)&&aoe::RectFits(page,r.inspectorPrepare)&&aoe::RectFits(page,r.inspectorStatus)&&aoe::RectFits(page,r.inspectorList)&&aoe::RectFits(page,r.provenanceHeading)&&aoe::RectFits(page,r.provenanceStatus)&&aoe::RectFits(page,r.provenanceOutput),"research sections fit");for(const auto& button:r.inspectorButtons)Require(aoe::RectFits(page,button),"inspector button fits");for(const auto& button:r.provenanceButtons)Require(aoe::RectFits(page,button),"provenance button fits");}});
    check("Target Inspector start requires attached valid session rather than detached state",[]{auto ready=aoe::CalculateTargetInspectorAvailability(true,true,false,false,false,false);Require(ready.startEnabled&&!ready.prepareEnabled&&ready.reason.find("Ready:")==0,"attached valid ready");auto detached=aoe::CalculateTargetInspectorAvailability(false,true,false,false,false,false);Require(!detached.startEnabled&&detached.reason=="Unavailable: TClient not attached","detached reason");auto invalid=aoe::CalculateTargetInspectorAvailability(true,false,false,false,false,false);Require(!invalid.startEnabled&&invalid.reason=="Unavailable: Profile not validated","profile reason");});
    check("armed Initial Nx exposes prepare action and explicit reason",[]{auto blocked=aoe::CalculateTargetInspectorAvailability(true,true,false,true,false,false);Require(!blocked.startEnabled&&blocked.prepareEnabled&&blocked.suppressAutoArm,"prepare available");Require(blocked.reason.find("Initial Nx currently armed")!=std::string::npos,"explicit conflict reason");});
    check("prepared inspector enables start and suppresses Auto Arm race",[]{auto prepared=aoe::CalculateTargetInspectorAvailability(true,true,false,false,false,true);Require(prepared.startEnabled&&prepared.suppressAutoArm&&prepared.reason.find("conflict released")!=std::string::npos,"prepared ready");auto running=aoe::CalculateTargetInspectorAvailability(true,true,true,false,false,false);Require(!running.startEnabled&&running.suppressAutoArm&&running.reason=="Unavailable: Inspector already running","running suppresses auto arm");});
    check("breakpoint transition failures are visible and recoverable",[]{auto failed=aoe::CalculateTargetInspectorAvailability(true,true,false,false,false,false,"Breakpoint slot unavailable");Require(!failed.startEnabled&&failed.prepareEnabled&&failed.reason=="Unavailable: Breakpoint slot unavailable","visible failure");});
    check("buffered parent paint preserves native child invalidation",[&]{std::ifstream input(root/L"src"/L"main.cpp");std::string source((std::istreambuf_iterator<char>(input)),{});Require(source.find("WS_OVERLAPPEDWINDOW|WS_CLIPCHILDREN")!=std::string::npos,"parent clips children");Require(source.find("SWP_NOREDRAW")==std::string::npos,"layout does not suppress child redraw");Require(source.find("RDW_INVALIDATE|RDW_ERASE|RDW_ALLCHILDREN")!=std::string::npos,"all main-window children invalidated at transitions");Require(source.find("BitBlt(dc,ps.rcPaint.left")!=std::string::npos,"backbuffer blit limited to paint region");});
    check("page controls do not clip against the overlapping tab sibling",[&]{std::ifstream input(root/L"src"/L"main.cpp");std::string source((std::istreambuf_iterator<char>(input)),{});Require(source.find("WS_CHILD|WS_VISIBLE|WS_CLIPSIBLINGS|style")==std::string::npos,"page child style restored");Require(source.find("WC_TABCONTROLW,L\"\",WS_CHILD|WS_VISIBLE|WS_CLIPSIBLINGS")!=std::string::npos,"tab retains sibling clipping");Require(source.find("RenderedPageColorCount")!=std::string::npos&&source.find("ValidatePopulatedPage")!=std::string::npos,"smoke verifies rendered pixels");});
    check("Research UI keeps READ ONLY label, sequential marker controls, and Auto Arm session gate",[&]{std::ifstream input(root/L"src"/L"main.cpp");std::string source((std::istreambuf_iterator<char>(input)),{});Require(source.find("AOE Target Differential Inspector (READ ONLY)")!=std::string::npos,"read only label");Require(source.find("PREPARE TARGET DIFFERENTIAL INSPECTOR")!=std::string::npos,"prepare action");Require(source.find("CANCEL CURRENT MARK")!=std::string::npos,"cancel marker action");Require(source.find("running&&CanMarkNextTargetCapture(inspector)")!=std::string::npos,"MARK follows capture-slot lifecycle");Require(source.find("ALL CAPTURES COMPLETE")!=std::string::npos&&source.find("Waiting for Capture")!=std::string::npos,"explicit marker status");Require(source.find("!ResearchModeActive()&&profile.runtime.initialNxAvailable")!=std::string::npos&&source.find("ShouldAutoArmAfterValidation")!=std::string::npos,"auto arm gated by research intent and live validation");Require(source.find("targetInspectorSelected=false;notice=L\"Target Differential Inspector stopped")!=std::string::npos,"saved auto arm may resume after stop");});
    check("Selected Target Provenance UI remains read only and labels the failed live candidate",[&]{std::ifstream input(root/L"src"/L"main.cpp");std::string source((std::istreambuf_iterator<char>(input)),{});Require(source.find("STATIC TARGET-STATE CANDIDATE game+0x2318 (READ ONLY)")!=std::string::npos,"read only provenance label");Require(source.find("UNPROVEN — returned NULL in prior manual captures")!=std::string::npos,"failed live validation label");for(auto text:{"CAPTURE A","CAPTURE B","CAPTURE C","CAPTURE NONE","ExportSelectedTargetProvenanceJson"})Require(source.find(text)!=std::string::npos,text);Require(source.find("InitialNxConflictsWithTargetInspector(tracerStatus.initial2x)")!=std::string::npos,"armed Nx blocks provenance start");Require(source.find("bool ResearchModeActive()const{return targetInspectorSelected||provenanceSelected||writerSelected;}")!=std::string::npos,"all research modes suppress auto arm");Require(source.find("zero additional hardware breakpoints")!=std::string::npos,"snapshot mode uses no new slots");Require(source.find("saved Auto Arm preference unchanged")!=std::string::npos,"saved preference preserved");});
    check("Target Writer UI is read only, phase labelled, bounded, and mutually exclusive",[&]{std::ifstream input(root/L"src"/L"main.cpp");std::string source((std::istreambuf_iterator<char>(input)),{});for(auto text:{"TARGET WRITER RUNTIME INSPECTOR (READ ONLY)","SET PHASE: SELECTION","SET PHASE: NORMAL ATTACK","SET PHASE: AOE CAST","SET PHASE: OTHER","CLEAR EVENTS","TargetWriterEventLimit","writerSelected"})Require(source.find(text)!=std::string::npos,text);Require(source.find("Starting Target Writer Runtime Inspector · Initial Nx released · Auto Arm temporarily suppressed")!=std::string::npos,"safe Initial Nx release and Auto Arm suppression");Require(source.find("saved Auto Arm behavior may resume")!=std::string::npos,"Auto Arm resumes only after stop");});
    check("Target Writer path contains no gameplay write or RIP redirect",[&]{for(auto name:{L"target_writer_runtime.cpp",L"target_writer_runtime.hpp"}){std::ifstream input(root/L"src"/name);std::string source((std::istreambuf_iterator<char>(input)),{});Require(source.find("WriteProcessMemory")==std::string::npos,"no WriteProcessMemory");Require(source.find("context.Rip=")==std::string::npos&&source.find("Context.Rip=")==std::string::npos,"no RIP redirect");}});
    check("Initial Calls remains editable and configures a separate next experiment",[&]{std::ifstream input(root/L"src"/L"main.cpp");std::string source((std::istreambuf_iterator<char>(input)),{});Require(source.find("id==InitialCalls&&code==EN_CHANGE")!=std::string::npos,"edit change handled");Require(source.find("EnableWindow(initialCalls,TRUE)")!=std::string::npos&&source.find("EnableWindow(GetDlgItem(window,InitialSpin),TRUE)")!=std::string::npos,"input and spinner remain editable");Require(source.find("Last Nx result:")!=std::string::npos&&source.find("Next Nx:")!=std::string::npos,"last and next status separated");});
    check("Initial Nx ARM control is an explicit continuous ON OFF latch",[&]{std::ifstream input(root/L"src"/L"main.cpp");std::string source((std::istreambuf_iterator<char>(input)),{});Require(source.find("INITIAL Nx CONTINUOUS (ON/OFF)")!=std::string::npos&&source.find("ToggleContinuousNx")!=std::string::npos,"continuous toggle UI");Require(source.find("continuous_nx_rearm_queued")!=std::string::npos&&source.find("ShouldQueueContinuousInitialNx")!=std::string::npos,"successful cast queues same-N re-arm");Require(source.find("current cast will finish; no next re-arm")!=std::string::npos,"OFF preserves active cast and stops the next one");});
    check("diagnostics snapshot contains stable copy fields and resolved addresses",[]{aoe::DiagnosticsSnapshot d;d.sessionGeneration=2;d.pid=61234;d.processCreationTime=99;d.moduleBase=0x7FF600000000;d.targetSha256=aoe::ApprovedHash;d.profileStatus="VALID";d.profileName="known.json";d.debuggerAttached=d.breakpointsInstalled=d.runtimeArmed=d.configuredAutoArm=true;d.initialCalls=5;d.observedInitialCalls=3;d.configurationDetails="Initial Calls configured: 5";d.lastExperimentDetails="Target: 2\r\nObserved initial calls: 2\r\nRIP redirects: 1\r\nResult: COMPLETED";d.nextExperimentDetails="Target: 5\r\nState: ARMED FOR NEXT CAST";d.threadIds={30296};d.breakpointThreads=1;d.breakpointCoverage={{30296,aoe::InitialPrepareRva,d.moduleBase+aoe::InitialPrepareRva,0,true,false,false,false},{30296,aoe::InitialCallRva,d.moduleBase+aoe::InitialCallRva,1,true,true,false,false},{30296,aoe::InitialReturnRva,d.moduleBase+aoe::InitialReturnRva,2,true,true,false,false}};d.lastSessionEndReason="Target exited";d.addresses={{"initialPrep",aoe::InitialPrepareRva,d.moduleBase+aoe::InitialPrepareRva},{"sharedWorker",aoe::Caller020ARva,d.moduleBase+aoe::Caller020ARva}};const auto text=aoe::RenderDiagnosticsSnapshot(d);for(auto required:{"Session Generation: 2","PID: 61234","Process Creation Time: 99","Target SHA-256:","Profile Status: VALID","Debugger Attached: YES","Breakpoints Installed: YES","Runtime Armed: YES","Configured Auto Arm: ON","Initial Calls configured: 5","Observed Initial Calls: 3","CONFIGURATION:","LAST Nx EXPERIMENT:","Result: COMPLETED","NEXT Nx EXPERIMENT:","State: ARMED FOR NEXT CAST","thread 30296 validation coverage: YES (3 / 3)","thread 30296 · DR0","TClient.exe+7F0900 | 0x"})Require(text.find(required)!=std::string::npos,required);});
    check("diagnostics cache avoids duplicate and interactive updates",[]{aoe::DiagnosticsRenderCache cache;Require(cache.update("one",false),"initial update");Require(!cache.update("one",false),"duplicate suppressed");Require(!cache.update("two",true)&&cache.rendered()=="one"&&cache.latest()=="two","interaction preserves visible text");Require(cache.update("two",false)&&cache.rendered()=="two","deferred latest rendered");});
    check("diagnostics freeze retains latest and does not mutate runtime session",[]{aoe::ManagerSession session;session.generation=7;session.pid=77;session.runtimeArmed=true;aoe::DiagnosticsRenderCache cache;cache.update("before",false);std::string render;Require(!cache.setFrozen(true,render)&&cache.frozen(),"frozen");Require(!cache.update("after",false)&&cache.rendered()=="before"&&cache.latest()=="after","visible frozen");Require(session.generation==7&&session.pid==77&&session.runtimeArmed,"runtime unchanged");Require(cache.setFrozen(false,render)&&render=="after"&&!cache.frozen(),"unfreeze latest");Require(session.generation==7,"generation survives UI refresh");});
    check("golden executable hash is unchanged during manager tests",[&]{Require(goldenBefore=="274153A6B4FDE921769D3F5650FED9E47E08EE91B32F4A639758943B5EF62C9E","expected golden baseline");Require(FileHash(golden)==goldenBefore,"golden post-test hash");});
    return passed;
}



