#include "target_writer_runtime.hpp"
#include <algorithm>
#include <array>
#include <cstring>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <stdexcept>

namespace {
void Require(bool value,const std::string& message){if(!value)throw std::runtime_error(message);}
struct Memory {std::map<uint64_t,uint8_t> bytes;template<class T>void put(uint64_t at,const T& value){const auto* p=reinterpret_cast<const uint8_t*>(&value);for(size_t i=0;i<sizeof(value);++i)bytes[at+i]=p[i];}void raw(uint64_t at,const void* value,size_t size){const auto* p=static_cast<const uint8_t*>(value);for(size_t i=0;i<size;++i)bytes[at+i]=p[i];}bool read(uint64_t at,void* out,size_t size,uint32_t& error)const{auto* p=static_cast<uint8_t*>(out);for(size_t i=0;i<size;++i){auto it=bytes.find(at+i);if(it==bytes.end()){error=299;return false;}p[i]=it->second;}error=0;return true;}};
aoe::InspectorRead Reader(const Memory& memory){return[&memory](uint64_t a,void* d,size_t n,uint32_t& e){return memory.read(a,d,n,e);};}
aoe::RuntimeLayout Layout(){aoe::RuntimeLayout r;r.gameContextPointerRva=0xE6C9C0;r.selectedTargetOffset=0x2318;r.selectedTargetWriterRva=0x7F6411;r.actorIdOffset=0x768;r.actorTypeOffset=0x7E1;r.actorEligibilityOffset=0x7CA;r.actorStatusOffset=0x7E4;r.actorWorldLinkOffset=0x1390;r.actorWorldLinkOwnerOffset=0x1380;r.actorWorldPositionOffset=0x70;r.actorTreeOffsets[1]=0x1140;r.actorTreeOffsets[2]=0x1120;return r;}
struct Fixture {Memory memory;aoe::RuntimeLayout layout=Layout();uint64_t module=0x140000000,game=0x100000,actor=0x200000,oldValue=0x900000;Fixture(uint8_t category=2){const uint8_t readableGame=0;memory.put(module+layout.gameContextPointerRva,game);memory.put(game,readableGame);memory.put(game+layout.selectedTargetOffset,oldValue);const uint32_t id=101,status=7;const uint8_t eligible=1;memory.put(actor+layout.actorIdOffset,id);memory.put(actor+layout.actorTypeOffset,category);memory.put(actor+layout.actorEligibilityOffset,eligible);memory.put(actor+layout.actorStatusOffset,status);const uint64_t treeOffset=layout.actorTreeOffsets[category],header=0x300000,node=0x301000,sentinel=0x302000;if(treeOffset){const uint8_t zero=0,one=1;memory.put(game+treeOffset,header);memory.put(header+8,node);memory.put(node,sentinel);memory.put(node+0x19,zero);memory.put(node+0x20,id);memory.put(node+0x28,actor);memory.put(sentinel+0x19,one);}if(category==2){const uint64_t link=0x400000;memory.put(actor+layout.actorWorldLinkOffset,link);memory.put(link+layout.actorWorldLinkOwnerOffset,actor);std::array<float,3> xyz{10,20,30};memory.raw(link+layout.actorWorldPositionOffset,xyz.data(),sizeof(xyz));}}aoe::TargetWriterEvent capture(aoe::TargetWriterPhase phase=aoe::TargetWriterPhase::Selection,uint64_t r8=0)const{aoe::TargetWriterRegisters regs;regs.rip=module+layout.selectedTargetWriterRva;regs.rbx=game;regs.r8=r8?r8:actor;regs.rdx=3;regs.rcx=4;regs.r9=5;regs.rsp=6;return aoe::CaptureTargetWriterEvent(Reader(memory),layout,module,phase,1,25,77,regs);}};
}

unsigned TargetWriterRuntimeTests(const std::filesystem::path& artifacts){unsigned passed=0;auto check=[&](const char* name,const std::function<void()>& fn){fn();++passed;std::cout<<"[PASS] "<<name<<'\n';};
    check("writer event captures RBX and R8",[]{Fixture f;auto e=f.capture();Require(e.registers.rbx==f.game&&e.registers.r8==f.actor&&e.registers.rip==f.module+0x7F6411,"register capture");});
    check("effective destination is RBX plus 0x2318",[]{Fixture f;auto e=f.capture();Require(e.effectiveDestination==f.game+0x2318,"destination");});
    check("pre-store and expected stored values remain distinct",[]{Fixture f;auto e=f.capture();Require(e.destinationReadable&&e.valueBefore==f.oldValue&&e.expectedStoredValue==f.actor,"pre and expected");});
    check("post-store is never claimed without observation",[]{Fixture f;auto e=f.capture();Require(!e.postStoreObserved&&e.observedPostStoreValue==0,"post-store label");});
    check("global storage uses module base plus profile RVA",[]{Fixture f;auto e=f.capture();Require(e.globalStorageAddress==f.module+0xE6C9C0&&e.globalRawValue==f.game,"global address");});
    check("RBX global equality is detected",[]{Fixture f;Require(f.capture().rbxMatchesGlobalValue,"global equality");});
    check("R8 category 2 actor and XYZ validate",[]{Fixture f;auto e=f.capture();Require(e.r8ActorValid&&e.actor.actorId==101&&e.actor.category==2&&e.actor.positionAvailable&&e.actor.position.value==std::array<float,3>{10,20,30}&&e.resolverMatched,"monster validation");});
    check("monster XYZ rejects a link owned by another actor",[]{Fixture f;const uint64_t link=0x400000,other=0x210000;f.memory.put(link+f.layout.actorWorldLinkOwnerOffset,other);auto e=f.capture();Require(e.r8ActorValid&&e.actor.category==2&&!e.actor.positionAvailable,"link ownership validation");});
    check("R8 category 1 actor classifies as character",[]{Fixture f(1);auto e=f.capture();Require(e.r8ActorValid&&e.actor.category==1&&std::string(aoe::TargetActorTypeName(e.actor.category))=="CTClientChar"&&!e.actor.positionAvailable,"character classification");});
    check("null R8 remains safe",[]{Fixture f;auto e=f.capture(aoe::TargetWriterPhase::Selection,1);e=aoe::CaptureTargetWriterEvent(Reader(f.memory),f.layout,f.module,aoe::TargetWriterPhase::Selection,1,1,1,{f.module+0x7F6411,f.game,0,0,0,0,0});Require(e.r8Null&&!e.r8ActorValid,"null R8");});
    check("unreadable RBX destination is explicit",[]{Fixture f;aoe::TargetWriterRegisters r{f.module+0x7F6411,0x700000,f.actor,0,0,0,0};auto e=aoe::CaptureTargetWriterEvent(Reader(f.memory),f.layout,f.module,aoe::TargetWriterPhase::Other,1,1,1,r);Require(!e.destinationReadable&&e.destinationReadError==299,"unreadable destination");});
    check("invalid global pointer is not accepted",[]{Fixture f;const uint64_t invalid=1;f.memory.put(f.module+f.layout.gameContextPointerRva,invalid);auto e=f.capture();Require(e.globalReadable&&!e.globalPointerValid&&!e.rbxMatchesGlobalValue&&!e.resolverMatched,"invalid global");});
    check("selection normal attack and AOE phases are retained",[]{Fixture f;Require(f.capture(aoe::TargetWriterPhase::Selection).phase==aoe::TargetWriterPhase::Selection,"selection");Require(f.capture(aoe::TargetWriterPhase::NormalAttack).phase==aoe::TargetWriterPhase::NormalAttack,"attack");Require(f.capture(aoe::TargetWriterPhase::AoeCast).phase==aoe::TargetWriterPhase::AoeCast,"AOE");});
    check("event buffer is bounded to 100",[]{aoe::TargetWriterRuntimeSession s;s.state=aoe::TargetWriterState::Running;for(size_t i=0;i<aoe::TargetWriterEventLimit;++i)Require(aoe::RecordTargetWriterEvent(s,{}),"record bounded event");Require(s.events.size()==100&&s.bufferFull&&!aoe::RecordTargetWriterEvent(s,{}),"buffer full");});
    check("clear events preserves running phase",[]{aoe::TargetWriterRuntimeSession s;s.state=aoe::TargetWriterState::Running;s.currentPhase=aoe::TargetWriterPhase::NormalAttack;s.events.push_back({});s.bufferFull=true;aoe::ClearTargetWriterEvents(s);Require(s.events.empty()&&!s.bufferFull&&s.currentPhase==aoe::TargetWriterPhase::NormalAttack,"clear");});
    check("default mode uses exactly one breakpoint",[]{Require(aoe::TargetWriterBreakpointCount==1,"one breakpoint");});
    check("empty session remains unproven",[]{aoe::TargetWriterRuntimeSession s;auto a=aoe::AnalyzeTargetWriterRuntime(s);Require(a.classifications.front()==aoe::TargetWriterConclusionState::WriterNotObserved&&std::none_of(a.classifications.begin(),a.classifications.end(),[](auto c){return std::string(aoe::TargetWriterConclusionName(c))=="PROVEN_SELECTED_TARGET";}),"unproven default");});
    check("multiple selection monsters become candidate only",[]{aoe::TargetWriterRuntimeSession s;for(int i=0;i<2;++i){aoe::TargetWriterEvent e;e.phase=aoe::TargetWriterPhase::Selection;e.registers.r8=0x200000+i*0x1000;e.actor.identityReadable=true;e.actor.category=2;e.globalReadable=e.rbxMatchesGlobalValue=true;s.events.push_back(e);}auto a=aoe::AnalyzeTargetWriterRuntime(s);Require(std::find(a.classifications.begin(),a.classifications.end(),aoe::TargetWriterConclusionState::SelectionWriterCandidate)!=a.classifications.end(),"selection candidate");});
    check("runtime JSON exports explicit observation semantics",[&]{Fixture f;aoe::TargetWriterRuntimeSession s;s.events.push_back(f.capture());auto path=artifacts/L"target-writer-runtime.json";std::string error;Require(aoe::ExportTargetWriterRuntimeJson(path,s,error),error);std::ifstream in(path);std::string json((std::istreambuf_iterator<char>(in)),{});for(auto token:{"targetWriterRuntime","breakpointsPerThread","valueBefore","expectedStoredValue","postStoreObserved","rbxMatchesGlobal","CTClientMonster","WRITER_OBSERVED_MONSTER_VALUE"})Require(json.find(token)!=std::string::npos,token);});
    return passed;
}
