#include "target_inspector.hpp"
#include <algorithm>
#include <cstring>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <stdexcept>

namespace {
void Require(bool condition,const std::string& message){if(!condition)throw std::runtime_error(message);}
struct Memory {
    std::map<uint64_t,uint8_t> bytes;
    template<class T> void put(uint64_t address,const T& value){const auto* p=reinterpret_cast<const uint8_t*>(&value);for(size_t i=0;i<sizeof(value);++i)bytes[address+i]=p[i];}
    void putBytes(uint64_t address,const uint8_t* data,size_t count){for(size_t i=0;i<count;++i)bytes[address+i]=data[i];}
    bool read(uint64_t address,void* destination,size_t size,uint32_t& error)const{auto* out=static_cast<uint8_t*>(destination);for(size_t i=0;i<size;++i){auto it=bytes.find(address+i);if(it==bytes.end()){error=299;return false;}out[i]=it->second;}error=0;return true;}
};
aoe::InspectorRead Reader(const Memory& memory){return [&memory](uint64_t address,void* destination,size_t size,uint32_t& error){return memory.read(address,destination,size,error);};}
aoe::RuntimeLayout Layout(){aoe::RuntimeLayout r;r.initialCallRva=0x7F091D;r.typedActorLookupRva=0x7B9BD0;r.targetVectorOffset=0x660;r.actorIdOffset=0x768;r.actorTypeOffset=0x7E1;r.localActorOffset=0x2710;r.actorPositionOffset=0xB0;r.actorWorldLinkOffset=0x1390;r.actorWorldLinkOwnerOffset=0x1380;r.actorWorldPositionOffset=0x70;r.selectedTargetOffset=0x2318;r.actorTreeOffsets[1]=0x1140;r.actorTreeOffsets[2]=0x1120;r.actorTreeOffsets[7]=0x11B0;r.actorTreeOffsets[9]=0x1130;r.actorTreeOffsets[10]=0xC6FF00;r.actorTreeOffsets[11]=0x11A0;r.actorTreeOffsets[17]=0x1150;r.actorTreeOffsets[19]=0x11E0;r.targetRecordBytes=8;r.targetMaximumEntries=32;return r;}
void Arm(aoe::TargetInspectorSession& session,uint64_t id){aoe::Marker marker{id,"Capture "+std::string(1,char('A'+id-1)),0,0};std::string error;Require(aoe::ArmNextTargetCapture(session,marker,error),error);}
}

unsigned TargetInspectorTests(const std::filesystem::path& artifacts){unsigned passed=0;auto check=[&](const char* name,const std::function<void()>& test){test();++passed;std::cout<<"[PASS] "<<name<<'\n';};
    check("Target Differential Inspector mode is isolated from Initial Nx replay",[]{Require(aoe::TraceRva(aoe::TraceMode::TargetInspector)==aoe::InitialCallRva,"callsite");Require(std::string(aoe::ModeName(aoe::TraceMode::TargetInspector))=="AOE Target Differential Inspector","name");Require(aoe::TraceMode::TargetInspector!=aoe::TraceMode::Initial2x,"distinct mode");});
    check("prepare releases only the active Initial Nx conflict",[]{aoe::Initial2xExperiment experiment;experiment.armed=true;experiment.phase=aoe::Initial2xPhase::Waiting0209;experiment.pid=77;experiment.moduleBase=0x140000000;Require(aoe::InitialNxConflictsWithTargetInspector(experiment),"conflict detected");Require(aoe::ReleaseInitialNxForTargetInspector(experiment),"conflict released");Require(!experiment.armed&&experiment.pid==0&&experiment.moduleBase==0&&!aoe::InitialNxConflictsWithTargetInspector(experiment),"experiment reset");aoe::Initial2xExperiment idle;Require(!aoe::ReleaseInitialNxForTargetInspector(idle),"idle release does not report a conflict");});
    check("operation classification only captures an initial 0x0209",[]{Memory memory;uint16_t word=0x0209;memory.put(0x20000,word);aoe::TargetInspectorEvent registers;registers.r9=0x20000;auto event=aoe::CaptureTargetInspectorEvent(Reader(memory),Layout(),registers);Require(event.initial0209&&!event.periodic020A,"0209 initial");word=0x020A;memory.put(0x20000,word);event=aoe::CaptureTargetInspectorEvent(Reader(memory),Layout(),registers);Require(!event.initial0209&&event.periodic020A,"020A periodic");});
    check("START makes Capture A markable",[]{aoe::TargetInspectorSession session;session.phase=aoe::TargetInspectorPhase::WaitingForAoe;Require(aoe::CanMarkNextTargetCapture(session)&&aoe::NextTargetCaptureSlot(session)==0,"A ready");});
    check("MARK A disables another mark while waiting for 0x0209",[]{aoe::TargetInspectorSession session;session.phase=aoe::TargetInspectorPhase::WaitingForAoe;Arm(session,1);Require(!aoe::CanMarkNextTargetCapture(session)&&aoe::ArmedTargetCaptureSlot(session)==0,"A armed");std::string error;aoe::Marker duplicate{2,"Capture B",0,0};Require(!aoe::ArmNextTargetCapture(session,duplicate,error)&&error.find("current capture")!=std::string::npos,"double mark refused");});
    check("first 0x0209 captures A and enables MARK B",[]{aoe::TargetInspectorSession session;session.phase=aoe::TargetInspectorPhase::WaitingForAoe;Arm(session,1);aoe::TargetInspectorEvent first;first.initial0209=true;first.sequence=2;Require(aoe::RecordDifferentialEvent(session,first),"first initial retained");Require(session.captureSlots[0].state==aoe::TargetCaptureSlotState::Captured&&session.captureSlots[0].captureSequence==2,"A captured");Require(aoe::CanMarkNextTargetCapture(session)&&aoe::NextTargetCaptureSlot(session)==1,"B ready");aoe::TargetInspectorEvent duplicate;duplicate.initial0209=true;duplicate.sequence=3;Require(!aoe::RecordDifferentialEvent(session,duplicate),"unmarked duplicate refused");});
    check("0x020A after A stays separate and does not disable MARK B",[]{aoe::TargetInspectorSession session;session.phase=aoe::TargetInspectorPhase::WaitingForAoe;Arm(session,1);aoe::TargetInspectorEvent initial;initial.initial0209=true;initial.sequence=1;Require(aoe::RecordDifferentialEvent(session,initial),"A captured");aoe::TargetInspectorEvent periodic;periodic.periodic020A=true;periodic.sequence=2;Require(aoe::RecordDifferentialEvent(session,periodic),"periodic retained");Require(session.periodicEvents.size()==1&&session.periodicEvents[0].markerId==1,"periodic paired to latest capture");Require(aoe::CanMarkNextTargetCapture(session)&&aoe::NextTargetCaptureSlot(session)==1,"B remains ready");});
    check("A B C marker pairing preserves independent initial events",[]{aoe::TargetInspectorSession session;session.phase=aoe::TargetInspectorPhase::WaitingForAoe;for(uint64_t marker=1;marker<=3;++marker){Arm(session,marker);aoe::TargetInspectorEvent event;event.initial0209=true;event.sequence=marker;event.operationRecord[0]=uint8_t(0xA0+marker);Require(aoe::RecordDifferentialEvent(session,event),"marker event");}Require(session.events.size()==3,"three captures");for(size_t i=0;i<3;++i){Require(session.events[i].markerId==i+1,"paired marker");Require(session.events[i].operationRecord[0]==uint8_t(0xA1+i),"distinct record");Require(session.captureSlots[i].state==aoe::TargetCaptureSlotState::Captured,"slot captured");}});
    check("cancel current mark returns the slot to empty and preserves completed captures",[]{aoe::TargetInspectorSession session;session.phase=aoe::TargetInspectorPhase::WaitingForAoe;Arm(session,1);aoe::TargetInspectorEvent initial;initial.initial0209=true;initial.sequence=1;Require(aoe::RecordDifferentialEvent(session,initial),"A captured");Arm(session,2);aoe::ParsedInputCapture parsed;parsed.operation0209=true;parsed.semanticInput=true;Require(aoe::RecordParsedInput(session,parsed),"pending parsed input retained");std::string error;Require(aoe::CancelCurrentTargetCapture(session,error),error);Require(session.captureSlots[0].state==aoe::TargetCaptureSlotState::Captured&&session.captureSlots[1].state==aoe::TargetCaptureSlotState::Empty,"A kept and B reset");Require(session.events.size()==1&&session.events[0].markerId==1&&session.markers.size()==1&&session.parsedInputs.empty(),"prior capture preserved and pending evidence removed");Require(aoe::CanMarkNextTargetCapture(session)&&aoe::NextTargetCaptureSlot(session)==1,"B markable again");});
    check("operation record snapshot is bounded to 0x30 bytes",[]{Memory memory;const uint64_t operationWord=0x100000,record=0x200000;const uint16_t word=0x0209;std::array<uint8_t,aoe::DifferentialOperationRecordBytes> raw{};raw[0]=0x11;raw.back()=0xEE;memory.put(operationWord,word);memory.putBytes(record,raw.data(),raw.size());aoe::TargetInspectorEvent registers;registers.r9=operationWord;registers.r8=record;const auto event=aoe::CaptureTargetInspectorEvent(Reader(memory),Layout(),registers);Require(event.operationRecordReadable&&event.operationRecord.size()==0x30&&event.operationRecord[0]==0x11&&event.operationRecord.back()==0xEE,"bounded record");});
    check("operation +0 +4 +8 preserve raw dwords and decode float32",[]{std::array<uint8_t,aoe::DifferentialOperationRecordBytes> raw{};const std::array<float,3> values{12.5f,-3.25f,999.75f};std::array<uint32_t,3> bits{};for(size_t i=0;i<3;++i){memcpy(&bits[i],&values[i],4);memcpy(raw.data()+i*4,&bits[i],4);}const auto decoded=aoe::DecodeOperationSpatialFields(raw,true);Require(decoded.readable&&decoded.finite&&decoded.plausible&&decoded.raw==bits&&decoded.value==values,"lossless float decode");});
    check("non-finite operation coordinates are invalid",[]{std::array<uint8_t,aoe::DifferentialOperationRecordBytes> raw{};const uint32_t infinity=0x7F800000;memcpy(raw.data(),&infinity,4);const auto decoded=aoe::DecodeOperationSpatialFields(raw,true);Require(!decoded.finite&&!decoded.plausible&&decoded.raw[0]==infinity,"non-finite rejected");});
    check("player and selected target unavailability do not reject an initial capture",[]{Memory memory;const uint16_t word=0x0209;memory.put(0x100000,word);std::array<uint8_t,aoe::DifferentialOperationRecordBytes> raw{};memory.putBytes(0x200000,raw.data(),raw.size());aoe::TargetInspectorEvent registers;registers.r9=0x100000;registers.r8=0x200000;registers.rdx=1;const auto event=aoe::CaptureTargetInspectorEvent(Reader(memory),Layout(),registers);Require(event.initial0209&&event.operationRecordReadable&&!event.spatial.player.positionAvailable&&event.actorProbes.empty(),"capture survives missing actors");});
    check("player and monster position paths use their separately verified layouts",[]{Memory memory;const uint64_t player=0x100000,monster=0x200000,link=0x300000;const uint32_t playerId=7,monsterId=8;const uint8_t playerType=1,monsterType=2;memory.put(player+0x768,playerId);memory.put(player+0x7E1,playerType);memory.put(monster+0x768,monsterId);memory.put(monster+0x7E1,monsterType);std::array<float,4> playerPosition{1,2,3,1};memory.putBytes(player+0xB0,reinterpret_cast<const uint8_t*>(playerPosition.data()),sizeof(playerPosition));memory.put(monster+0x1390,link);memory.put(link+0x1380,monster);std::array<float,3> monsterPosition{10,20,30};memory.putBytes(link+0x70,reinterpret_cast<const uint8_t*>(monsterPosition.data()),sizeof(monsterPosition));const auto p=aoe::CaptureActorSpatial(Reader(memory),Layout(),player,"player","verified");const auto m=aoe::CaptureActorSpatial(Reader(memory),Layout(),monster,"monster","verified");Require(p.positionAvailable&&p.position.value==std::array<float,3>{1,2,3}&&p.position.source.find("0xB0")!=std::string::npos,"player +B0 path");Require(m.positionAvailable&&m.position.value==monsterPosition&&m.position.source.find("accessor-equivalent")!=std::string::npos,"monster linked accessor path");});
    check("initial 0x0209 captures independent selected-target identity",[]{Memory memory;auto layout=Layout();const uint64_t context=0x100000,monster=0x200000,link=0x300000,header=0x400000,node=0x410000,sentinel=0x420000,wordAt=0x500000,record=0x510000;const uint32_t id=123;const uint8_t type=2,zero=0,one=1;const uint16_t word=0x0209;memory.put(context+layout.selectedTargetOffset,monster);memory.put(monster+layout.actorIdOffset,id);memory.put(monster+layout.actorTypeOffset,type);memory.put(monster+layout.actorWorldLinkOffset,link);memory.put(link+layout.actorWorldLinkOwnerOffset,monster);std::array<float,3> xyz{10,20,30};memory.putBytes(link+layout.actorWorldPositionOffset,reinterpret_cast<const uint8_t*>(xyz.data()),sizeof(xyz));memory.put(context+layout.actorTreeOffsets[2],header);memory.put(header+8,node);memory.put(node,sentinel);memory.put(node+0x19,zero);memory.put(node+0x20,id);memory.put(node+0x28,monster);memory.put(sentinel+0x19,one);memory.put(wordAt,word);std::array<uint8_t,aoe::DifferentialOperationRecordBytes> raw{};memory.putBytes(record,raw.data(),raw.size());aoe::TargetInspectorEvent registers;registers.rcx=context;registers.r9=wordAt;registers.r8=record;auto event=aoe::CaptureTargetInspectorEvent(Reader(memory),layout,registers);Require(event.initial0209&&event.spatial.selectedTarget.provenanceValidated,"independent target snapshot validated");Require(event.spatial.selectedTarget.pointer==monster&&event.spatial.selectedTarget.actorId==id&&event.spatial.selectedTarget.category==2,"selected identity at initial time");Require(event.spatial.selectedTarget.positionAvailable&&event.spatial.selectedTarget.position.value==xyz,"selected XYZ at initial time");});
    check("player comparison remains available when selected target is unknown",[]{aoe::TargetInspectorSession session;for(uint64_t id=1;id<=3;++id){aoe::TargetInspectorEvent event;event.markerId=id;event.initial0209=true;event.operationSpatial.readable=event.operationSpatial.finite=event.operationSpatial.plausible=true;event.operationSpatial.value={float(id),2.0f,3.0f};event.spatial.player.positionAvailable=true;event.spatial.player.position.value=event.operationSpatial.value;session.events.push_back(event);}const auto result=aoe::AnalyzeSpatialProvenance(session);Require(result.captures[0].playerAvailable&&!result.captures[0].targetAvailable&&result.captures[0].operationToPlayer3d==0&&result.classification==aoe::SpatialClassification::InsufficientData,"player distance retained without target guess");});
    check("player and proven target produce both distances and ambiguous classification",[]{aoe::TargetInspectorSession session;for(uint64_t id=1;id<=3;++id){aoe::TargetInspectorEvent event;event.markerId=id;event.initial0209=true;event.operationSpatial.readable=event.operationSpatial.finite=event.operationSpatial.plausible=true;event.operationSpatial.value={10.0f,20.0f,30.0f};event.spatial.player.positionAvailable=true;event.spatial.player.position.value=event.operationSpatial.value;aoe::DifferentialActorProbe probe;probe.idOffset=0x24;probe.typeOffset=0x28;probe.actorId=uint32_t(100+id);probe.actorType=probe.category=2;probe.actorPointer=0x500000+id*0x1000;probe.resolved=probe.categoryReadable=true;probe.spatial.positionAvailable=true;probe.spatial.position.value=event.operationSpatial.value;event.actorProbes.push_back(probe);session.events.push_back(event);}const auto result=aoe::AnalyzeSpatialProvenance(session);Require(result.captures[0].playerAvailable&&!result.captures[0].targetAvailable&&result.captures[0].operationToPlayer3d==0,"player distance retained; operation candidate is not selection provenance");Require(result.classification==aoe::SpatialClassification::InsufficientData,"confounded proximity stays insufficient");});
    check("MARK-time and initial-0209 snapshots stay distinct across movement",[]{aoe::TargetInspectorSession session;session.phase=aoe::TargetInspectorPhase::WaitingForAoe;aoe::SpatialSnapshot mark;mark.player.positionAvailable=true;mark.player.position.value={1,2,3};aoe::Marker marker{1,"Capture A",100,10};std::string error;Require(aoe::ArmNextTargetCapture(session,marker,error,&mark),error);aoe::TargetInspectorEvent event;event.initial0209=true;event.sequence=1;event.qpc=200;event.timestampMs=20;event.spatial.player.positionAvailable=true;event.spatial.player.position.value={4,5,6};Require(aoe::RecordDifferentialEvent(session,event),"initial stored");Require(session.markers[0].qpc==100&&session.markerSpatial[0].player.position.value[0]==1&&session.events[0].qpc==200&&session.events[0].spatial.player.position.value[0]==4,"timestamps and movement remain independent");});
    check("A B C retain independent spatial snapshots and single capture never proves provenance",[]{aoe::TargetInspectorSession session;for(uint64_t id=1;id<=3;++id){aoe::TargetInspectorEvent event;event.markerId=id;event.initial0209=true;event.spatial.player.positionAvailable=true;event.spatial.player.position.value={float(id),0,0};session.events.push_back(event);}Require(session.events[0].spatial.player.position.value[0]==1&&session.events[2].spatial.player.position.value[0]==3,"independent snapshots");aoe::TargetInspectorSession one;one.events.push_back(session.events[0]);one.events[0].markerId=1;one.events[0].operationSpatial.plausible=true;one.events[0].operationSpatial.value=one.events[0].spatial.player.position.value;Require(aoe::AnalyzeSpatialProvenance(one).classification==aoe::SpatialClassification::InsufficientData,"one capture cannot prove");});
    check("field comparison highlights a changing A B C scalar",[]{aoe::TargetInspectorSession session;for(uint64_t marker=1;marker<=3;++marker){aoe::TargetInspectorEvent event;event.markerId=marker;event.initial0209=true;event.operationRecordReadable=true;const uint32_t value=uint32_t(100+marker);memcpy(event.operationRecord.data()+4,&value,sizeof(value));session.events.push_back(event);}const auto rows=aoe::CompareOperationFields(session);auto it=std::find_if(rows.begin(),rows.end(),[](const auto& row){return row.offset==4;});Require(it!=rows.end()&&it->changed&&it->allPairwiseDifferent&&it->values[0]==101&&it->values[2]==103,"changed field");});
    check("invalid operation and frame pointers fail safely",[]{Memory memory;aoe::TargetInspectorEvent event;event.r9=1;event.r8=2;event=aoe::CaptureTargetInspectorEvent(Reader(memory),Layout(),event);Require(!event.operationReadable&&!event.operationRecordReadable,"invalid operation pointers");aoe::ParsedInputCapture parsed;parsed.rbp=1;parsed.operationRecordPointer=2;parsed=aoe::CaptureParsedInput(Reader(memory),Layout(),parsed);Require(!parsed.operationReadable&&!parsed.recordReadable,"invalid frame pointers");});
    check("parsed input accepts semantic ID type data without a 0x0209 word",[]{Memory memory;const uint64_t rbp=0x200000,actor=0x300000,game=0x400000,state=actor+0x818;const uint16_t skillTemplate=0x1234;const uint32_t actorId=0x55667788;const uint8_t actorType=2;memory.put(rbp-0x40,skillTemplate);memory.put(rbp-0x30,actorId);memory.put(rbp-0x3C,actorType);memory.put(rbp+0x40,game);memory.put(actor+0x768,actorId);memory.put(actor+0x7E1,actorType);aoe::ParsedInputCapture registers;registers.rbp=rbp;registers.ownerPointer=actor;registers.operationRecordPointer=state;auto parsed=aoe::CaptureParsedInput(Reader(memory),Layout(),registers);Require(parsed.semanticInput&&!parsed.operation0209&&parsed.operationWord==skillTemplate,"semantic boundary retained without opcode filter");Require(parsed.parsedActorId==actorId&&parsed.parsedActorType==actorType&&parsed.gameContext==game,"ID type and game context");Require(parsed.resolvedActorPointer==actor&&parsed.actorStatePointer==state&&parsed.ownerIdentityReadable,"resolved actor register semantics");aoe::TargetInspectorSession session;session.phase=aoe::TargetInspectorPhase::Capturing;session.captureSlots[0].state=aoe::TargetCaptureSlotState::Captured;session.captureSlots[0].markerId=1;Require(aoe::RecordParsedInput(session,parsed)&&session.parsedInputs.size()==1,"non-0209 semantic input recorded");});
    check("resolved A B C operation fields remain candidate only",[]{aoe::TargetInspectorSession session;for(uint64_t marker=1;marker<=3;++marker){aoe::TargetInspectorEvent event;event.markerId=marker;event.initial0209=true;aoe::DifferentialActorProbe probe;probe.idOffset=4;probe.typeOffset=0x28;probe.actorId=uint32_t(100+marker);probe.actorType=2;probe.actorPointer=0x500000+marker*0x1000;probe.resolved=true;probe.categoryReadable=true;probe.category=2;event.actorProbes.push_back(probe);session.events.push_back(event);}const auto candidates=aoe::CompareActorCandidates(session);Require(candidates.size()==1&&!candidates[0].provenForAbc&&candidates[0].allMonsters,"operation actor remains untrusted");});
    check("entity+0x660 exact record decoding and actor lookup",[]{
        Memory memory;const uint64_t context=0x100000,entity=0x200000,vector=entity+0x660,begin=0x300000,recordPointer=0x400000,header=0x500000,node=0x510000,sentinel=0x520000,actor=0x600000;const uint32_t actorId=0x12345678;const uint8_t actorType=2;const std::array<uint8_t,8> raw{0x78,0x56,0x34,0x12,0x02,0xA5,0xB6,0xC7};
        memory.put(vector,begin);memory.put(vector+8,begin+8);memory.put(vector+16,begin+8);memory.put(begin,recordPointer);memory.putBytes(recordPointer,raw.data(),raw.size());memory.put(context+0x1120,header);memory.put(header+8,node);memory.put(node,sentinel);memory.put(node+0x20,actorId);memory.put(node+0x28,actor);const uint8_t zero=0,one=1;memory.put(node+0x19,zero);memory.put(sentinel+0x19,one);memory.put(actor+0x768,actorId);memory.put(actor+0x7E1,actorType);
        const auto capture=aoe::InspectPrimaryTargetVector(Reader(memory),Layout(),context,entity,vector);Require(capture.r12MatchesEntity660&&capture.headerReadable&&capture.structurallyValid&&capture.count==1,"exact vector");Require(capture.records.size()==1&&capture.records[0].recordReadable,"record read");const auto& record=capture.records[0];Require(record.actorId==actorId&&record.actorType==actorType,"decoded identity");Require(record.trailingBytes==std::array<uint8_t,3>{0xA5,0xB6,0xC7},"all eight bytes retained");Require(record.resolution.status==aoe::TargetActorLookupStatus::Resolved&&record.resolution.actorPointer==actor,"actor resolved");Require(record.resolution.idMatches&&record.resolution.typeMatches,"resolved identity verified");
    });
    check("capture is bounded to the proven 32-entry maximum",[]{Memory memory;const uint64_t context=0x100000,entity=0x200000,vector=entity+0x660,begin=0x300000;memory.put(vector,begin);memory.put(vector+8,begin+40*8);memory.put(vector+16,begin+40*8);for(uint64_t i=0;i<40;++i){const uint64_t pointer=0x400000+i*0x20;memory.put(begin+i*8,pointer);std::array<uint8_t,8> raw{};const uint32_t id=uint32_t(i+1);memcpy(raw.data(),&id,4);raw[4]=3;memory.putBytes(pointer,raw.data(),raw.size());}const auto capture=aoe::InspectPrimaryTargetVector(Reader(memory),Layout(),context,entity,vector);Require(capture.structurallyValid&&capture.count==40&&!capture.countWithinLimit&&capture.truncated,"limit violation retained");Require(capture.records.size()==aoe::TargetMaximumEntries,"bounded to 32");});
    check("only RDX+0x660 is accepted; generic R12 scanning is gone",[]{Memory memory;const uint64_t entity=0x200000;const auto capture=aoe::InspectPrimaryTargetVector(Reader(memory),Layout(),0x100000,entity,entity+0x688);Require(!capture.r12MatchesEntity660&&!capture.headerReadable&&capture.records.empty(),"mismatched R12 refused");});
    check("failed actor lookup is safe and explicit",[]{Memory memory;const uint64_t context=0x100000,entity=0x200000,vector=entity+0x660,begin=0x300000,recordPointer=0x400000;memory.put(vector,begin);memory.put(vector+8,begin+8);memory.put(vector+16,begin+8);memory.put(begin,recordPointer);std::array<uint8_t,8> raw{};const uint32_t id=99;memcpy(raw.data(),&id,4);raw[4]=2;memory.putBytes(recordPointer,raw.data(),raw.size());const auto capture=aoe::InspectPrimaryTargetVector(Reader(memory),Layout(),context,entity,vector);Require(capture.records.size()==1,"record retained");Require(capture.records[0].resolution.status==aoe::TargetActorLookupStatus::ReadError&&capture.records[0].resolution.error==299,"lookup failure recorded");});
    check("A through D target-switch captures are grouped and changed fields are shown",[]{aoe::TargetInspectorSession session;for(uint64_t marker=1;marker<=4;++marker){aoe::TargetInspectorEvent event;event.markerId=marker;event.initial0209=true;event.targetVector.count=marker==4?0:1;if(marker<4){aoe::TargetRecord record;record.recordReadable=true;record.actorId=uint32_t(100+marker);record.actorType=2;record.raw[0]=uint8_t(record.actorId);record.raw[4]=2;record.resolution.actorPointer=0x500000+marker*0x1000;event.targetVector.records.push_back(record);}session.events.push_back(event);}const auto comparison=aoe::CompareTargetCaptures(session);Require(comparison.size()==4&&comparison[0].captured&&comparison[3].captured,"A-D grouped");Require(comparison[1].records[0].idChangedFromA&&comparison[1].records[0].actorChangedFromA,"target identity changes");Require(comparison[3].count==0&&comparison[3].countChangedFromA,"no-target count change");});
    check("STOP export contains all completed A B C captures",[&]{aoe::TargetInspectorSession session;session.phase=aoe::TargetInspectorPhase::WaitingForAoe;session.pid=1;session.creationTime=2;session.moduleBase=0x140000000;session.targetSha256=aoe::ApprovedHash;session.runtime=Layout();for(uint64_t id=1;id<=3;++id){Arm(session,id);aoe::TargetInspectorEvent event;event.initial0209=true;event.operationReadable=true;event.operationWord0=0x0209;event.sequence=id;event.targetVector.entityPointer=0x200000+id*0x1000;event.targetVector.expectedAddress=event.targetVector.entityPointer+0x660;event.targetVector.addressFromR12=event.targetVector.expectedAddress;event.targetVector.r12MatchesEntity660=true;event.targetVector.headerReadable=true;event.targetVector.structurallyValid=true;event.targetVector.count=1;aoe::TargetRecord record;record.actorId=uint32_t(76+id);record.actorType=2;record.raw[0]=uint8_t(record.actorId);record.raw[4]=2;record.resolution.status=aoe::TargetActorLookupStatus::Resolved;record.resolution.actorPointer=0x600000+id*0x1000;event.targetVector.records.push_back(record);Require(aoe::RecordDifferentialEvent(session,event),"capture stored");}session.phase=aoe::TargetInspectorPhase::Complete;const auto path=artifacts/L"target-differential-inspector.json";std::string error;Require(aoe::ExportTargetInspectorJson(path,session,error),error);std::ifstream input(path);std::string json((std::istreambuf_iterator<char>(input)),{});for(auto token:{"\"mode\":\"AOE Target Differential Inspector\"","\"readOnly\":true","\"captureSlots\"","\"capture\":\"A\",\"state\":\"CAPTURED\"","\"capture\":\"B\",\"state\":\"CAPTURED\"","\"capture\":\"C\",\"state\":\"CAPTURED\"","\"knownVectorOffset\":\"0x660\"","\"entity660\"","\"raw8\"","\"fieldComparison\"","\"spatialCaptures\"","\"operationSpatialCandidate\"","\"candidateField24\"","candidate only","\"spatialConclusion\""})Require(json.find(token)!=std::string::npos,token);Require(std::count(json.begin(),json.end(),'\n')>5,"structured export");});
    check("process restart invalidation clears runtime identity, slots, and all A B C streams",[]{aoe::TargetInspectorSession session;session.phase=aoe::TargetInspectorPhase::Capturing;session.pid=1;session.moduleBase=2;session.captureSlots[0].state=aoe::TargetCaptureSlotState::Captured;session.captureSlots[0].markerId=1;session.markers.push_back({});session.events.push_back({});session.periodicEvents.push_back({});session.parsedInputs.push_back({});aoe::InvalidateTargetInspector(session,"restart");Require(session.phase==aoe::TargetInspectorPhase::Error&&session.pid==0&&session.moduleBase==0&&session.captureSlots[0].state==aoe::TargetCaptureSlotState::Empty&&session.markers.empty()&&session.events.empty()&&session.periodicEvents.empty()&&session.parsedInputs.empty()&&session.error=="restart","invalidated");});
    check("Target Differential Inspector implementation contains no write or RIP redirect primitive",[]{std::ifstream input(std::filesystem::path(LR"(C:\Users\Public\Documents\4UnityAOEManager\src\target_inspector.cpp)"));std::string source((std::istreambuf_iterator<char>(input)),{});Require(source.find("WriteProcessMemory")==std::string::npos&&source.find("SetThreadContext")==std::string::npos&&source.find("context.Rip=")==std::string::npos,"read-only source");});
    check("in-session inspector breakpoint transition has no gameplay write or RIP redirect",[]{std::ifstream input(std::filesystem::path(LR"(C:\Users\Public\Documents\4UnityAOEManager\src\tracer.cpp)"));std::string source((std::istreambuf_iterator<char>(input)),{});const auto begin=source.find("auto processInspectorRequest=");const auto end=source.find("auto closeEventFiles=",begin);Require(begin!=std::string::npos&&end!=std::string::npos&&end>begin,"transition block found");const auto block=source.substr(begin,end-begin);Require(block.find("WriteProcessMemory")==std::string::npos&&block.find("VirtualProtectEx")==std::string::npos&&block.find("context.Rip=")==std::string::npos,"transition remains read only");});
    return passed;
}





