#include "tick_patch.hpp"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <functional>
#include <iostream>
#include <iterator>
#include <memory>
#include <stdexcept>
#include <unordered_map>

namespace {
void Require(bool condition,const std::string& message){if(!condition)throw std::runtime_error(message);}
aoe::TargetInfo Target(){aoe::TargetInfo target;target.mode=aoe::TraceMode::Tick100;target.pid=321;target.creationTime=654;target.base=0x140000000;target.size=0x1000000;target.traceRva=aoe::ProducerRva;target.traceAddress=target.base+target.traceRva;target.verified=true;target.image.sha256=aoe::ApprovedHash;return target;}
aoe::TickPatchExperimentState Experiment(const aoe::TargetInfo& target,bool observation=true){return aoe::CreateTickPatchExperimentState(target,observation);}
struct Memory {
    std::unordered_map<uint64_t,uint8_t> bytes;
    unsigned writes=0,failWrite=0,reads=0,mismatchRead=0;
    void Put(uint64_t address,std::initializer_list<uint8_t> value){for(auto byte:value)bytes[address++]=byte;}
    std::vector<uint8_t> Get(uint64_t address,size_t size)const{std::vector<uint8_t> out;for(size_t i=0;i<size;++i){auto it=bytes.find(address+i);out.push_back(it==bytes.end()?0:it->second);}return out;}
    aoe::TickPatchIo Io(){return {
        [](uint64_t,size_t,std::string& error){error.clear();return true;},
        [this](uint64_t address,void* out,size_t size,std::string& error){++reads;auto* p=static_cast<uint8_t*>(out);for(size_t i=0;i<size;++i){auto it=bytes.find(address+i);if(it==bytes.end()){error="missing byte";return false;}p[i]=it->second;}if(mismatchRead&&reads==mismatchRead&&size)p[0]^=0x01;error.clear();return true;},
        [this](uint64_t address,const void* in,size_t size,std::string& error){++writes;if(failWrite&&writes==failWrite){error="injected write failure";return false;}auto* p=static_cast<const uint8_t*>(in);for(size_t i=0;i<size;++i)bytes[address+i]=p[i];error.clear();return true;}
    };}
};
Memory Original(const aoe::TargetInfo& target){Memory memory;memory.Put(target.base+aoe::TickThresholdRva,{0x81,0xF9,0xE8,0x03,0x00,0x00});memory.Put(target.base+aoe::TickSubtractRva,{0x41,0x81,0x85,0x90,0x00,0x00,0x00,0x18,0xFC,0xFF,0xFF});memory.Put(target.base+aoe::TickRepeatRva,{0x41,0x81,0xBD,0x90,0x00,0x00,0x00,0xE8,0x03,0x00,0x00});return memory;}
}

unsigned TickPatchTests(const std::filesystem::path& artifacts){unsigned passed=0;auto check=[&](const char* name,const std::function<void()>& test){test();++passed;std::cout<<"[PASS] "<<name<<'\n';};
    check("ARM creates persistent TickPatchExperimentState without Capture",[]{auto target=Target();auto state=Experiment(target);std::shared_ptr<aoe::Capture> capture;Require(state.armed&&state.pid==target.pid&&state.creationTime==target.creationTime&&state.moduleBase==target.base&&!state.armTimestamp.empty(),"independent armed state");Require(!capture,"normal capture is absent");});
    check("tick interval converts both 1000 immediates to 100 with 3/3 readback",[]{auto target=Target();auto memory=Original(target);auto state=Experiment(target);std::string error;Require(aoe::ApplyTick100Patch(memory.Io(),target,state,error),error);Require(state.patchApplied&&state.active&&state.validationPassed&&state.targets.size()==3,"active only after three targets");Require(std::all_of(state.targets.begin(),state.targets.end(),[](const auto& item){return item.patchReadbackVerified;}),"3/3 readback");Require(memory.Get(target.base+aoe::TickThresholdRva,6)==std::vector<uint8_t>({0x81,0xF9,0x64,0,0,0}),"threshold 100");Require(memory.Get(target.base+aoe::TickRepeatRva,11)==std::vector<uint8_t>({0x41,0x81,0xBD,0x90,0,0,0,0x64,0,0,0}),"repeat 100");});
    check("tick subtraction converts -1000 to -100",[]{auto target=Target();auto memory=Original(target);auto state=Experiment(target);std::string error;Require(aoe::ApplyTick100Patch(memory.Io(),target,state,error),error);Require(memory.Get(target.base+aoe::TickSubtractRva,11)==std::vector<uint8_t>({0x41,0x81,0x85,0x90,0,0,0,0x9C,0xFF,0xFF,0xFF}),"subtract -100");});
    check("all three validated scheduler patches are required",[]{auto target=Target();auto memory=Original(target);memory.bytes[target.base+aoe::TickRepeatRva]=0x90;auto state=Experiment(target);std::string error;Require(!aoe::ApplyTick100Patch(memory.Io(),target,state,error)&&memory.writes==0&&!state.patchApplied&&!state.active,"third validation blocks transaction");Require(state.targets.size()==3&&!state.targets[2].validationPassed,"failed target retained diagnostically");});
    check("byte validation failure causes zero writes",[]{auto target=Target();auto memory=Original(target);memory.bytes[target.base+aoe::TickThresholdRva+2]=0xE9;auto state=Experiment(target);std::string error;Require(!aoe::ApplyTick100Patch(memory.Io(),target,state,error)&&memory.writes==0,"zero writes");});
    check("second patch failure restores every original instruction",[]{auto target=Target();auto original=Original(target);auto memory=original;memory.failWrite=2;auto state=Experiment(target);std::string error;Require(!aoe::ApplyTick100Patch(memory.Io(),target,state,error),"failure expected");for(auto rva:{aoe::TickThresholdRva,aoe::TickSubtractRva,aoe::TickRepeatRva})Require(memory.Get(target.base+rva,rva==aoe::TickThresholdRva?6:11)==original.Get(target.base+rva,rva==aoe::TickThresholdRva?6:11),"all original bytes restored");Require(!state.active&&!state.patchApplied,"never active");});
    check("one patched readback mismatch rejects ACTIVE and restores originals",[]{auto target=Target();auto original=Original(target);auto memory=original;memory.mismatchRead=5;auto state=Experiment(target);std::string error;Require(!aoe::ApplyTick100Patch(memory.Io(),target,state,error),"readback mismatch expected");Require(!state.patchApplied&&!state.active&&state.patchRestored,"mismatch rejected and rolled back");Require(state.targets.size()==3&&!state.targets[1].patchReadbackVerified,"exact failing target recorded");for(auto rva:{aoe::TickThresholdRva,aoe::TickSubtractRva,aoe::TickRepeatRva})Require(memory.Get(target.base+rva,rva==aoe::TickThresholdRva?6:11)==original.Get(target.base+rva,rva==aoe::TickThresholdRva?6:11),"rollback exact");Require(aoe::TickExperimentDetails(state).find("PATCH FAILED")!=std::string::npos,"GUI does not show ACTIVE");});
    check("exact patched bytes persist after verified apply",[]{auto target=Target();auto memory=Original(target);auto state=Experiment(target);std::string error;Require(aoe::ApplyTick100Patch(memory.Io(),target,state,error),error);for(const auto& item:state.targets){Require(item.actualPatchedReadback==item.intendedPatchedBytes&&item.patchReadbackVerified,"stored process readback");Require(memory.Get(item.resolvedAddress,item.intendedPatchedBytes.size())==item.intendedPatchedBytes,"patched process bytes persist");}});
    check("restore requires 3/3 exact original-byte readback",[]{auto target=Target();auto original=Original(target);auto memory=original;auto state=Experiment(target);std::string error;Require(aoe::ApplyTick100Patch(memory.Io(),target,state,error),error);Require(aoe::RestoreTick100Patch(memory.Io(),target,state,error),error);Require(state.patchApplied&&state.patchRestored&&!state.active&&state.explicitRestoreAttempted,"restored state");Require(std::all_of(state.targets.begin(),state.targets.end(),[](const auto& item){return item.restoreReadbackVerified&&item.actualRestoredReadback==item.originalBytes;}),"3/3 restore readback");Require(aoe::TickExperimentDetails(state).find("RESTORED - VERIFIED")!=std::string::npos,"verified restore GUI");});
    check("one restore readback mismatch rejects RESTORED verified state",[]{auto target=Target();auto memory=Original(target);auto state=Experiment(target);std::string error;Require(aoe::ApplyTick100Patch(memory.Io(),target,state,error),error);memory.mismatchRead=8;Require(!aoe::RestoreTick100Patch(memory.Io(),target,state,error),"restore mismatch expected");Require(!state.patchRestored&&state.restoreRequired&&state.explicitRestoreAttempted,"restore verification required");Require(aoe::TickExperimentDetails(state).find("RESTORE VERIFICATION FAILED")!=std::string::npos,"failure displayed");});
    check("producer counters classify 0209 020A and other",[]{auto target=Target();auto state=Experiment(target);state.active=true;state.armQpc=1000;state.frequency=1000;aoe::RecordTickProducer(state,true,0x0209,1050);aoe::RecordTickProducer(state,true,0x020A,1100);aoe::RecordTickProducer(state,true,0x0246,1150);aoe::RecordTickProducer(state,false,0,1200);Require(state.producer0209Count==1&&state.producer020ACount==1&&state.producerOtherCount==2,"producer classes");});
    check("producer 020A timestamps calculate inter-event deltas",[]{auto target=Target();auto state=Experiment(target);state.active=true;state.armQpc=1000;state.frequency=1000;aoe::RecordTickProducer(state,true,0x020A,1100);aoe::RecordTickProducer(state,true,0x020A,1205);aoe::RecordTickProducer(state,true,0x020A,1310);Require(state.producer020ATimestampsMs.size()==3&&state.producer020ADeltasMs.size()==2,"series sizes");Require(std::abs(state.producer020ATimestampsMs[1]-205.0)<1e-9&&std::abs(state.producer020ADeltasMs[0]-105.0)<1e-9,"relative timestamp and delta");});
    check("experiment survives zero producer events",[]{auto target=Target();auto memory=Original(target);auto state=Experiment(target);std::string error;Require(aoe::ApplyTick100Patch(memory.Io(),target,state,error),error);Require(state.armed&&state.active&&state.producer0209Count==0&&state.producer020ACount==0&&state.producerOtherCount==0,"zero-event state remains exportable");});
    check("standalone tick JSON exports without Capture state",[&]{auto target=Target();auto memory=Original(target);auto state=Experiment(target);std::shared_ptr<aoe::Capture> capture;std::string error;Require(aoe::ApplyTick100Patch(memory.Io(),target,state,error),error);aoe::RecordTickProducer(state,true,0x020A,state.armQpc+state.frequency/10);Require(aoe::RestoreTick100Patch(memory.Io(),target,state,error),error);auto path=artifacts/L"tick_patch_standalone.json";Require(aoe::ExportTickExperimentJson(path,state,error),error);Require(!capture,"no capture object");std::ifstream input(path);std::string json((std::istreambuf_iterator<char>(input)),{});for(auto token:{"\"mode\":\"AOE Tick 100ms\"","\"patchApplied\":true","\"patchRestored\":true","\"validationPassed\":true","\"actualPatchedReadback\"","\"patchReadbackVerified\":true","\"actualRestoredReadback\"","\"restoreReadbackVerified\":true","\"producer020ACount\":1","\"experimentDurationMs\"",aoe::TickPatchLimitation})Require(json.find(token)!=std::string::npos,token);Require(json.find("\"restoreTimestamp\":\"\"")==std::string::npos,"restore timestamp populated");});
    check("tick transaction never modifies record plus 34",[]{auto target=Target();auto memory=Original(target);const uint64_t record=0x300000;const uint32_t budget=7900;for(size_t i=0;i<4;++i)memory.bytes[record+0x34+i]=uint8_t(budget>>(8*i));auto before=memory.Get(record+0x34,4);auto state=Experiment(target);std::string error;Require(aoe::ApplyTick100Patch(memory.Io(),target,state,error),error);Require(memory.Get(record+0x34,4)==before,"record budget unchanged after apply");Require(aoe::RestoreTick100Patch(memory.Io(),target,state,error),error);Require(memory.Get(record+0x34,4)==before,"record budget unchanged after restore");});
    check("process restart invalidates persistent state safely",[]{auto target=Target();auto memory=Original(target);auto state=Experiment(target);std::string error;Require(aoe::ApplyTick100Patch(memory.Io(),target,state,error),error);++target.creationTime;Require(!aoe::RestoreTick100Patch(memory.Io(),target,state,error),"session mismatch");Require(!state.armed&&!state.active&&state.targets.empty()&&state.moduleBase==0,"saved addresses invalidated");});
    check("GUI status requires verified patch and restore readbacks",[]{aoe::TickPatchExperimentState state;Require(aoe::TickExperimentDetails(state).find("NOT ARMED")!=std::string::npos,"not armed");state.armed=state.active=state.patchApplied=true;state.targets.resize(3);for(auto& target:state.targets)target.patchReadbackVerified=true;auto active=aoe::TickExperimentDetails(state);Require(active.find("AOE TICK TEST ACTIVE")!=std::string::npos&&active.find("PATCH READBACK: VERIFIED 3/3")!=std::string::npos,"active verified");state.active=false;state.explicitRestoreAttempted=state.patchRestored=true;for(auto& target:state.targets)target.restoreReadbackVerified=true;Require(aoe::TickExperimentDetails(state).find("RESTORED - VERIFIED")!=std::string::npos,"restore verified");});
    return passed;
}
