#include "visual_suppression.hpp"
#include <functional>
#include <iostream>
#include <stdexcept>

namespace {
void Require(bool condition,const std::string& message){if(!condition)throw std::runtime_error(message);}
aoe::TargetInfo Target(){aoe::TargetInfo t;t.pid=41;t.creationTime=82;t.base=0x140000000;t.verified=true;t.image.sha256="VISUAL-SHA";auto&r=t.runtime;r.visualSuppressionAvailable=true;r.visualReaderRva=0x100;r.visualLookupRva=0x500;r.visualFieldOffset=0x8C;r.visualBaseRegister=aoe::X64RegisterId::Rdx;r.visualReaderBytes={0x8B};return t;}
aoe::VisualRuntimeState Resolved(){aoe::VisualRuntimeState s;aoe::InitializeVisualRuntime(s,Target());s.captureBreakpointActive=true;std::string error;Require(aoe::ObserveVisualReader(s,77,0x100000,328,error),error);aoe::ObserveVisualPreparation(s,77);Require(aoe::ConfirmVisualAoeCall(s,77,true,0x0209),"correlated visual capture");return s;}
aoe::VisualSessionIdentity Identity(uint64_t generation=3){auto t=Target();return{t.pid,t.creationTime,t.base,generation,t.image.sha256};}
}

unsigned VisualSuppressionTests(const std::filesystem::path&){unsigned passed=0;auto check=[&](const char* name,const std::function<void()>& body){body();++passed;std::cout<<"[PASS] "<<name<<'\n';};
    check("visual reader candidate requires same-thread prep and established AOE operation",[]{auto s=Resolved();Require(s.resolved&&s.tSkill==0x100000&&s.visualField==0x10008C&&s.originalValue==328,"resolved session fields");});
    check("periodic 020A resolves an already active AOE visual",[]{aoe::VisualRuntimeState s;aoe::InitializeVisualRuntime(s,Target());s.captureBreakpointActive=true;std::string error;Require(aoe::ObserveVisualReader(s,77,0x200000,328,error),error);aoe::ObserveVisualPreparation(s,77);Require(aoe::ConfirmVisualAoeCall(s,77,true,0x020A)&&s.resolved&&s.tSkill==0x200000,"correlated periodic AOE capture");});
    check("unrelated skill does not resolve TSkill",[]{aoe::VisualRuntimeState s;aoe::InitializeVisualRuntime(s,Target());s.captureBreakpointActive=true;std::string error;Require(aoe::ObserveVisualReader(s,77,0x200000,314,error),error);aoe::ObserveVisualPreparation(s,77);Require(!aoe::ConfirmVisualAoeCall(s,77,true,0x0210)&&!s.resolved,"non-AOE operation rejected");});
    check("session identity change invalidates cached TSkill",[]{aoe::VisualSessionCache c;std::string error;Require(aoe::BindVisualSessionCache(c,Resolved(),Identity(),error),error);auto changed=Identity(4);unsigned writes=0;aoe::VisualMemoryIo io;io.read=[](uint64_t,uint32_t&v,std::string&){v=328;return true;};io.write=[&](uint64_t,uint32_t,std::string&){++writes;return true;};Require(!aoe::SetVisualHidden(c,changed,true,io,error)&&writes==0&&error.find("SESSION CHANGED")!=std::string::npos,"stale write blocked");});
    check("hide writes one uint32 zero and captures no constant original",[]{aoe::VisualSessionCache c;std::string error;Require(aoe::BindVisualSessionCache(c,Resolved(),Identity(),error),error);uint32_t memory=328,written=99;size_t writeSize=0;aoe::VisualMemoryIo io;io.read=[&](uint64_t,uint32_t&v,std::string&){v=memory;return true;};io.write=[&](uint64_t,uint32_t v,std::string&){written=v;writeSize=sizeof(v);memory=v;return true;};Require(aoe::SetVisualHidden(c,Identity(),true,io,error),error);Require(c.hidden&&written==0&&writeSize==4&&c.originalValue==328,"four-byte zero write");});
    check("restore uses dynamically captured original value",[]{aoe::VisualSessionCache c;std::string error;Require(aoe::BindVisualSessionCache(c,Resolved(),Identity(),error),error);uint32_t memory=328;aoe::VisualMemoryIo io;io.read=[&](uint64_t,uint32_t&v,std::string&){v=memory;return true;};io.write=[&](uint64_t,uint32_t v,std::string&){memory=v;return true;};Require(aoe::SetVisualHidden(c,Identity(),true,io,error)&&memory==0,error);Require(aoe::SetVisualHidden(c,Identity(),false,io,error)&&memory==328&&!c.hidden,error);});
    check("restore accepts original already exposed for downstream damage",[]{aoe::VisualSessionCache c;std::string error;Require(aoe::BindVisualSessionCache(c,Resolved(),Identity(),error),error);uint32_t memory=328,writes=0;aoe::VisualMemoryIo io;io.read=[&](uint64_t,uint32_t&v,std::string&){v=memory;return true;};io.write=[&](uint64_t,uint32_t v,std::string&){++writes;memory=v;return true;};c.hidden=true;Require(aoe::SetVisualHidden(c,Identity(),false,io,error)&&!c.hidden&&writes==0,"already restored original accepted without another write");});
    check("restore refuses field changed by another owner",[]{aoe::VisualSessionCache c;std::string error;Require(aoe::BindVisualSessionCache(c,Resolved(),Identity(),error),error);uint32_t memory=328;unsigned writes=0;aoe::VisualMemoryIo io;io.read=[&](uint64_t,uint32_t&v,std::string&){v=memory;return true;};io.write=[&](uint64_t,uint32_t v,std::string&){++writes;memory=v;return true;};Require(aoe::SetVisualHidden(c,Identity(),true,io,error),error);memory=777;Require(!aoe::SetVisualHidden(c,Identity(),false,io,error)&&writes==1&&memory==777,"blind restore blocked");});
    check("zero original is rejected before ownership",[]{aoe::VisualRuntimeState s;aoe::InitializeVisualRuntime(s,Target());s.captureBreakpointActive=true;std::string error;Require(!aoe::ObserveVisualReader(s,77,0x100000,0,error)&&!s.resolved,"zero cannot become original");});
    return passed;
}
