#include "analysis.hpp"
#include "budget_write.hpp"
#include <array>
#include <cstring>
#include <fstream>
#include <functional>
#include <iostream>
#include <iterator>
#include <stdexcept>

namespace {
void Require(bool condition,const std::string& message){if(!condition)throw std::runtime_error(message);}
template<class T> void Put(void* base,size_t offset,T value){memcpy(static_cast<unsigned char*>(base)+offset,&value,sizeof(value));}
aoe::TargetInfo Target(uint64_t base=0x140000000){aoe::TargetInfo t;t.mode=aoe::TraceMode::BudgetWrite;t.pid=123;t.creationTime=456;t.base=base;t.size=0x1000000;t.traceRva=aoe::BudgetWriteRva;t.traceAddress=base+aoe::BudgetWriteRva;t.verified=true;t.image.sha256=aoe::ApprovedHash;return t;}
aoe::BudgetProbe Matching(){aoe::BudgetProbe p;p.recordPointer=0x100000;p.linkedPointer=0x200000;p.recordPlausible=p.recordReadable=p.linkedPointerReadable=p.linkedWordReadable=p.record64Readable=p.record98Readable=p.record34Readable=true;p.linkedWord0=0x020A;p.record64=0x0246;p.record98=0;p.old34=7901;return p;}
}

unsigned BudgetWriteTests(const std::filesystem::path& artifacts){unsigned passed=0;auto check=[&](const char* name,const std::function<void()>& test){test();++passed;std::cout<<"[PASS] "<<name<<'\n';};
    check("budget mode resolves dynamic base plus 0x854049 RVA",[]{uint64_t a=0,b=0;Require(aoe::TraceRva(aoe::TraceMode::BudgetWrite)==0x854049,"RVA");Require(aoe::ResolveTraceAddress(0x140000000,0x1000000,aoe::BudgetWriteRva,a),"base one");Require(aoe::ResolveTraceAddress(0x7FF600000000,0x1000000,aoe::BudgetWriteRva,b),"base two");Require(a==0x140854049&&b==0x7FF600854049&&a!=b,"dynamic addresses");Require(!aoe::ResolveTraceAddress(0x140000000,0x1000,aoe::BudgetWriteRva,a),"outside image rejected");});
    check("budget strict linkedWord0 filter",[]{auto p=Matching();Require(aoe::IsBudgetWriteMatch(p),"baseline");p.linkedWord0=0x0209;Require(!aoe::IsBudgetWriteMatch(p),"exact 020A");p.linkedWordReadable=false;Require(!aoe::IsBudgetWriteMatch(p),"read required");});
    check("budget strict record64 filter",[]{auto p=Matching();p.record64=0x0245;Require(!aoe::IsBudgetWriteMatch(p),"exact 0246");});
    check("budget strict record98 filter",[]{auto p=Matching();p.record98=1;Require(!aoe::IsBudgetWriteMatch(p),"zero only");});
    check("budget strict old34 threshold and floor division",[]{auto p=Matching();aoe::BudgetExperiment e;e.armed=e.active=true;aoe::BudgetWritePlan plan;auto t=Target();p.old34=2000;Require(!aoe::ClaimBudgetWrite(e,p,t,1,plan),"> 2000 required");p.old34=2001;Require(aoe::ClaimBudgetWrite(e,p,t,2,plan)&&plan.new34==1000,"floor odd value");});
    check("budget arm permits exactly one write claim",[]{auto p=Matching();auto t=Target();aoe::BudgetExperiment e;std::string error;Require(aoe::ArmBudgetExperiment(e,t,t,error),"arm");aoe::BudgetWritePlan first,second;Require(aoe::ClaimBudgetWrite(e,p,t,10,first),"first claim");Require(!aoe::ClaimBudgetWrite(e,p,t,11,second)&&e.writeClaimed&&!e.active,"second claim blocked");Require(first.address==p.recordPointer+0x34&&first.new34==p.old34/2,"only +34 plan");});
    check("budget success records breakpoint removal",[]{auto p=Matching();auto t=Target();aoe::BudgetExperiment e;e.armed=e.active=true;aoe::BudgetWritePlan plan;Require(aoe::ClaimBudgetWrite(e,p,t,12.5,plan),"claim");aoe::FinishBudgetWrite(e,plan,true);Require(e.writePerformed&&e.completed&&!e.breakpointRemoved,"write completion");aoe::MarkBudgetBreakpointRemoved(e);Require(e.breakpointRemoved,"breakpoint removed after success");});
    check("failed pointer read produces zero write claims",[]{auto probe=aoe::ProbeBudgetWrite(GetCurrentProcess(),1);Require(!probe.recordReadable&&!aoe::IsBudgetWriteMatch(probe),"invalid pointer");aoe::BudgetExperiment e;e.armed=e.active=true;aoe::BudgetWritePlan plan;Require(!aoe::ClaimBudgetWrite(e,probe,Target(),1,plan)&&!e.writeClaimed&&!e.writePerformed,"zero writes");});
    check("budget probe reads exact matching layout",[]{std::array<unsigned char,0xA0> record{};std::array<unsigned char,8> linked{};auto linkedPointer=reinterpret_cast<uint64_t>(linked.data());Put(record.data(),0x80,linkedPointer);Put(record.data(),0x64,uint32_t(0x0246));Put(record.data(),0x98,uint8_t(0));Put(record.data(),0x34,uint32_t(7900));Put(linked.data(),0,uint16_t(0x020A));auto p=aoe::ProbeBudgetWrite(GetCurrentProcess(),reinterpret_cast<uint64_t>(record.data()));Require(aoe::IsBudgetWriteMatch(p)&&p.old34==7900,"safe reads");});
    check("process session change invalidates arm",[]{auto attached=Target(),capture=attached;aoe::BudgetExperiment e;std::string error;++capture.creationTime;Require(!aoe::ArmBudgetExperiment(e,attached,capture,error)&&!e.active&&!error.empty(),"creation change");capture=attached;capture.base+=0x10000;capture.traceAddress=capture.base+aoe::BudgetWriteRva;Require(!aoe::ArmBudgetExperiment(e,attached,capture,error),"base change");});
    check("budget JSON serializes successful write",[&]{aoe::Capture c;c.id=1;c.synthetic=true;c.complete=true;c.frequency=1000000;c.startQpc=1;c.endQpc=12000001;c.requestedSeconds=12;c.durationMs=12000;c.target=Target();auto p=Matching();c.experiment.armed=c.experiment.active=true;aoe::BudgetWritePlan plan;Require(aoe::ClaimBudgetWrite(c.experiment,p,c.target,2250.5,plan),"claim");aoe::FinishBudgetWrite(c.experiment,plan,true);aoe::MarkBudgetBreakpointRemoved(c.experiment);auto a=aoe::Analyze(c);std::string error;auto path=artifacts/L"budget_write_success.json";Require(aoe::ExportJson(path,c,a,error),error);std::ifstream in(path);std::string json((std::istreambuf_iterator<char>(in)),{});for(auto token:{"\"mode\":\"AOE Budget Write 854049\"","\"armed\":true","\"writePerformed\":true","\"old34\":{\"decimal\":7901","\"new34\":{\"decimal\":3950","\"breakpointRva\":\"0x854049\"","\"breakpointRemoved\":true",aoe::BudgetWriteLimitation})Require(json.find(token)!=std::string::npos,token);});
    check("budget JSON serializes compact no-match result",[&]{aoe::Capture c;c.id=2;c.synthetic=true;c.complete=true;c.frequency=1000000;c.startQpc=1;c.endQpc=12000001;c.requestedSeconds=12;c.durationMs=12000;c.target=Target();c.experiment.armed=true;c.experiment.totalBreakpointHits=17;c.experiment.readableRecords=12;c.experiment.linked020AMatches=3;c.experiment.linked020AAnd0246Matches=2;auto a=aoe::Analyze(c);std::string error;auto path=artifacts/L"budget_write_no_match.json";Require(aoe::ExportJson(path,c,a,error),error);std::ifstream in(path);std::string json((std::istreambuf_iterator<char>(in)),{});for(auto token:{"\"writePerformed\":false","\"totalBreakpointHits\":17","\"readableRecords\":12","\"linked020AMatches\":3","\"linked020AAnd0246Matches\":2"})Require(json.find(token)!=std::string::npos,token);Require(json.find("\"recordPointer\"")==std::string::npos,"success fields omitted");});
    return passed;
}
