#include "initial_nx_lifecycle.hpp"
#include "live_validation.hpp"
#include "manager_state.hpp"
#include <filesystem>
#include <fstream>
#include <functional>
#include <iostream>
#include <iterator>
#include <stdexcept>

namespace {
void Require(bool value,const std::string& message){if(!value)throw std::runtime_error(message);}
aoe::TargetInfo Target(){aoe::TargetInfo target;target.pid=41;target.creationTime=82;target.base=0x140000000;target.verified=true;target.image.sha256="SESSION";target.runtime.initialNxAvailable=true;target.runtime.initialPrepRva=0x1000;return target;}
aoe::Initial2xExperiment Armed(uint32_t target){return aoe::CreateInitial2xExperiment(Target(),true,target);}
aoe::Initial2xExperiment Completed(uint32_t target){auto experiment=Armed(target);experiment.initialCallsObserved=target;experiment.redirectsPerformed=target-1;experiment.redirectCount=target-1;experiment.completed=true;experiment.phase=aoe::Initial2xPhase::Completed;return experiment;}
}

unsigned InitialNxLifecycleTests(const std::filesystem::path& artifacts){unsigned passed=0;auto check=[&](const char* name,const std::function<void()>& test){test();++passed;std::cout<<"[PASS] "<<name<<'\n';};
    check("completed 2x reconfigures a fresh Auto Arm 10x experiment",[]{aoe::InitialNxLifecycleState state;auto current=Completed(2);auto action=aoe::ConfigureNextInitialNx(state,current,10);Require(action==aoe::InitialNxConfigurationAction::ResetTerminalExperiment,"terminal reset planned");Require(state.hasLastExperiment&&state.lastExperiment.completed&&state.lastExperiment.targetInitialCalls==2,"completed 2x retained");current={};Require(aoe::PendingInitialNxAction(state,current)==aoe::InitialNxConfigurationAction::PrepareReady,"fresh state preparation");aoe::MarkInitialNxConfigurationApplied(state);aoe::LiveValidationState validation;validation.replayCriticalValidationPassed=true;Require(aoe::ShouldAutoArmAfterValidation(validation,true,false,true),"Auto Arm eligible after preserved validation");auto next=Armed(state.configuredInitialCalls);Require(next.armed&&next.targetInitialCalls==10&&!next.completed&&!next.aborted&&next.initialCallsObserved==0&&next.redirectsPerformed==0,"fresh armed 10x");});
    check("Auto Arm off prepares new target without arming",[]{aoe::InitialNxLifecycleState state;auto current=Completed(2);aoe::ConfigureNextInitialNx(state,current,5);current={};Require(aoe::PendingInitialNxAction(state,current)==aoe::InitialNxConfigurationAction::PrepareReady,"ready action");aoe::MarkInitialNxConfigurationApplied(state);Require(state.configuredInitialCalls==5&&!current.armed,"ready and disarmed");});
    check("continuous ON queues the same N after every successful cast",[]{auto completed=Completed(50);Require(aoe::ShouldQueueContinuousInitialNx(completed,true,false,false),"successful 50x queues re-arm");Require(!aoe::ShouldQueueContinuousInitialNx(completed,false,false,false),"OFF remains one shot");Require(!aoe::ShouldQueueContinuousInitialNx(completed,true,true,false),"research mode suppresses re-arm");Require(!aoe::ShouldQueueContinuousInitialNx(completed,true,false,true),"existing configuration is not duplicated");auto aborted=completed;aborted.completed=false;aborted.aborted=true;Require(!aoe::ShouldQueueContinuousInitialNx(aborted,true,false,false),"abort fails closed without a retry loop");});
    check("armed unstarted 2x can be replaced safely with armed 5x",[]{aoe::InitialNxLifecycleState state;auto current=Armed(2);Require(current.initialCallsObserved==0,"not started");Require(aoe::ConfigureNextInitialNx(state,current,5)==aoe::InitialNxConfigurationAction::ReplaceArmedPending,"pending arm replacement");current={};aoe::MarkInitialNxConfigurationApplied(state);current=Armed(state.configuredInitialCalls);Require(current.armed&&current.targetInitialCalls==5&&current.initialCallsObserved==0,"fresh armed 5x");});
    check("active 10x remains frozen while 20x queues for next cast",[]{aoe::InitialNxLifecycleState state;auto current=Armed(10);current.initialCallsObserved=3;current.replayInProgress=true;Require(aoe::InitialNxReplayActive(current),"active replay recognized");Require(aoe::ConfigureNextInitialNx(state,current,20)==aoe::InitialNxConfigurationAction::QueueAfterActiveReplay,"next target queued");Require(current.targetInitialCalls==10&&state.pendingNextInitialCalls==20,"active target unchanged");current=Completed(10);Require(aoe::PendingInitialNxAction(state,current)==aoe::InitialNxConfigurationAction::ResetTerminalExperiment,"queued target advances after completion");Require(state.lastExperiment.targetInitialCalls==10&&state.configuredInitialCalls==20,"last and next separated");});
    check("configuration changes preserve live and profile validation",[]{aoe::InitialNxLifecycleState state;aoe::LiveValidationState validation;validation.pid=41;validation.creationTime=82;validation.targetSha256="SESSION";validation.profileIdentity="PROFILE";validation.profileFingerprintsPassed=true;validation.replayCriticalValidationPassed=true;validation.validationCastComplete=true;aoe::ManagerSession session;session.active=true;session.profileValid=true;session.pid=41;session.creationTime=82;const auto before=validation;auto current=Completed(2);aoe::ConfigureNextInitialNx(state,current,10);Require(validation.pid==before.pid&&validation.profileFingerprintsPassed&&validation.replayCriticalValidationPassed,"session validation untouched");Require(session.active&&session.profileValid&&session.pid==41&&session.creationTime==82,"profile validation untouched");});
    check("new process session clears lifecycle results but preserves configuration",[]{aoe::InitialNxLifecycleState state;state.configuredInitialCalls=10;state.pendingNextInitialCalls=20;state.configurationPending=true;state.hasLastExperiment=true;state.lastExperiment=Completed(2);aoe::ResetInitialNxLifecycleForNewSession(state);Require(state.configuredInitialCalls==10&&!state.configurationPending&&!state.hasLastExperiment&&state.pendingNextInitialCalls==0,"session result cleared and preference retained");});
    check("completed and aborted state cannot leak into a fresh experiment",[]{aoe::InitialNxLifecycleState state;auto aborted=Armed(3);aborted.aborted=true;aborted.phase=aoe::Initial2xPhase::Aborted;aborted.initialCallsObserved=1;aborted.redirectsPerformed=1;Require(aoe::ConfigureNextInitialNx(state,aborted,7)==aoe::InitialNxConfigurationAction::ResetTerminalExperiment,"aborted reset planned");auto next=Armed(7);Require(!next.completed&&!next.aborted&&next.initialCallsObserved==0&&next.redirectsPerformed==0&&next.firstThreadId==0&&!next.repeatPending,"experiment fields clean");Require(state.hasLastExperiment&&state.lastExperiment.aborted,"aborted result retained");});
    check("last experiment diagnostics remain stable after next arm",[]{aoe::InitialNxLifecycleState state;auto completed=Completed(4);aoe::ConfigureNextInitialNx(state,completed,8);aoe::MarkInitialNxConfigurationApplied(state);auto next=Armed(8);Require(state.lastExperiment.targetInitialCalls==4&&state.lastExperiment.initialCallsObserved==4&&state.lastExperiment.redirectsPerformed==3,"last result retained");Require(next.targetInitialCalls==8&&next.initialCallsObserved==0,"next result independent");});
    check("lifecycle layer does not alter proven replay implementation",[&]{const auto root=std::filesystem::path(__FILE__).parent_path().parent_path();std::ifstream input(root/L"src"/L"initial_2x.cpp");Require(input.good(),"current repository source is readable");const std::string source((std::istreambuf_iterator<char>(input)),{});Require(source.find("initial_nx_lifecycle")==std::string::npos,"replay implementation has no lifecycle dependency");});
    return passed;
}
