#include "live_validation.hpp"
#include "initial_2x.hpp"
#include <filesystem>
#include <fstream>
#include <functional>
#include <iostream>
#include <iterator>
#include <stdexcept>

namespace {
void Require(bool value,const std::string& message){if(!value)throw std::runtime_error(message);}
aoe::TargetInfo Target(uint32_t pid=900,uint64_t creation=1000,const std::string& sha="LIVE-SHA"){
    aoe::TargetInfo target;target.pid=pid;target.creationTime=creation;target.base=0x140000000;target.image.sha256=sha;target.verified=true;return target;
}
aoe::InitialCallSnapshot Registers(uint32_t thread=77){aoe::InitialCallSnapshot value;value.observed=true;value.threadId=thread;value.rsp=0x1000;value.r12=12;value.r13=13;value.r14=14;value.r15=15;value.rsi=16;value.rdi=17;return value;}
void Return(aoe::LiveValidationState& state,uint32_t thread=77){aoe::ObserveLiveReturn(state,thread,0x1000,12,13,14,15,16,17);}
void CompleteValidationCast(aoe::LiveValidationState& state){aoe::MarkLiveProfileFingerprintsPassed(state);aoe::ObserveLivePrep(state,77,1);auto registers=Registers();aoe::ObserveLiveCall(state,aoe::ClassifyOperationWord(0x0209),&registers);Return(state);for(unsigned i=0;i<aoe::RequiredPeriodic020AForLiveValidation;++i){aoe::ObserveLiveCall(state,aoe::ClassifyOperationWord(0x020A),&registers);Return(state);}}
std::string Read(const std::filesystem::path& path){std::ifstream input(path);Require(input.good(),"current repository source is readable");return std::string((std::istreambuf_iterator<char>(input)),{});}
}

unsigned LiveValidationTests(const std::filesystem::path& artifacts){unsigned passed=0;auto check=[&](const char* name,const std::function<void()>& test){test();++passed;std::cout<<"[PASS] "<<name<<'\n';};
    check("disarmed 0x0209 and 0x020A feed canonical live observation",[]{aoe::LiveValidationState state;auto target=Target();aoe::EnsureLiveValidationSession(state,target,"profile-A");auto registers=Registers();aoe::ObserveLiveCall(state,aoe::ClassifyOperationWord(0x0209),&registers);aoe::ObserveLiveCall(state,aoe::ClassifyOperationWord(0x020A),&registers);Require(state.seenInitial0209&&state.initial0209Count==1,"initial observed while replay disarmed");Require(state.seenPeriodic020A&&state.periodic020ACount==1,"periodic observed while replay disarmed");});
    check("Inspector shared-call observations bridge into same-session evidence",[]{aoe::LiveValidationState state;aoe::EnsureLiveValidationSession(state,Target(),"profile-A");aoe::ObserveLiveCall(state,aoe::ClassifyOperationWord(0x0209),nullptr);aoe::ObserveLiveCall(state,aoe::ClassifyOperationWord(0x020A),nullptr);Require(state.initial0209Count==1&&state.periodic020ACount==1&&state.callHitCount==2,"Inspector evidence shared");});
    check("same identity and Inspector stop preserve validation evidence",[]{aoe::LiveValidationState state;auto target=Target();aoe::EnsureLiveValidationSession(state,target,"profile-A");aoe::ObserveLiveCall(state,aoe::ClassifyOperationWord(0x0209),nullptr);Require(!aoe::EnsureLiveValidationSession(state,target,"profile-A"),"same session is retained");Require(state.initial0209Count==1,"evidence retained across mode transition");});
    check("Research to Play selection does not clear same-session evidence",[]{aoe::LiveValidationState state;auto target=Target();aoe::EnsureLiveValidationSession(state,target,"profile-A");aoe::ObserveLiveCall(state,aoe::ClassifyOperationWord(0x020A),nullptr);const auto before=state.periodic020ACount;Require(!aoe::EnsureLiveValidationSession(state,target,"profile-A")&&state.periodic020ACount==before,"UI page selection leaves runtime identity and evidence unchanged");});
    check("PID creation SHA and profile identity changes clear evidence",[]{for(unsigned variant=0;variant<4;++variant){aoe::LiveValidationState state;auto original=Target();aoe::EnsureLiveValidationSession(state,original,"profile-A");aoe::ObserveLiveCall(state,aoe::ClassifyOperationWord(0x0209),nullptr);auto changed=original;std::string identity="profile-A";if(variant==0)++changed.pid;else if(variant==1)++changed.creationTime;else if(variant==2)changed.image.sha256="OTHER-SHA";else identity="profile-B";Require(aoe::EnsureLiveValidationSession(state,changed,identity),"identity change resets");Require(!state.seenInitial0209&&state.initial0209Count==0,"old evidence discarded");}});
    check("one initial operation is insufficient for replay-critical validation",[]{aoe::LiveValidationState state;aoe::EnsureLiveValidationSession(state,Target(),"profile-A");aoe::MarkLiveProfileFingerprintsPassed(state);aoe::ObserveLivePrep(state,77,1);auto registers=Registers();aoe::ObserveLiveCall(state,aoe::ClassifyOperationWord(0x0209),&registers);Return(state);Require(!state.replayCriticalValidationPassed&&!aoe::ShouldAutoArmAfterValidation(state,true,false,true),"periodic phase required");});
    check("full 1 plus 9 call-return validation enables only the next cast",[]{aoe::LiveValidationState state;auto target=Target();aoe::EnsureLiveValidationSession(state,target,"profile-A");aoe::Initial2xExperiment replay;CompleteValidationCast(state);Require(state.replayCriticalValidationPassed&&state.periodic020ACount==9&&state.periodic020AReturnCount==9,"complete validation cast");Require(!replay.armed&&!replay.repeatPending&&replay.redirectCount==0,"validation cast never enters replay state");Require(aoe::CanArmInitialNxFromValidation(state,target,"profile-A"),"manual arm eligible for next cast");Require(aoe::ShouldAutoArmAfterValidation(state,true,false,true),"configured Auto Arm becomes eligible after completion");Require(!aoe::ShouldAutoArmAfterValidation(state,false,false,true),"Auto Arm off still validates without arming");Require(!aoe::ShouldAutoArmAfterValidation(state,true,true,true),"already armed is not armed again");});
    check("periodic returns are required and producer counters stay distinct",[]{aoe::LiveValidationState state;aoe::EnsureLiveValidationSession(state,Target(),"profile-A");aoe::MarkLiveProfileFingerprintsPassed(state);aoe::ObserveLivePrep(state,77,1);auto registers=Registers();aoe::ObserveLiveCall(state,aoe::ClassifyOperationWord(0x0209),&registers);Return(state);for(unsigned i=0;i<9;++i)aoe::ObserveLiveCall(state,aoe::ClassifyOperationWord(0x020A),&registers);aoe::ObserveLiveProducer(state,aoe::ClassifyOperationWord(0x020A));Require(!state.replayCriticalValidationPassed&&state.periodic020ACount==9&&state.periodic020AReturnCount==0,"returns still missing");Require(state.producer020ACount==1&&state.periodic020ACount==9,"producer path reported separately");});
    check("canonical operation decoder is used by tracer and Inspector",[&]{const auto root=std::filesystem::path(__FILE__).parent_path().parent_path();const auto tracer=Read(root/L"src"/L"tracer.cpp"),inspector=Read(root/L"src"/L"target_inspector.cpp");Require(tracer.find("DecodeOperation")!=std::string::npos&&inspector.find("DecodeOperation")!=std::string::npos,"shared decoder wired to both paths");});
    check("live validation and Target Inspector contain no gameplay write or RIP redirect",[&]{const auto root=std::filesystem::path(__FILE__).parent_path().parent_path();const auto live=Read(root/L"src"/L"live_validation.cpp")+Read(root/L"src"/L"operation_observer.cpp")+Read(root/L"src"/L"target_inspector.cpp");Require(live.find("WriteProcessMemory")==std::string::npos&&live.find("VirtualProtectEx")==std::string::npos,"no target memory write API");Require(live.find("context.Rip")==std::string::npos&&live.find("SetThreadContext")==std::string::npos,"no redirect in observation path");});
    return passed;
}
