#include "producer.hpp"
#include "analysis.hpp"
#include <array>
#include <cmath>
#include <cstring>
#include <fstream>
#include <functional>
#include <iostream>
#include <stdexcept>

namespace {
void Require(bool b,const char* message){if(!b)throw std::runtime_error(message);}
aoe::Event Entry(){aoe::Event e;e.rcx=0x123456789ABCDEF0;e.rdx=0xABCDEF0198765432;e.r8=0xFFFFFFFF76543210;e.r9=0x1234AB;e.returnReadable=e.returnInModule=true;e.returnRva=aoe::ProducerCallerRva;e.producer.rawStack.resize(0xA0);for(unsigned i=0;i<0xA0;++i)e.producer.rawStack[i]=uint8_t(i);aoe::DecodeProducerArguments(e);return e;}
}
unsigned ProducerTests(const std::filesystem::path& artifacts){
    unsigned passed=0;auto check=[&](const char* title,const std::function<void()>& f){f();++passed;std::cout<<"[PASS] "<<title<<'\n';};
    check("producer argument widths and entry-stack offsets",[]{auto e=Entry();auto& a=e.producer.arguments;Require(a.size()==18,"18 inputs");Require(a[0].bits==e.rcx&&a[1].bits==0x98765432&&a[2].bits==0x76543210&&a[3].bits==0xAB,"register truncations");Require(a[4].bits==0x2B2A2928&&a[7].bits==0x4746454443424140&&a[8].bits==0x4948&&a[17].bits==0x93929190,"entry stack decoding");Require(e.producer.expectedCaller,"expected caller");e.producer.rawStack.resize(0x29);aoe::DecodeProducerArguments(e);Require(!e.producer.arguments[4].readable&&e.producer.arguments[3].readable,"partial stack is not zero-valued input");});
    check("producer float bit patterns survive NaN infinity and signed zero",[]{auto e=Entry();for(uint32_t bits:{0x80000000u,0x7FC01234u,0x7F800000u,0x3F800000u}){memcpy(e.producer.rawStack.data()+0x28,&bits,4);aoe::DecodeProducerArguments(e);Require(e.producer.arguments[4].bits==bits,"float bits exact");Require(e.producer.arguments[4].raw.size()==4,"float raw bytes");}});
    check("producer invalid stack and vector addresses remain diagnostic",[]{aoe::Event e;e.rsp=1;aoe::SnapshotProducer(GetCurrentProcess(),e);Require(e.producer.captured&&!e.producer.stackReadable&&!e.producer.arguments[7].readable,"invalid stack handled");std::array<uint8_t,0xA0> stack{};uint64_t ptr=UINT64_MAX-8;memcpy(stack.data()+0x40,&ptr,8);e.rsp=reinterpret_cast<uint64_t>(stack.data());aoe::SnapshotProducer(GetCurrentProcess(),e);Require(e.producer.stackReadable&&!e.producer.vectorValid&&e.producer.vectorError!=0,"overflow vector handled");});
    check("producer vector shape validates bounds alignment and sanity",[]{aoe::ProducerSnapshot p;p.vectorHeaderReadable=true;Require(aoe::ValidateProducerVector(p)&&p.elementCount==0,"empty vector");p.begin=0x10000;p.end=0x10010;p.capacity=0x10020;Require(aoe::ValidateProducerVector(p)&&p.elementCount==2,"valid span");p.end=0xFFFF;Require(!aoe::ValidateProducerVector(p),"unordered span");p.end=0x10011;Require(!aoe::ValidateProducerVector(p),"unaligned span");p.end=0x10000+8ull*65537;p.capacity=p.end;Require(!aoe::ValidateProducerVector(p),"excessive count");});
    check("producer vector reads at most 64 pointers and 16 bytes per record",[]{std::array<uint8_t,16> record{};record[15]=0xAC;std::array<uint64_t,70> pointers{};pointers.fill(reinterpret_cast<uint64_t>(record.data()));pointers[1]=1;std::array<uint64_t,3> header={reinterpret_cast<uint64_t>(pointers.data()),reinterpret_cast<uint64_t>(pointers.data()+70),reinterpret_cast<uint64_t>(pointers.data()+70)};std::array<uint8_t,0xA0> stack{};auto ptr=reinterpret_cast<uint64_t>(header.data());memcpy(stack.data()+0x40,&ptr,8);aoe::Event e;e.rsp=reinterpret_cast<uint64_t>(stack.data());aoe::SnapshotProducer(GetCurrentProcess(),e);auto& p=e.producer;Require(p.vectorValid&&p.elementCount==70&&p.elements.size()==64,"snapshot limit");Require(p.elements[0].recordReadable&&p.elements[0].bytes.size()==16&&p.elements[0].bytes[15]==0xAC,"record snapshot");Require(!p.elements[1].recordReadable&&p.elements[2].recordReadable,"bad record does not stop traversal");});
    check("producer field stability retains sequence exact changes and missing data",[]{auto c=aoe::SyntheticProducerCapture();auto f=aoe::CompareProducerFields(c);Require(f.size()==18&&f[1].constant&&f[1].observations==9,"constant input");Require(!f[9].constant&&f[9].distinct==9&&f[9].deltas.size()==8&&f[9].deltas[0]=="1","changing sequence");c.events[4].producer.arguments[9].readable=false;f=aoe::CompareProducerFields(c);Require(f[9].missing==1&&f[9].observations==8&&f[9].deltas[3]=="null"&&f[9].deltas[4]=="null","missing gap not bridged");});
    check("producer nine event timing and unexpected caller grouping",[]{auto c=aoe::SyntheticProducerCapture();auto a=aoe::Analyze(c);Require(a.groups.size()==1&&a.groups[0].count==9&&a.groups[0].periodicNear1s&&std::abs(a.groups[0].meanDeltaMs-997)<.001,"nine near-second events");auto e=c.events[0];e.returnRva=0x12345;e.returnAddress=c.target.base+e.returnRva;aoe::DecodeProducerArguments(e);c.events.push_back(e);a=aoe::Analyze(c);Require(a.groups.size()==2&&!c.events.back().producer.expectedCaller,"other caller retained");auto m=aoe::RelativeToMarkers(c,1997);Require(m.available&&m.nearestRelativeMs==997,"marker relation");auto idle=c;idle.label=aoe::Label::Idle;idle.events.clear();a=aoe::Analyze(c,&idle);Require(a.idleCompatible&&a.groups[0].idleCount==0,"producer idle baseline");idle.target.mode=aoe::TraceMode::Queue;a=aoe::Analyze(c,&idle);Require(!a.idleCompatible,"modes not mixed");});
    check("producer additive JSON retains old fields and nonfinite raw bits",[&]{auto c=aoe::SyntheticProducerCapture();uint32_t bits=0x7FC01234;memcpy(c.events[0].producer.rawStack.data()+0x28,&bits,4);aoe::DecodeProducerArguments(c.events[0]);auto a=aoe::Analyze(c);std::string error;auto path=artifacts/"producer_capture.json";Require(aoe::ExportJson(path,c,a,error),"export JSON");std::ifstream in(path);std::string text((std::istreambuf_iterator<char>(in)),{});for(auto token:{"\"producerFieldStability\"","\"rawEntryStack\"","\"floatRawUint32\":2143294004","\"value\":null","\"markerRelativeTimes\"","\"r8dPacketLength\"","\"rip\"","\"arguments\"",aoe::ProducerLimitation})Require(text.find(token)!=std::string::npos,token);});
    return passed;
}
