#include "selected_target_provenance.hpp"
#include <cstring>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <stdexcept>

namespace {
void Require(bool value,const std::string& message){if(!value)throw std::runtime_error(message);}
struct Memory {std::map<uint64_t,uint8_t> bytes;template<class T>void put(uint64_t at,const T& v){auto p=reinterpret_cast<const uint8_t*>(&v);for(size_t i=0;i<sizeof(v);++i)bytes[at+i]=p[i];}void raw(uint64_t at,const void* v,size_t n){auto p=static_cast<const uint8_t*>(v);for(size_t i=0;i<n;++i)bytes[at+i]=p[i];}bool read(uint64_t at,void* out,size_t n,uint32_t& error)const{auto p=static_cast<uint8_t*>(out);for(size_t i=0;i<n;++i){auto it=bytes.find(at+i);if(it==bytes.end()){error=299;return false;}p[i]=it->second;}error=0;return true;}};
aoe::InspectorRead Reader(const Memory& m){return[&](uint64_t a,void* d,size_t n,uint32_t& e){return m.read(a,d,n,e);};}
aoe::RuntimeLayout Layout(){aoe::RuntimeLayout r;r.gameContextPointerRva=0xE6C9C0;r.selectedTargetOffset=0x2318;r.selectedTargetWriterRva=0x7F6411;r.selectedTargetReaderRvas={0x799891,0x7D7C77};r.actorIdOffset=0x768;r.actorTypeOffset=0x7E1;r.localActorOffset=0x2710;r.actorPositionOffset=0xB0;r.actorWorldLinkOffset=0x1390;r.actorWorldLinkOwnerOffset=0x1380;r.actorWorldPositionOffset=0x70;r.actorTreeOffsets[1]=0x1140;r.actorTreeOffsets[2]=0x1120;return r;}
void Monster(Memory& m,const aoe::RuntimeLayout& l,uint64_t module,uint64_t context,uint64_t actor,uint32_t id,uint64_t seed){const uint64_t header=seed,node=seed+0x100,sentinel=seed+0x200,link=seed+0x300;const uint8_t zero=0,one=1,type=2;m.put(module+l.gameContextPointerRva,context);m.put(context+l.selectedTargetOffset,actor);m.put(context+l.actorTreeOffsets[2],header);m.put(header+8,node);m.put(node,sentinel);m.put(node+0x19,zero);m.put(node+0x20,id);m.put(node+0x28,actor);m.put(sentinel+0x19,one);m.put(actor+l.actorIdOffset,id);m.put(actor+l.actorTypeOffset,type);m.put(actor+l.actorWorldLinkOffset,link);m.put(link+l.actorWorldLinkOwnerOffset,actor);std::array<float,3> xyz{float(id),2,3};m.raw(link+l.actorWorldPositionOffset,xyz.data(),sizeof(xyz));}
aoe::SelectedTargetCapture Valid(const char* label,uint64_t pointer,uint32_t id){aoe::SelectedTargetCapture c;c.label=label;c.storageReadable=c.identityReadable=c.categoryMonster=c.resolverMatched=true;c.rawValue=c.actorPointer=pointer;c.actorId=id;c.actorType=c.category=2;return c;}
}

unsigned SelectedTargetProvenanceTests(const std::filesystem::path& artifacts){unsigned passed=0;auto check=[&](const char* name,const std::function<void()>& fn){fn();++passed;std::cout<<"[PASS] "<<name<<'\n';};
    check("direct selected actor pointer capture",[]{Memory m;auto l=Layout();Monster(m,l,0x140000000,0x100000,0x200000,101,0x300000);auto c=aoe::CaptureSelectedTarget(Reader(m),l,0x140000000,"A",1);Require(c.storageReadable&&c.rawValue==0x200000&&c.actorPointer==0x200000,"direct pointer");});
    check("category 2 validation",[]{Memory m;auto l=Layout();Monster(m,l,0x140000000,0x100000,0x200000,101,0x300000);auto c=aoe::CaptureSelectedTarget(Reader(m),l,0x140000000,"A",1);Require(c.identityReadable&&c.categoryMonster&&c.actorType==2&&c.category==2,"monster category");});
    check("category 1 candidate rejection",[]{Memory m;auto l=Layout();const uint64_t module=0x140000000,context=0x100000,actor=0x200000;const uint32_t id=7;const uint8_t type=1;m.put(module+l.gameContextPointerRva,context);m.put(context+l.selectedTargetOffset,actor);m.put(context+l.localActorOffset,actor);m.put(actor+l.actorIdOffset,id);m.put(actor+l.actorTypeOffset,type);auto c=aoe::CaptureSelectedTarget(Reader(m),l,module,"A",1);Require(c.identityReadable&&!c.categoryMonster&&c.validation.find("rejected")!=std::string::npos,"category 1 rejected");});
    check("invalid unreadable pointer rejection",[]{Memory m;auto l=Layout();const uint64_t module=0x140000000,context=0x100000,bad=0x222000;m.put(module+l.gameContextPointerRva,context);m.put(context+l.selectedTargetOffset,bad);auto c=aoe::CaptureSelectedTarget(Reader(m),l,module,"A",1);Require(c.storageReadable&&!c.identityReadable&&!c.categoryMonster,"unreadable rejected");});
    check("ID type resolver success",[]{Memory m;auto l=Layout();Monster(m,l,0x140000000,0x100000,0x200000,101,0x300000);auto c=aoe::CaptureSelectedTarget(Reader(m),l,0x140000000,"A",1);Require(c.resolverMatched,"tree resolver agrees");});
    check("resolver failure does not create false target",[]{Memory m;auto l=Layout();const uint64_t module=0x140000000,context=0x100000,actor=0x200000;const uint32_t id=9;const uint8_t type=2;m.put(module+l.gameContextPointerRva,context);m.put(context+l.selectedTargetOffset,actor);m.put(actor+l.actorIdOffset,id);m.put(actor+l.actorTypeOffset,type);auto c=aoe::CaptureSelectedTarget(Reader(m),l,module,"A",1);Require(c.identityReadable&&!c.resolverMatched,"no false resolution");});
    check("A B C different actor identities prove direct pointer",[]{aoe::SelectedTargetProvenanceSession s;s.phase=aoe::SelectedTargetPhase::Running;std::string e;for(int i=0;i<3;++i)Require(aoe::RecordSelectedTargetCapture(s,Valid(std::string(1,char('A'+i)).c_str(),0x200000+i*0x1000,100+i),e),e);Require(aoe::AnalyzeSelectedTargetProvenance(s).classification==aoe::SelectedTargetClassification::ProvenDirectPointer,"ABC proof");});
    check("same actor repeatedly does not prove switching",[]{aoe::SelectedTargetProvenanceSession s;s.phase=aoe::SelectedTargetPhase::Running;std::string e;for(int i=0;i<3;++i)aoe::RecordSelectedTargetCapture(s,Valid(std::string(1,char('A'+i)).c_str(),0x200000,100),e);Require(aoe::AnalyzeSelectedTargetProvenance(s).classification==aoe::SelectedTargetClassification::CandidateOnly,"same actor candidate only");});
    check("deselected null state",[]{Memory m;auto l=Layout();const uint64_t module=0x140000000,context=0x100000,zero=0;m.put(module+l.gameContextPointerRva,context);m.put(context+l.selectedTargetOffset,zero);auto c=aoe::CaptureSelectedTarget(Reader(m),l,module,"NONE",1);Require(c.storageReadable&&c.nullSelection&&!c.identityReadable,"null selection");});
    check("monster XYZ validates actor link relationship",[]{Memory m;auto l=Layout();Monster(m,l,0x140000000,0x100000,0x200000,101,0x300000);auto c=aoe::CaptureSelectedTarget(Reader(m),l,0x140000000,"A",1);Require(c.positionAvailable&&c.position.value[0]==101,"linked XYZ");});
    check("invalid actor world link rejected",[]{Memory m;auto l=Layout();Monster(m,l,0x140000000,0x100000,0x200000,101,0x300000);const uint64_t wrong=0x555000;m.put(0x300300+l.actorWorldLinkOwnerOffset,wrong);auto c=aoe::CaptureSelectedTarget(Reader(m),l,0x140000000,"A",1);Require(!c.positionAvailable,"invalid owner link");});
    check("selected target JSON export",[&]{aoe::SelectedTargetProvenanceSession s;s.phase=aoe::SelectedTargetPhase::Captured;s.runtime=Layout();s.captures.push_back(Valid("A",0x200000,100));auto p=artifacts/L"selected-target-provenance.json";std::string e;Require(aoe::ExportSelectedTargetProvenanceJson(p,s,e),e);std::ifstream in(p);std::string text((std::istreambuf_iterator<char>(in)),{});Require(text.find("selectedTargetProvenance")!=std::string::npos&&text.find("gameContextPointerRva")!=std::string::npos,"json schema");});
    check("one capture cannot become proven",[]{aoe::SelectedTargetProvenanceSession s;s.captures.push_back(Valid("A",0x200000,100));Require(aoe::AnalyzeSelectedTargetProvenance(s).classification==aoe::SelectedTargetClassification::InsufficientData,"single capture");});
    check("Initial Nx conflict remains mutually exclusive",[]{aoe::Initial2xExperiment nx;nx.armed=true;nx.phase=aoe::Initial2xPhase::Waiting0209;Require(aoe::InitialNxConflictsWithTargetInspector(nx),"Nx conflict");});
    check("Differential Inspector operation decoding remains compatible",[]{std::array<uint8_t,aoe::DifferentialOperationRecordBytes> raw{};float x=1,y=2,z=3;memcpy(raw.data(),&x,4);memcpy(raw.data()+4,&y,4);memcpy(raw.data()+8,&z,4);Require(aoe::DecodeOperationSpatialFields(raw,true).plausible,"legacy spatial decode");});
    check("provenance implementation contains no process write or RIP redirect",[]{std::ifstream in(L"C:\\Users\\Public\\Documents\\4UnityAOEManager\\src\\selected_target_provenance.cpp");std::string source((std::istreambuf_iterator<char>(in)),{});Require(source.find("WriteProcessMemory")==std::string::npos&&source.find("SetThreadContext")==std::string::npos&&source.find("Rip")==std::string::npos,"read only source");});
    check("hardware breakpoint diagnostic includes all slots",[]{auto d=aoe::FormatHardwareBreakpointDiagnostic(77,{1,2,3,4},5,2,1);Require(d.find("thread ID=77")!=std::string::npos&&d.find("DR0=0x1")!=std::string::npos&&d.find("DR3=0x4")!=std::string::npos&&d.find("required slots=2")!=std::string::npos&&d.find("available slots=1")!=std::string::npos,"diagnostic fields");});
    return passed;
}
