#include "visual_suppression.hpp"
#include "initial_2x.hpp"
#include <functional>
#include <iostream>
#include <stdexcept>

namespace {
void Require(bool condition,const std::string& message){if(!condition)throw std::runtime_error(message);}
aoe::TargetInfo Target(){aoe::TargetInfo t;t.pid=41;t.creationTime=82;t.base=0x140000000;t.verified=true;t.image.sha256="VISUAL-SHA";auto&r=t.runtime;r.visualSuppressionAvailable=true;r.visualReaderRva=0x100;r.visualLookupRva=0x500;r.visualFieldOffset=0x8C;r.visualBaseRegister=aoe::X64RegisterId::Rdx;r.visualReaderBytes={0x8B};return t;}
aoe::VisualRuntimeState Resolved(){aoe::VisualRuntimeState s;aoe::InitializeVisualRuntime(s,Target());s.captureBreakpointActive=true;std::string error;Require(aoe::ObserveVisualReader(s,77,0x100000,328,error),error);aoe::ObserveVisualPreparation(s,77);Require(aoe::ConfirmVisualAoeCall(s,77,true,0x0209),"correlated visual capture");return s;}
aoe::VisualSessionIdentity Identity(uint64_t generation=3){auto t=Target();return{t.pid,t.creationTime,t.base,generation,t.image.sha256};}
}

unsigned VisualSuppressionTests(const std::filesystem::path&){unsigned passed=0;auto check=[&](const char* name,const std::function<void()>& body){body();++passed;std::cout<<"[PASS] "<<name<<'\n';};
    check("pending Hide reader survives repeated continuous Nx reset plans",[]{auto target=Target();target.runtime.producerRva=0x900;target.runtime.initialNxAvailable=true;target.runtime.initialPrepRva=0x1100;aoe::VisualRuntimeState visual;aoe::InitializeVisualRuntime(visual,target);visual.captureBreakpointActive=true;for(unsigned cast=0;cast<5;++cast){auto nx=aoe::CreateInitial2xExperiment(target,false,100);nx.completed=true;nx.initialCallsObserved=100;nx={};const auto plan=aoe::PlanInitialVisualBreakpoints(visual,target.runtime);Require(plan.fourthRva==target.runtime.visualReaderRva&&plan.requiredSlots==4&&plan.keepAfterInitialTerminal&&!plan.observesProducer,"reset preserves reader instead of substituting producer");}std::string error;Require(aoe::ObserveVisualReader(visual,77,0x200000,328,error),error);aoe::ObserveVisualPreparation(visual,77);Require(aoe::ConfirmVisualAoeCall(visual,77,true,0x0209),"next cast can still resolve Hide after Nx resets");});
    check("attach reserves reader and core coverage across resolved Hide and OFF",[]{auto visual=Resolved();auto target=Target();target.runtime.producerRva=0x900;visual.suppressionRequested=true;auto plan=aoe::PlanInitialVisualBreakpoints(visual,target.runtime);Require(visual.readerCoverageActive&&plan.keepAfterInitialTerminal&&plan.fourthRva==target.runtime.visualReaderRva&&plan.requiredSlots==4&&!plan.observesProducer,"reader is reserved from attach without a producer swap");visual.suppressionRequested=false;Require(aoe::PlanInitialVisualBreakpoints(visual,target.runtime).keepAfterInitialTerminal,"OFF retains the same slot until detach");aoe::InvalidateVisualRuntime(visual,aoe::VisualRuntimePhase::SessionChanged,"ended");Require(!visual.readerCoverageActive&&!aoe::PlanInitialVisualBreakpoints(visual,target.runtime).keepAfterInitialTerminal,"session end releases reservation");});
    check("Hide during correlated Nx call waits until final return",[]{auto visual=Resolved();visual.suppressionRequested=true;visual.downstreamOriginalActive=true;visual.downstreamThreadId=77;uint32_t memory=328,writes=0;aoe::VisualMemoryIo io;io.read=[&](uint64_t,uint32_t&v,std::string&){v=memory;return true;};io.write=[&](uint64_t,uint32_t v,std::string&){memory=v;++writes;return true;};std::string error;Require(aoe::ApplyVisualSuppression(visual,io,error)&&memory==328&&writes==0,"UI hide request leaves active worker input unchanged");for(unsigned redirect=0;redirect<99;++redirect)Require(aoe::EndVisualDamageWindow(visual,77,true,io,error)&&memory==328&&writes==0,"100x replay retains original until final return");Require(aoe::EndVisualDamageWindow(visual,77,false,io,error)&&memory==0&&writes==1&&!visual.downstreamOriginalActive,"final return applies Hide exactly once");});
    check("Hide remains effective across repeated periodic and initial calls",[]{auto visual=Resolved();visual.suppressionRequested=true;uint32_t memory=328;aoe::VisualMemoryIo io;io.read=[&](uint64_t,uint32_t&v,std::string&){v=memory;return true;};io.write=[&](uint64_t,uint32_t v,std::string&){memory=v;return true;};std::string error;Require(aoe::ApplyVisualSuppression(visual,io,error)&&memory==0,error);for(unsigned call=0;call<10;++call){Require(aoe::BeginVisualDamageWindow(visual,77,io,error)&&memory==328,error);Require(aoe::EndVisualDamageWindow(visual,88,false,io,error)&&memory==328,"unrelated return cannot close owned window");Require(aoe::EndVisualDamageWindow(visual,77,false,io,error)&&memory==0,error);}memory=328;Require(aoe::BeginVisualDamageWindow(visual,77,io,error)&&visual.downstreamOriginalActive,"captured original already present still establishes return ownership");Require(aoe::EndVisualDamageWindow(visual,77,false,io,error)&&memory==0,"original rewritten by game is hidden again after owned return");});
    check("Hide OFF cancels deferred zero and restores captured original",[]{auto visual=Resolved();visual.suppressionRequested=true;visual.downstreamOriginalActive=true;visual.downstreamThreadId=77;uint32_t memory=328,writes=0;aoe::VisualMemoryIo io;io.read=[&](uint64_t,uint32_t&v,std::string&){v=memory;return true;};io.write=[&](uint64_t,uint32_t v,std::string&){memory=v;++writes;return true;};std::string error;Require(aoe::ApplyVisualSuppression(visual,io,error),error);visual.suppressionRequested=false;Require(aoe::ApplyVisualSuppression(visual,io,error)&&aoe::EndVisualDamageWindow(visual,77,false,io,error)&&memory==328&&writes==0,"OFF during active call prevents queued hide");visual.suppressionRequested=true;Require(aoe::ApplyVisualSuppression(visual,io,error)&&memory==0,error);visual.suppressionRequested=false;Require(aoe::ApplyVisualSuppression(visual,io,error)&&memory==328,"worker cleanup restores dynamic original");});
    check("visual worker refuses unrelated values and failed readback",[]{auto visual=Resolved();visual.suppressionRequested=true;uint32_t memory=777,writes=0;aoe::VisualMemoryIo io;io.read=[&](uint64_t,uint32_t&v,std::string&){v=memory;return true;};io.write=[&](uint64_t,uint32_t,std::string&){++writes;return true;};std::string error;Require(!aoe::ApplyVisualSuppression(visual,io,error)&&writes==0&&!visual.restoreRequired,"foreign original never overwritten or claimed");memory=0;Require(!aoe::ApplyVisualSuppression(visual,io,error)&&writes==0&&!visual.restoreRequired,"unowned zero is rejected");memory=328;Require(!aoe::ApplyVisualSuppression(visual,io,error)&&writes==1&&!visual.error.empty()&&visual.restoreRequired,"failed zero readback retains cleanup responsibility");visual.suppressionRequested=false;Require(aoe::ApplyVisualSuppression(visual,io,error)&&!visual.restoreRequired&&writes==1,"cleanup accepts captured original already restored");});
    check("visual reader candidate requires same-thread prep and established AOE operation",[]{auto s=Resolved();Require(s.resolved&&s.tSkill==0x100000&&s.visualField==0x10008C&&s.originalValue==328,"resolved session fields");});
    check("periodic 020A resolves an already active AOE visual",[]{aoe::VisualRuntimeState s;aoe::InitializeVisualRuntime(s,Target());s.captureBreakpointActive=true;std::string error;Require(aoe::ObserveVisualReader(s,77,0x200000,328,error),error);aoe::ObserveVisualPreparation(s,77);Require(aoe::ConfirmVisualAoeCall(s,77,true,0x020A)&&s.resolved&&s.tSkill==0x200000,"correlated periodic AOE capture");});
    check("unrelated skill does not resolve TSkill",[]{aoe::VisualRuntimeState s;aoe::InitializeVisualRuntime(s,Target());s.captureBreakpointActive=true;std::string error;Require(aoe::ObserveVisualReader(s,77,0x200000,314,error),error);aoe::ObserveVisualPreparation(s,77);Require(!aoe::ConfirmVisualAoeCall(s,77,true,0x0210)&&!s.resolved,"non-AOE operation rejected");});
    check("session identity change invalidates cached TSkill",[]{aoe::VisualSessionCache c;std::string error;Require(aoe::BindVisualSessionCache(c,Resolved(),Identity(),error),error);auto changed=Identity(4);unsigned writes=0;aoe::VisualMemoryIo io;io.read=[](uint64_t,uint32_t&v,std::string&){v=328;return true;};io.write=[&](uint64_t,uint32_t,std::string&){++writes;return true;};Require(!aoe::SetVisualHidden(c,changed,true,io,error)&&writes==0&&error.find("SESSION CHANGED")!=std::string::npos,"stale write blocked");});
    check("hide writes one uint32 zero and captures no constant original",[]{aoe::VisualSessionCache c;std::string error;Require(aoe::BindVisualSessionCache(c,Resolved(),Identity(),error),error);uint32_t memory=328,written=99;size_t writeSize=0;aoe::VisualMemoryIo io;io.read=[&](uint64_t,uint32_t&v,std::string&){v=memory;return true;};io.write=[&](uint64_t,uint32_t v,std::string&){written=v;writeSize=sizeof(v);memory=v;return true;};Require(aoe::SetVisualHidden(c,Identity(),true,io,error),error);Require(c.hidden&&written==0&&writeSize==4&&c.originalValue==328,"four-byte zero write");});
    check("restore uses dynamically captured original value",[]{aoe::VisualSessionCache c;std::string error;Require(aoe::BindVisualSessionCache(c,Resolved(),Identity(),error),error);uint32_t memory=328;aoe::VisualMemoryIo io;io.read=[&](uint64_t,uint32_t&v,std::string&){v=memory;return true;};io.write=[&](uint64_t,uint32_t v,std::string&){memory=v;return true;};Require(aoe::SetVisualHidden(c,Identity(),true,io,error)&&memory==0,error);Require(aoe::SetVisualHidden(c,Identity(),false,io,error)&&memory==328&&!c.hidden,error);});
    check("restore accepts original already exposed for downstream damage",[]{aoe::VisualSessionCache c;std::string error;Require(aoe::BindVisualSessionCache(c,Resolved(),Identity(),error),error);uint32_t memory=328,writes=0;aoe::VisualMemoryIo io;io.read=[&](uint64_t,uint32_t&v,std::string&){v=memory;return true;};io.write=[&](uint64_t,uint32_t v,std::string&){++writes;memory=v;return true;};c.hidden=true;Require(aoe::SetVisualHidden(c,Identity(),false,io,error)&&!c.hidden&&writes==0,"already restored original accepted without another write");});
    check("restore refuses field changed by another owner",[]{aoe::VisualSessionCache c;std::string error;Require(aoe::BindVisualSessionCache(c,Resolved(),Identity(),error),error);uint32_t memory=328;unsigned writes=0;aoe::VisualMemoryIo io;io.read=[&](uint64_t,uint32_t&v,std::string&){v=memory;return true;};io.write=[&](uint64_t,uint32_t v,std::string&){++writes;memory=v;return true;};Require(aoe::SetVisualHidden(c,Identity(),true,io,error),error);memory=777;Require(!aoe::SetVisualHidden(c,Identity(),false,io,error)&&writes==1&&memory==777,"blind restore blocked");});
    check("zero original is rejected before ownership",[]{aoe::VisualRuntimeState s;aoe::InitializeVisualRuntime(s,Target());s.captureBreakpointActive=true;std::string error;Require(!aoe::ObserveVisualReader(s,77,0x100000,0,error)&&!s.resolved,"zero cannot become original");});
    return passed;
}
