<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>4UnitySpeedJump</AssemblyName>
    <RootNamespace>SpeedJump</RootNamespace>
    <Version>1.0.0</Version>
</PropertyGroup>
  <ItemGroup><EmbeddedResource Include="signatures.json" /></ItemGroup>
<ItemGroup><ProjectReference Include="../../Suite/Controls/UnityTools.Controls.csproj" /></ItemGroup>
</Project>
