using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace UnityMonsterList;

static class Program
{
    [STAThread] static void Main(string[] args){if(args.Contains("--linked-test")){LinkedMemoryTests.Run();return;}if(args.Contains("--center-test")){LearnedCenterTests.Run();return;}if(args.Length==2 && args[0]=="--center-replay"){LearnedCenterTests.Replay(args[1]);return;}if(args.Length==2 && args[0]=="--recover"){CaptureFiles.FinalizeCapture(Path.GetFullPath(args[1]),"RECOVERED_AFTER_FINALIZATION_ERROR; original stop reason not independently recorded");return;}if(args.Contains("--file-test")){CaptureFileTests.Run();return;}if(args.Contains("--profile-test")){PlayerSource.Test();return;}if(args.Contains("--self-test")){CaptureTests.Run();return;}if(args.Contains("--smoke")){var samples=new List<Snapshot>();for(int i=0;i<8;i++){samples.Add(Reader.Capture());Thread.Sleep(250);}File.WriteAllText(Path.Combine(AppContext.BaseDirectory,"smoke.json"),JsonSerializer.Serialize(samples,new JsonSerializerOptions{WriteIndented=true}));return;}ApplicationConfiguration.Initialize();if(args.Contains("--ui-test")){UiTests.Run();return;}Application.Run(new MainForm());}
}

static class Reader
{
    const string ExpectedSha="9CD77CD0C305359A3048D60C3C2FD837B907E2E61BBF8B828BFCC8E5270E5C28"; const long ContextRva=0xE6E9C0;
    public static Snapshot Capture(){try{var ps=Process.GetProcessesByName("TClient");var p=ps.FirstOrDefault(x=>x.MainWindowTitle=="4Unity")??ps.FirstOrDefault();if(p is null)return Snapshot.Disconnected("TClient.exe bulunamadı");IntPtr h=N.OpenProcess(0x1010,false,p.Id);if(h==IntPtr.Zero)return Snapshot.Disconnected($"OpenProcess başarısız: {Marshal.GetLastWin32Error()}",p.Id);try{string path=PathOf(h);string sha=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(path)));long mb=Module(p.Id,path);if(sha!=ExpectedSha)return new(DateTimeOffset.Now,"UNVERIFIED_BUILD","UNVERIFIED_BUILD",p.Id,sha,$"0x{mb:X}",null,null,[],"UNRESOLVED",null,"SHA-256 current profile ile eşleşmiyor; offset kullanılmadı.");var rpm=new Rpm(h);ulong? ctx=rpm.Q(mb+ContextRva);if(!Rpm.P(ctx))return Fail(p,sha,mb,"Context global okunamadı");ulong? head=rpm.Q((long)ctx!.Value+0x1120);if(!Rpm.P(head))return Fail(p,sha,mb,"Monster tree head okunamadı",ctx);PlayerInfo? player=ValidatedPlayer(rpm,ctx.Value,mb,PlayerSource.Load(path));var rows=Walk(rpm,head!.Value,player is null?null:new Position(player.X,player.Y,player.Z),out string validation);int valid=rows.Count(x=>x.PositionValid);bool diverse=rows.Where(x=>x.PositionValid).Select(x=>(Math.Round(x.X,2),Math.Round(x.Z,2))).Distinct().Take(3).Count()>=3;string posStatus=rows.Count>0&&valid==rows.Count&&diverse?"POSITION_CANDIDATE":"CURRENT_TENTATIVE";string status=validation=="ok"?"REGISTRY_CANDIDATE":"REGISTRY_WARNING";string msg=$"{validation}; XYZ {valid}/{rows.Count} {posStatus}; Player distance {(player is null?"UNRESOLVED":player.Status)}";return new(DateTimeOffset.Now,status,status,p.Id,sha,$"0x{mb:X}",$"0x{ctx:X}",$"0x{head:X}",rows,posStatus,player,msg);}finally{N.CloseHandle(h);}}catch(Exception ex){return Snapshot.Disconnected(ex.Message);}}
    static Snapshot Fail(Process p,string sha,long mb,string msg,ulong? ctx=null)=>new(DateTimeOffset.Now,"CURRENT_TENTATIVE","CURRENT_TENTATIVE",p.Id,sha,$"0x{mb:X}",ctx is null?null:$"0x{ctx:X}",null,[],"UNRESOLVED",null,msg);
    static List<Monster> Walk(Rpm r,ulong head,Position? player,out string validation){var result=new List<Monster>();ulong? root=r.Q((long)head+8),leftmost=r.Q((long)head),rightmost=r.Q((long)head+0x10);if(!Rpm.P(root)||!Rpm.P(leftmost)||!Rpm.P(rightmost)){validation="head root/leftmost/rightmost invalid";return result;}if(root==head){validation="ok";return result;}var stack=new Stack<ulong>();var seen=new HashSet<ulong>();var actors=new HashSet<ulong>();stack.Push(root!.Value);int malformed=0;while(stack.Count>0&&seen.Count<4096){ulong node=stack.Pop();if(node==head)continue;if(!Rpm.P(node)||!seen.Add(node)){malformed++;continue;}byte? nil=r.B((long)node+0x19);if(nil is null){malformed++;continue;}if(nil!=0)continue;uint? key=r.D((long)node+0x20);ulong? actor=r.Q((long)node+0x28);if(key is null||key==0||!Rpm.P(actor)){malformed++;}else{uint? actorId=r.D((long)actor!.Value+0x768);byte? type=r.B((long)actor.Value+0x7E1);if(actorId==key&&type==2&&actors.Add(actor.Value)){Position? pos=ReadPosition(r,actor.Value);double? dist=DiagnosticDistance(pos,player);result.Add(new(key.Value,type.Value,actor.Value,node,pos?.X??0,pos?.Y??0,pos?.Z??0,pos is not null,dist,ReadPosition(r,actor.Value,0xB0)));}else if(actorId!=key||type is null)malformed++;}ulong? l=r.Q((long)node),parent=r.Q((long)node+8),rr=r.Q((long)node+0x10);if(!Rpm.P(parent)){malformed++;}if(Rpm.P(l)&&l!=head)stack.Push(l!.Value);if(Rpm.P(rr)&&rr!=head)stack.Push(rr!.Value);}result.Sort((a,b)=>(a.DistanceXZ??double.MaxValue).CompareTo(b.DistanceXZ??double.MaxValue));validation=seen.Count>=4096?"node safety limit reached":malformed==0?"ok":$"structural warnings: {malformed}";return result;}
    internal static double? DiagnosticDistance(Position? mob,Position? player)=>mob is null || player is null || mob==new Position(0,0,0) || player==new Position(0,0,0)?null:MobCapture.Distance(mob,player,true);
    static Position? ReadPosition(Rpm r,ulong actor,int offset=0x70){return DecodePosition(r.Bytes((long)actor+offset,12));}
    static Position? DecodePosition(byte[]? b){if(b is null)return null;float x=BitConverter.ToSingle(b,0),y=BitConverter.ToSingle(b,4),z=BitConverter.ToSingle(b,8);return float.IsFinite(x)&&float.IsFinite(y)&&float.IsFinite(z)&&Math.Abs(x)<=1_000_000&&Math.Abs(y)<=1_000_000&&Math.Abs(z)<=1_000_000?new(x,y,z):null;}
    internal static PlayerInfo? ValidatedPlayer(Rpm r,ulong ctx,long moduleBase,PlayerXYZ.BuildProfile profile)
    {
        if(!PlayerSource.ValidateLive(r,moduleBase,profile) || r.Q((long)ctx)!=(ulong)(moduleBase+profile.CtclientgameVtableRva))return null;
        ulong? actor=r.Q((long)ctx+profile.OwnerToPlayerOffset);
        if(!Rpm.P(actor)||r.Q((long)actor!.Value)!=(ulong)(moduleBase+profile.CtclientcharVtableRva))return null;
        uint? id=r.D((long)actor.Value+0x768);byte? type=r.B((long)actor.Value+0x7E1);
        if(id is null or 0 || type!=1)return null;
        byte[]? rawA=r.Bytes((long)actor.Value+profile.CoordinateA[0],12),rawB=r.Bytes((long)actor.Value+profile.CoordinateB[0],12);
        var a=DecodePosition(rawA);var b=DecodePosition(rawB);
        if(a is null || r.Q((long)ctx+profile.OwnerToPlayerOffset)!=actor || r.D((long)actor.Value+0x768)!=id)return null;
        return new(id.Value,actor.Value,a.X,a.Y,a.Z,"PlayerXYZ profile + live signatures + owner/P vtables; A/B ayrı, sıfır mesafeye alınmaz",b,$"0x{actor.Value+(uint)profile.CoordinateA[0]:X}",$"0x{actor.Value+(uint)profile.CoordinateB[0]:X}",rawA is null?null:Convert.ToHexString(rawA),rawB is null?null:Convert.ToHexString(rawB));
    }
    internal static string PathOf(IntPtr h){var s=new StringBuilder(32768);int n=s.Capacity;if(!N.QueryFullProcessImageName(h,0,s,ref n))throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());return s.ToString();}
    internal static long Module(int pid,string image){IntPtr s=N.CreateToolhelp32Snapshot(0x18,(uint)pid);if(s==new IntPtr(-1))throw new System.ComponentModel.Win32Exception();try{var e=new ME{Size=(uint)Marshal.SizeOf<ME>()};if(N.Module32First(s,ref e))do{if(string.Equals(Path.GetFullPath(e.Path),Path.GetFullPath(image),StringComparison.OrdinalIgnoreCase))return e.Base.ToInt64();e.Size=(uint)Marshal.SizeOf<ME>();}while(N.Module32Next(s,ref e));throw new Exception("TClient module bulunamadı");}finally{N.CloseHandle(s);}}
}

sealed class Rpm(IntPtr h){public static bool P(ulong? x)=>x is>=0x10000 and<=0x7FFFFFFFFFFF;public byte[]? Bytes(long a,int n){if(a<0x10000||a>0x7FFFFFFFFFFF)return null;var b=new byte[n];return N.ReadProcessMemory(h,(IntPtr)a,b,(nuint)n,out var got)&&got==(nuint)n?b:null;}public ulong? Q(long a){var b=Bytes(a,8);return b is null?null:BitConverter.ToUInt64(b);}public uint? D(long a){var b=Bytes(a,4);return b is null?null:BitConverter.ToUInt32(b);}public byte? B(long a){var b=Bytes(a,1);return b?[0];}}
record Position(float X,float Y,float Z);
record PlayerInfo(uint EntityId,ulong ActorPtr,float X,float Y,float Z,string Status,Position? B=null,string? AAddress=null,string? BAddress=null,string? RawA=null,string? RawB=null);
record Monster(uint EntityId,byte EntityType,ulong ActorPtr,ulong NodePtr,float X,float Y,float Z,bool PositionValid,double? DistanceXZ,Position? B=null);
record Snapshot(DateTimeOffset Timestamp,string Status,string Profile,int? Pid,string? Sha256,string? ModuleBase,string? Context,string? Tree,List<Monster> Monsters,string PositionStatus,PlayerInfo? Player,string Message){public static Snapshot Disconnected(string m,int? pid=null)=>new(DateTimeOffset.Now,"DISCONNECTED","DISCONNECTED",pid,null,null,null,null,[],"UNRESOLVED",null,m);}

[StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]struct ME{public uint Size,ModuleId,ProcessId,GlobalUsage,ProcessUsage;public IntPtr Base;public uint BaseSize;public IntPtr Module;[MarshalAs(UnmanagedType.ByValTStr,SizeConst=256)]public string Name;[MarshalAs(UnmanagedType.ByValTStr,SizeConst=260)]public string Path;}
static class N{[DllImport("kernel32.dll",SetLastError=true)]public static extern IntPtr OpenProcess(uint a,bool i,int p);[DllImport("kernel32.dll",SetLastError=true)]public static extern bool ReadProcessMemory(IntPtr h,IntPtr a,[Out]byte[]b,nuint n,out nuint r);[DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]public static extern bool QueryFullProcessImageName(IntPtr h,int f,StringBuilder s,ref int n);[DllImport("kernel32.dll")]public static extern IntPtr CreateToolhelp32Snapshot(uint f,uint p);[DllImport("kernel32.dll",CharSet=CharSet.Unicode)]public static extern bool Module32First(IntPtr s,ref ME e);[DllImport("kernel32.dll",CharSet=CharSet.Unicode)]public static extern bool Module32Next(IntPtr s,ref ME e);[DllImport("kernel32.dll")]public static extern bool CloseHandle(IntPtr h);}
