#include "reader.hpp"
#include <algorithm>
#include <bcrypt.h>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <map>
#include <mutex>
#include <sstream>
#include <stdexcept>

namespace pc { namespace {
struct Image {
    std::span<const unsigned char> data;IMAGE_NT_HEADERS64 nt{};std::vector<IMAGE_SECTION_HEADER> sections;
    template<class T>T read(size_t pos)const{if(pos>data.size()||sizeof(T)>data.size()-pos)throw std::runtime_error("Truncated counter PE");T v;std::memcpy(&v,data.data()+pos,sizeof(v));return v;}
    explicit Image(std::span<const unsigned char> d):data(d){auto dos=read<IMAGE_DOS_HEADER>(0);if(dos.e_magic!=IMAGE_DOS_SIGNATURE||dos.e_lfanew<64||dos.e_lfanew>4096)throw std::runtime_error("Counter DOS identity");nt=read<IMAGE_NT_HEADERS64>(dos.e_lfanew);if(nt.Signature!=IMAGE_NT_SIGNATURE||nt.FileHeader.Machine!=IMAGE_FILE_MACHINE_AMD64||nt.OptionalHeader.Magic!=IMAGE_NT_OPTIONAL_HDR64_MAGIC||nt.FileHeader.SizeOfOptionalHeader!=sizeof(IMAGE_OPTIONAL_HEADER64)||!nt.FileHeader.NumberOfSections||nt.FileHeader.NumberOfSections>96)throw std::runtime_error("Counter PE identity");for(unsigned i=0;i<nt.FileHeader.NumberOfSections;++i){auto s=read<IMAGE_SECTION_HEADER>(size_t(dos.e_lfanew)+sizeof(nt)+i*sizeof(IMAGE_SECTION_HEADER));if(uint64_t(s.PointerToRawData)+s.SizeOfRawData>d.size()||uint64_t(s.VirtualAddress)+s.SizeOfRawData>nt.OptionalHeader.SizeOfImage)throw std::runtime_error("Counter section bounds");sections.push_back(s);}}
    size_t raw(uintptr_t rva,size_t n=1)const{for(const auto&s:sections)if(rva>=s.VirtualAddress&&rva-s.VirtualAddress<=s.SizeOfRawData&&n<=s.SizeOfRawData-(rva-s.VirtualAddress))return s.PointerToRawData+rva-s.VirtualAddress;throw std::runtime_error("Counter RVA bounds");}
    uint32_t u32(uintptr_t rva)const{return read<uint32_t>(raw(rva,4));}
    uint64_t u64(uintptr_t rva)const{return read<uint64_t>(raw(rva,8));}
    bool code(uintptr_t rva,size_t n=1)const{for(const auto&s:sections)if((s.Characteristics&IMAGE_SCN_MEM_EXECUTE)&&rva>=s.VirtualAddress&&rva-s.VirtualAddress<=s.SizeOfRawData&&n<=s.SizeOfRawData-(rva-s.VirtualAddress))return true;return false;}
    std::vector<unsigned char> bytes(uintptr_t rva,size_t n)const{auto p=raw(rva,n);return{data.begin()+p,data.begin()+p+n};}
    std::vector<uintptr_t> scan(const std::string& text)const{std::istringstream in(text);std::string word;std::vector<int> p;while(in>>word)p.push_back(word=="??"?-1:std::stoi(word,nullptr,16));std::vector<uintptr_t> hits;for(const auto&s:sections)if(s.Characteristics&IMAGE_SCN_MEM_EXECUTE)for(size_t x=0;x+p.size()<=s.SizeOfRawData;++x){bool ok=true;for(size_t i=0;i<p.size();++i)if(p[i]>=0&&data[s.PointerToRawData+x+i]!=p[i]){ok=false;break;}if(ok)hits.push_back(s.VirtualAddress+x);}return hits;}
    uintptr_t unique(const std::string& p)const{auto hits=scan(p);if(hits.size()!=1)throw std::runtime_error("Counter recovery: missing/ambiguous semantic anchor");return hits[0];}
    uintptr_t call(uintptr_t site)const{if(bytes(site,1)[0]!=0xE8)throw std::runtime_error("Counter CALL opcode");int64_t target=int64_t(site+5)+int32_t(u32(site+1));if(target<0||!code(uintptr_t(target),16))throw std::runtime_error("Counter CALL target");return uintptr_t(target);}
    bool rtti(uintptr_t table,const char* name)const{try{auto pointer=u64(table-8);if(pointer<nt.OptionalHeader.ImageBase)return false;auto col=pointer-nt.OptionalHeader.ImageBase;if(u32(col)!=1||u32(col+4)!=0||u32(col+8)!=0||u32(col+20)!=col)return false;auto td=u32(col+12);auto text=bytes(td+16,std::strlen(name)+1);return std::memcmp(text.data(),name,text.size())==0&&u64(table)>=nt.OptionalHeader.ImageBase&&code(u64(table)-nt.OptionalHeader.ImageBase);}catch(...){return false;}}
    uintptr_t table(const char* name)const{std::vector<uintptr_t> hits;for(const auto&s:sections)if(!(s.Characteristics&IMAGE_SCN_MEM_EXECUTE))for(size_t x=8;x+8<=s.SizeOfRawData;x+=8){auto rva=s.VirtualAddress+x;if(rtti(rva,name))hits.push_back(rva);}if(hits.size()!=1)throw std::runtime_error("Counter RTTI missing/ambiguous");return hits[0];}
};
const char* exitPattern="40 53 48 83 EC 20 48 8B D9 E8 ?? ?? ?? ?? E8 ?? ?? ?? ?? 48 85 DB 74 50 48 8B CB E8 ?? ?? ?? ?? 33 D2 48 8B CB E8 ?? ?? ?? ?? 48 8B CB E8 ?? ?? ?? ?? 48 8B 03 48 8B CB FF 90 ?? ?? ?? ?? 48 8D 8B ?? ?? ?? ?? 33 D2 48 8B 01 FF 50 28 48 8B CB C6 83 ?? ?? ?? ?? 01 E8 ?? ?? ?? ?? 48 8D 8B ?? ?? ?? ?? E8 ?? ?? ?? ?? 33 C0 48 83 C4 20 5B C3";
const char* getterPattern="48 8B 05 ?? ?? ?? ?? C3 CC CC CC CC CC CC CC CC 41 B0 FF 80 FA 85 77 51";
const char* countPattern="48 8B 81 ?? ?? ?? ?? 3B 90 ?? ?? ?? ?? 74 ?? 4C 8B 81 ?? ?? ?? ?? 49 8B C8 49 8B 40 08 80 78 19 00";
std::string DiskSha(std::span<const unsigned char> disk){
    BCRYPT_ALG_HANDLE algorithm=nullptr;BCRYPT_HASH_HANDLE hash=nullptr;std::array<unsigned char,32> digest{};
    if(BCryptOpenAlgorithmProvider(&algorithm,BCRYPT_SHA256_ALGORITHM,nullptr,0)<0)throw std::runtime_error("Counter SHA provider");
    auto status=BCryptCreateHash(algorithm,&hash,nullptr,0,nullptr,0,0);
    if(status>=0)status=BCryptHashData(hash,const_cast<PUCHAR>(disk.data()),ULONG(disk.size()),0);
    if(status>=0)status=BCryptFinishHash(hash,digest.data(),ULONG(digest.size()),0);
    if(hash)BCryptDestroyHash(hash);BCryptCloseAlgorithmProvider(algorithm,0);
    if(status<0)throw std::runtime_error("Counter SHA failed");
    const char* hex="0123456789ABCDEF";std::string text;for(auto b:digest){text+=hex[b>>4];text+=hex[b&15];}return text;
}
std::mutex cacheMutex;std::map<std::string,std::shared_ptr<const RecoveredProfile>> cache;
void Serialize(std::ostream& out,const RecoveredProfile& p){auto number=[&](uint64_t n){out.write(reinterpret_cast<const char*>(&n),8);};number(1);out.write(p.sha.data(),64);for(uint64_t n:{uint64_t(p.timestamp),uint64_t(p.imageSize),p.getterRva,p.rootRva,p.countOffset,p.contextVtable,p.rootVtable,p.rootDelta,p.exitRva,p.rootVirtual,p.rootSlot})number(n);number(p.guards.size());for(const auto&g:p.guards){number(g.rva);number(g.bytes.size());out.write(reinterpret_cast<const char*>(g.bytes.data()),g.bytes.size());}}
RecoveredProfile Deserialize(std::istream& in){auto number=[&](){uint64_t n=0;if(!in.read(reinterpret_cast<char*>(&n),8))throw std::runtime_error("Counter cache truncated");return n;};if(number()!=1)throw std::runtime_error("Counter cache schema");RecoveredProfile p;p.sha.resize(64);if(!in.read(p.sha.data(),64))throw std::runtime_error("Counter cache SHA");p.timestamp=uint32_t(number());p.imageSize=uint32_t(number());for(auto* v:{&p.getterRva,&p.rootRva,&p.countOffset,&p.contextVtable,&p.rootVtable,&p.rootDelta,&p.exitRva,&p.rootVirtual,&p.rootSlot})*v=number();auto count=number();if(count!=11)throw std::runtime_error("Counter cache guard count");for(size_t j=0;j<count;++j){CodeGuard g;g.rva=number();auto n=number();if(n<8||n>512)throw std::runtime_error("Counter cache guard size");g.bytes.resize(n);if(!in.read(reinterpret_cast<char*>(g.bytes.data()),n))throw std::runtime_error("Counter cache guard bytes");p.guards.push_back(std::move(g));}return p;}
}
bool ValidateRecoveredCounter(const RecoveredProfile& p,std::span<const unsigned char> disk){try{Image b(disk);if(p.sha.size()!=64||p.timestamp!=b.nt.FileHeader.TimeDateStamp||p.imageSize!=b.nt.OptionalHeader.SizeOfImage||p.guards.size()!=11||p.guards[0].rva!=p.getterRva||p.guards[0].bytes.size()!=8||p.guards[1].rva!=p.exitRva||p.guards[1].bytes.size()!=112||p.guards[2].bytes.size()!=33)return false;for(const auto&g:p.guards)if(!b.code(g.rva,g.bytes.size())||b.bytes(g.rva,g.bytes.size())!=g.bytes)return false;auto getterBytes=p.guards[0].bytes;if(getterBytes[0]!=0x48||getterBytes[1]!=0x8B||getterBytes[2]!=0x05||getterBytes[7]!=0xC3||int64_t(p.getterRva+7)+int32_t(b.u32(p.getterRva+3))!=int64_t(p.rootRva)||p.rootRva>=p.imageSize-8||b.code(p.rootRva)||p.countOffset<0x100||p.countOffset>0x10000||(p.countOffset&7)||p.countOffset!=b.u32(p.guards[2].rva+18)+8||p.rootDelta<0x100||p.rootDelta>0x4000000||p.rootSlot>=0x1000||(p.rootSlot&7)||p.rootDelta!=b.u32(p.exitRva+95)||p.rootSlot!=b.u32(p.exitRva+58)||!b.rtti(p.contextVtable,".?AVCTClientGame@@")||!b.rtti(p.rootVtable,".?AVCTClientWnd@@")||b.u64(p.rootVtable+p.rootSlot)!=b.nt.OptionalHeader.ImageBase+p.rootVirtual)return false;for(size_t i=0;i<7;++i)if(b.call(p.exitRva+std::array<uintptr_t,7>{9,14,27,37,45,87,99}[i])!=p.guards[3+i].rva)return false;return p.guards[10].rva==p.rootVirtual;}catch(...){return false;}}
std::shared_ptr<const RecoveredProfile> RecoverCounterProfile(std::span<const unsigned char> disk,const std::string& sha,std::string* error){
    try{if(DiskSha(disk)!=sha)throw std::runtime_error("Counter disk SHA mismatch");}catch(const std::exception& ex){if(error)*error=ex.what();return {};}
    std::lock_guard lock(cacheMutex);if(auto found=cache.find(sha);found!=cache.end())return found->second;
    wchar_t local[32768]{};GetEnvironmentVariableW(L"LOCALAPPDATA",local,32768);std::filesystem::path directory=std::filesystem::path(local)/L"4UnityTools"/L"Counter"/L"profiles",path=directory/(sha+".bin");
    try{std::ifstream in(path,std::ios::binary);auto saved=Deserialize(in);if(saved.sha==sha&&ValidateRecoveredCounter(saved,disk)){auto p=std::make_shared<const RecoveredProfile>(std::move(saved));cache[sha]=p;return p;}}catch(...){}
    try{Image b(disk);RecoveredProfile p;p.sha=sha;p.timestamp=b.nt.FileHeader.TimeDateStamp;p.imageSize=b.nt.OptionalHeader.SizeOfImage;p.getterRva=b.unique(getterPattern);p.rootRva=uintptr_t(int64_t(p.getterRva+7)+int32_t(b.u32(p.getterRva+3)));auto count=b.unique(countPattern);p.countOffset=b.u32(count+18)+8;p.contextVtable=b.table(".?AVCTClientGame@@");p.rootVtable=b.table(".?AVCTClientWnd@@");p.exitRva=b.unique(exitPattern);p.rootDelta=b.u32(p.exitRva+95);p.rootSlot=b.u32(p.exitRva+58);auto function=b.u64(p.rootVtable+p.rootSlot);if(function<b.nt.OptionalHeader.ImageBase)throw std::runtime_error("Counter vtable target");p.rootVirtual=uintptr_t(function-b.nt.OptionalHeader.ImageBase);p.guards={{p.getterRva,b.bytes(p.getterRva,8)},{p.exitRva,b.bytes(p.exitRva,112)},{count,b.bytes(count,33)}};for(auto offset:{9,14,27,37,45,87,99}){auto target=b.call(p.exitRva+offset);p.guards.push_back({target,b.bytes(target,16)});}p.guards.push_back({p.rootVirtual,b.bytes(p.rootVirtual,16)});if(!ValidateRecoveredCounter(p,disk))throw std::runtime_error("Counter recovery relationship mismatch");std::filesystem::create_directories(directory);auto temp=path;temp+=L".tmp";std::ofstream out(temp,std::ios::binary|std::ios::trunc);Serialize(out,p);out.flush();if(!out)throw std::runtime_error("Counter cache write");out.close();if(!MoveFileExW(temp.c_str(),path.c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH))throw std::runtime_error("Counter profile replacement failed");auto result=std::make_shared<const RecoveredProfile>(std::move(p));cache[sha]=result;return result;}catch(const std::exception& ex){if(error)*error=ex.what();return {};}
}
}
