#pragma once
#include "tracer.hpp"
#include <functional>
#include <ostream>

namespace aoe {
inline constexpr char TickPatchLimitation[]="Changing the client-side scheduler interval can increase the frequency of the periodic operation generated by the client. It does not by itself prove that a remote server will accept every generated operation as gameplay damage.";
struct TickPatchIo {
    std::function<bool(uint64_t,size_t,std::string&)> executable;
    std::function<bool(uint64_t,void*,size_t,std::string&)> read;
    std::function<bool(uint64_t,const void*,size_t,std::string&)> write;
};
TickPatchIo ProcessTickPatchIo(HANDLE process);
TickPatchExperimentState CreateTickPatchExperimentState(const TargetInfo& target,bool producerObservationAvailable);
bool ApplyTick100Patch(const TickPatchIo& io,const TargetInfo& target,TickExperiment& experiment,std::string& error);
bool RestoreTick100Patch(const TickPatchIo& io,const TargetInfo& target,TickExperiment& experiment,std::string& error);
bool TickSessionMatches(const TickExperiment& experiment,const TargetInfo& target);
void InvalidateTickSession(TickExperiment& experiment,const std::string& reason);
void RecordTickProducer(TickPatchExperimentState& experiment,bool argumentReadable,uint64_t argument9,int64_t qpc);
void WriteTickExperimentJson(std::ostream& out,const TickExperiment& experiment);
bool ExportTickExperimentJson(const std::filesystem::path& path,const TickPatchExperimentState& experiment,std::string& error);
std::string TickExperimentDetails(const TickExperiment& experiment);
}
