#include "ui_layout.hpp"
#include <algorithm>

namespace aoe {
int ScaleUi(int value,uint32_t dpi){return (value*int(dpi)+48)/96;}
UiRect MainTabBounds(int clientWidth,int clientHeight,uint32_t dpi){const int margin=ScaleUi(20,dpi),top=ScaleUi(78,dpi),bottom=ScaleUi(48,dpi);return{margin,top,std::max(1,clientWidth-2*margin),std::max(1,clientHeight-top-bottom)};}
bool RectFits(const UiRect& outer,const UiRect& inner){return inner.width>=0&&inner.height>=0&&inner.x>=outer.x&&inner.y>=outer.y&&inner.x+inner.width<=outer.x+outer.width&&inner.y+inner.height<=outer.y+outer.height;}
PageVisibility CalculatePageVisibility(int selectedTab,bool diagnosticsExpanded){return{selectedTab==0,selectedTab==1,selectedTab==2,selectedTab==2&&diagnosticsExpanded};}
TargetInspectorAvailability CalculateTargetInspectorAvailability(bool attached,bool profileValid,bool inspectorRunning,bool initialNxActive,bool transitionPending,bool prepared,const std::string& transitionError){TargetInspectorAvailability a;if(!attached){a.reason="Unavailable: TClient not attached";return a;}if(!profileValid){a.reason="Unavailable: Profile not validated";return a;}if(inspectorRunning){a.suppressAutoArm=true;a.reason="Unavailable: Inspector already running";return a;}if(transitionPending){a.suppressAutoArm=true;a.reason="Unavailable: Inspector breakpoint transition in progress";return a;}if(initialNxActive){a.prepareEnabled=true;a.suppressAutoArm=true;a.reason="Unavailable: Initial Nx currently armed — use PREPARE TARGET INSPECTOR";return a;}if(!transitionError.empty()){a.prepareEnabled=true;a.suppressAutoArm=true;a.reason="Unavailable: "+transitionError;return a;}a.startEnabled=true;a.suppressAutoArm=prepared;a.reason=prepared?"Ready: Initial Nx conflict released; START TARGET INSPECTOR":"Ready: attached, profile validated, read-only inspector available";return a;}
ResearchPageLayout CalculateResearchLayout(const UiRect& p,uint32_t dpi){const int gap=ScaleUi(8,dpi),headingH=ScaleUi(28,dpi),buttonH=ScaleUi(30,dpi);ResearchPageLayout r;r.heading={p.x,p.y,p.width,headingH};const int rowY=p.y+headingH+gap;const int buttonW=(p.width-3*gap)/4;for(int i=0;i<4;++i)r.buttons[size_t(i)]={p.x+i*(buttonW+gap),rowY,buttonW,buttonH};const int inspectorY=rowY+buttonH+ScaleUi(10,dpi);r.inspectorHeading={p.x,inspectorY,p.width,ScaleUi(22,dpi)};const int actionY=inspectorY+ScaleUi(24,dpi);const int actionW=(p.width-4*gap)/5;for(int i=0;i<5;++i)r.inspectorButtons[size_t(i)]={p.x+i*(actionW+gap),actionY,actionW,buttonH};const int prepareY=actionY+buttonH+ScaleUi(4,dpi);r.inspectorPrepare={p.x,prepareY,std::min(p.width,ScaleUi(280,dpi)),buttonH};r.inspectorStatus={r.inspectorPrepare.x+r.inspectorPrepare.width+gap,prepareY,std::max(1,p.width-r.inspectorPrepare.width-gap),ScaleUi(38,dpi)};const int listY=prepareY+r.inspectorStatus.height+ScaleUi(4,dpi);r.inspectorList={p.x,listY,p.width,ScaleUi(58,dpi)};const int lowerY=listY+r.inspectorList.height+ScaleUi(8,dpi),columnW=(p.width-gap)/2,rightX=p.x+columnW+gap,sectionHeading=ScaleUi(22,dpi);r.provenanceHeading={p.x,lowerY,columnW,sectionHeading};r.writerHeading={rightX,lowerY,columnW,sectionHeading};const int actionsY=lowerY+ScaleUi(24,dpi),smallGap=ScaleUi(4,dpi),cellW=(columnW-3*smallGap)/4;for(size_t i=0;i<r.provenanceButtons.size();++i){const int row=int(i/4),col=int(i%4);r.provenanceButtons[i]={p.x+col*(cellW+smallGap),actionsY+row*(buttonH+smallGap),cellW,buttonH};}for(size_t i=0;i<r.writerButtons.size();++i){const int row=int(i/4),col=int(i%4);r.writerButtons[i]={rightX+col*(cellW+smallGap),actionsY+row*(buttonH+smallGap),cellW,buttonH};}const int statusY=actionsY+2*buttonH+smallGap+ScaleUi(4,dpi);r.provenanceStatus={p.x,statusY,columnW,ScaleUi(48,dpi)};r.writerStatus={rightX,statusY,columnW,ScaleUi(48,dpi)};const int outputY=statusY+r.provenanceStatus.height;r.provenanceOutput={p.x,outputY,columnW,std::max(ScaleUi(48,dpi),p.y+p.height-outputY)};r.writerOutput={rightX,outputY,columnW,std::max(ScaleUi(48,dpi),p.y+p.height-outputY)};r.viewer={p.x,p.y+p.height-1,1,1};return r;}
ProfilesPageLayout CalculateProfilesLayout(const UiRect& p,uint32_t dpi){const int gap=ScaleUi(10,dpi),headingH=ScaleUi(28,dpi),summaryH=ScaleUi(104,dpi);ProfilesPageLayout r;r.heading={p.x,p.y,p.width,headingH};r.summary={p.x,p.y+headingH+gap,p.width,summaryH};const int listY=r.summary.y+r.summary.height+gap;r.list={p.x,listY,p.width,std::max(1,p.y+p.height-listY)};return r;}
PlayPageLayout CalculatePlayLayout(const UiRect& p,uint32_t dpi){const int headingH=ScaleUi(28,dpi),statusH=ScaleUi(136,dpi);PlayPageLayout r;r.heading={p.x,p.y,p.width,headingH};r.status={p.x,p.y+headingH+ScaleUi(6,dpi),p.width,statusH};const int contentY=r.status.y+r.status.height+ScaleUi(12,dpi);const int columnGap=ScaleUi(32,dpi);const int leftW=std::min(ScaleUi(440,dpi),(p.width-columnGap)/2);const int rightX=p.x+leftW+columnGap;const int rightW=std::max(1,p.x+p.width-rightX);r.initialLabel={p.x,contentY,ScaleUi(330,dpi),ScaleUi(24,dpi)};r.initialEdit={p.x+ScaleUi(340,dpi),contentY-ScaleUi(4,dpi),ScaleUi(76,dpi),ScaleUi(31,dpi)};r.initialSpin={r.initialEdit.x+r.initialEdit.width,contentY-ScaleUi(4,dpi),ScaleUi(20,dpi),ScaleUi(31,dpi)};int y=contentY+ScaleUi(42,dpi);for(auto& option:r.options){option={p.x,y,leftW,ScaleUi(28,dpi)};y+=ScaleUi(32,dpi);}r.visualStatus={p.x,y,leftW,ScaleUi(48,dpi)};y+=ScaleUi(50,dpi);r.save={p.x,y+ScaleUi(4,dpi),ScaleUi(180,dpi),ScaleUi(35,dpi)};const int rowH=ScaleUi(35,dpi),smallGap=ScaleUi(8,dpi);r.attach={rightX,contentY,ScaleUi(150,dpi),rowH};r.detach={rightX+ScaleUi(158,dpi),contentY,ScaleUi(110,dpi),rowH};r.arm={rightX,contentY+rowH+smallGap,std::min(rightW,ScaleUi(268,dpi)),ScaleUi(42,dpi)};const int actionY=r.arm.y+r.arm.height+smallGap;r.reset={rightX,actionY,ScaleUi(110,dpi),rowH};r.exportButton={rightX+ScaleUi(118,dpi),actionY,ScaleUi(150,dpi),rowH};const int advancedY=actionY+rowH+ScaleUi(10,dpi);r.advanced={rightX,advancedY,ScaleUi(200,dpi),ScaleUi(28,dpi)};const int toolsY=advancedY+ScaleUi(34,dpi);r.copy={rightX,toolsY,ScaleUi(170,dpi),ScaleUi(30,dpi)};r.freeze={rightX+ScaleUi(178,dpi),toolsY,std::max(ScaleUi(120,dpi),rightW-ScaleUi(178,dpi)),ScaleUi(30,dpi)};const int diagnosticsY=toolsY+ScaleUi(38,dpi);r.diagnostics={rightX,diagnosticsY,rightW,std::max(1,p.y+p.height-diagnosticsY)};return r;}
}

