#include "caller_trace.hpp"
#include <algorithm>
#include <cmath>
#include <iomanip>
#include <map>
#include <numeric>
#include <sstream>

namespace aoe {
namespace {
const char* Bool(bool value){return value?"true":"false";}
std::string Quote(const std::string& value){std::ostringstream out;out<<'"';for(char c:value){if(c=='"'||c=='\\')out<<'\\';out<<c;}out<<'"';return out.str();}
void Doubles(std::ostream& out,const std::vector<double>& values){out<<'[';for(size_t i=0;i<values.size();++i){if(i)out<<',';out<<std::fixed<<std::setprecision(6)<<values[i];}out<<']';}
double Median(std::vector<double> values){if(values.empty())return 0;std::sort(values.begin(),values.end());const size_t middle=values.size()/2;return values.size()%2?values[middle]:(values[middle-1]+values[middle])/2;}
}

void ClassifyCaller020A(Event& event){auto& snapshot=event.caller020A;snapshot.operation0209=snapshot.operationWord0.readable&&snapshot.operationWord0.value==0x0209;snapshot.operation020A=snapshot.operationWord0.readable&&snapshot.operationWord0.value==0x020A;snapshot.known853B10Path=event.returnInModule&&event.returnRva==Known853B10ReturnRva;}

void SnapshotCaller020A(HANDLE process,Event& event){auto& snapshot=event.caller020A;snapshot={};snapshot.captured=true;snapshot.operationPointer=event.r9;snapshot.operationWord0.width=2;if(!event.r9){snapshot.operationWord0.error=ERROR_INVALID_ADDRESS;ClassifyCaller020A(event);return;}uint16_t word=0;snapshot.operationWord0.readable=SafeRead(process,event.r9,&word,sizeof(word),snapshot.operationWord0.error);if(snapshot.operationWord0.readable){snapshot.operationWord0.value=word;snapshot.operationWord0.raw={uint8_t(word),uint8_t(word>>8)};}ClassifyCaller020A(event);}

void SnapshotCaller020AEntry(HANDLE process,const TargetInfo& target,Event& event){event.returnReadable=SafeRead(process,event.rsp,&event.returnAddress,sizeof(event.returnAddress),event.returnReadError);event.returnInModule=event.returnReadable&&event.returnAddress>=target.base&&event.returnAddress-target.base<target.size;if(event.returnInModule)event.returnRva=event.returnAddress-target.base;SnapshotCaller020A(process,event);}

std::vector<DirectCallsite> DirectCallsitesToCaller020A(){return {{0x81204,0x81209},{0x797F7A,0x797F7F},{0x7A9617,0x7A961C},{0x7C6D6D,0x7C6D72},{0x7D9268,0x7D926D},{0x7F091D,0x7F0922},{0x854049,0x85404E}};}

Caller020ASummary BuildCaller020ASummary(const Capture& capture){Caller020ASummary summary;summary.directCallsites=DirectCallsitesToCaller020A();std::map<uint64_t,Caller020AGroup> grouped;for(const auto& event:capture.events){if(!event.caller020A.operation020A)continue;++summary.operation020ACount;if(!event.returnInModule)continue;auto& group=grouped[event.returnRva];group.returnRva=event.returnRva;group.returnAddress=event.returnAddress;group.known853B10Path=event.returnRva==Known853B10ReturnRva;group.timestampsMs.push_back(event.ms);}for(auto& [rva,group]:grouped){(void)rva;group.count=group.timestampsMs.size();if(!group.timestampsMs.empty()){group.firstTimestampMs=group.timestampsMs.front();group.lastTimestampMs=group.timestampsMs.back();}for(size_t i=1;i<group.timestampsMs.size();++i)group.deltasMs.push_back(group.timestampsMs[i]-group.timestampsMs[i-1]);if(!group.deltasMs.empty()){group.meanDeltaMs=std::accumulate(group.deltasMs.begin(),group.deltasMs.end(),0.0)/group.deltasMs.size();group.medianDeltaMs=Median(group.deltasMs);const auto nearCount=std::count_if(group.deltasMs.begin(),group.deltasMs.end(),[](double delta){return std::abs(delta-1000.0)<=180.0;});group.near1000msPeriodic=group.count>=3&&double(nearCount)/group.deltasMs.size()>=0.75&&group.meanDeltaMs>=800&&group.meanDeltaMs<=1200;}summary.callerGroups.push_back(std::move(group));}std::stable_sort(summary.callerGroups.begin(),summary.callerGroups.end(),[](const auto& left,const auto& right){if(left.count!=right.count)return left.count>right.count;return left.returnRva<right.returnRva;});for(const auto& group:summary.callerGroups)if(group.near1000msPeriodic){summary.dominantPeriodicAvailable=true;summary.dominantReturnRva=group.returnRva;summary.dominantReturnAddress=group.returnAddress;break;}return summary;}

void WriteCaller020AEventJson(std::ostream& out,const Event& event){const auto& snapshot=event.caller020A;out<<"{\"captured\":"<<Bool(snapshot.captured)<<",\"operationPointer\":"<<Quote(Hex(snapshot.operationPointer))<<",\"operationWord0\":"<<(snapshot.operationWord0.readable?std::to_string(snapshot.operationWord0.value):"null")<<",\"operationWord0Hex\":"<<(snapshot.operationWord0.readable?Quote(Hex(snapshot.operationWord0.value)):"null")<<",\"operationWord0Readable\":"<<Bool(snapshot.operationWord0.readable)<<",\"operationWord0ReadError\":"<<snapshot.operationWord0.error<<",\"operation0209\":"<<Bool(snapshot.operation0209)<<",\"operation020A\":"<<Bool(snapshot.operation020A)<<",\"known853B10Path\":"<<Bool(snapshot.known853B10Path)<<'}';}

void WriteCaller020ASummaryJson(std::ostream& out,const Caller020ASummary& summary){out<<"{\"operation020ACount\":"<<summary.operation020ACount<<",\"dominantPeriodicCaller\":";if(summary.dominantPeriodicAvailable)out<<"{\"returnRva\":"<<Quote(Hex(summary.dominantReturnRva))<<",\"returnAddress\":"<<Quote(Hex(summary.dominantReturnAddress))<<",\"known853B10Path\":"<<Bool(summary.dominantReturnRva==Known853B10ReturnRva)<<'}';else out<<"null";out<<",\"callerGroups\":[";for(size_t i=0;i<summary.callerGroups.size();++i){if(i)out<<',';const auto& group=summary.callerGroups[i];out<<"{\"returnRva\":"<<Quote(Hex(group.returnRva))<<",\"returnAddress\":"<<Quote(Hex(group.returnAddress))<<",\"count\":"<<group.count<<",\"timestamps\":";Doubles(out,group.timestampsMs);out<<",\"deltas\":";Doubles(out,group.deltasMs);out<<",\"firstTimestamp\":"<<std::fixed<<std::setprecision(6)<<group.firstTimestampMs<<",\"lastTimestamp\":"<<group.lastTimestampMs<<",\"meanDelta\":"<<group.meanDeltaMs<<",\"medianDelta\":"<<group.medianDeltaMs<<",\"near1000msPeriodic\":"<<Bool(group.near1000msPeriodic)<<",\"known853B10Path\":"<<Bool(group.known853B10Path)<<'}';}out<<"],\"directCallsites\":[";for(size_t i=0;i<summary.directCallsites.size();++i){if(i)out<<',';out<<"{\"callRva\":"<<Quote(Hex(summary.directCallsites[i].callRva))<<",\"returnRva\":"<<Quote(Hex(summary.directCallsites[i].returnRva))<<'}';}out<<"],\"limitation\":"<<Quote(Caller020ALimitation)<<'}';}

std::string Caller020AEventDetails(const Event& event){const auto& snapshot=event.caller020A;std::ostringstream out;out<<"Time "<<event.ms<<" ms  thread "<<event.threadId<<"  RIP "<<Hex(event.rip)<<"\r\nRSP "<<Hex(event.rsp)<<"  RCX "<<Hex(event.rcx)<<"  RDX "<<Hex(event.rdx)<<"  R8 "<<Hex(event.r8)<<"  R9 "<<Hex(event.r9)<<"\r\noperationWord0 "<<(snapshot.operationWord0.readable?Hex(snapshot.operationWord0.value):"unreadable (Win32 "+std::to_string(snapshot.operationWord0.error)+")")<<"  operation0209="<<Bool(snapshot.operation0209)<<"  operation020A="<<Bool(snapshot.operation020A)<<"\r\nreturn "<<(event.returnInModule?"TClient.exe+"+Hex(event.returnRva)+" | "+Hex(event.returnAddress):event.returnReadable?Hex(event.returnAddress)+" (outside TClient.exe)":"unreadable")<<"  known853B10Path="<<Bool(snapshot.known853B10Path)<<"\r\n"<<Caller020ALimitation;return out.str();}

std::string Caller020ASummaryText(const Caller020ASummary& summary,uint64_t moduleBase){std::ostringstream out;out<<"0x020A caller summary\r\n0x020A events: "<<summary.operation020ACount<<"\r\n";for(size_t i=0;i<summary.callerGroups.size();++i){const auto& group=summary.callerGroups[i];out<<"\r\nCaller group "<<i+1<<":\r\nreturn = TClient.exe+"<<std::hex<<std::uppercase<<group.returnRva<<" | "<<Hex(group.returnAddress)<<std::dec<<"\r\ncount = "<<group.count<<"; first = "<<group.firstTimestampMs<<" ms; last = "<<group.lastTimestampMs<<" ms\r\nmean delta = "<<group.meanDeltaMs<<" ms; median delta = "<<group.medianDeltaMs<<" ms; near 1000 ms = "<<Bool(group.near1000msPeriodic)<<"; known853B10Path = "<<Bool(group.known853B10Path)<<"\r\ntimestamps = ";for(double timestamp:group.timestampsMs)out<<timestamp<<" ";out<<"\r\ndeltas = ";for(double delta:group.deltasMs)out<<delta<<" ";out<<"\r\n";}out<<"\r\nDominant periodic 0x020A caller: ";if(!summary.dominantPeriodicAvailable)out<<"not established";else{out<<"TClient.exe+"<<std::hex<<std::uppercase<<summary.dominantReturnRva<<" | "<<Hex(summary.dominantReturnAddress)<<std::dec<<"\r\n";if(summary.dominantReturnRva==Known853B10ReturnRva)out<<"The +853B10 path is runtime-confirmed, but another gate inside or above that path must still enforce the approximately one-second producer cadence.";else out<<"+854049 was not the runtime periodic caller; the observed periodic return RVA is TClient.exe+"<<std::hex<<std::uppercase<<summary.dominantReturnRva<<std::dec<<".";}out<<"\r\n\r\nStatically verified direct CALLs to TClient.exe+7BB160:\r\n";for(const auto& callsite:summary.directCallsites)out<<"call TClient.exe+"<<std::hex<<std::uppercase<<callsite.callRva<<" | "<<Hex(moduleBase+callsite.callRva)<<"  return TClient.exe+"<<callsite.returnRva<<" | "<<Hex(moduleBase+callsite.returnRva)<<"\r\n";out<<std::dec<<Caller020ALimitation;return out.str();}
}
