#include "initial_2x.hpp"
#include <fstream>
#include <iomanip>
#include <locale>
#include <sstream>

namespace aoe {
namespace {
std::string Quote(const std::string& value){std::ostringstream out;out<<'"';for(unsigned char c:value){switch(c){case '"':out<<"\\\"";break;case '\\':out<<"\\\\";break;case '\n':out<<"\\n";break;case '\r':out<<"\\r";break;case '\t':out<<"\\t";break;default:if(c<0x20)out<<"\\u"<<std::hex<<std::setw(4)<<std::setfill('0')<<unsigned(c)<<std::dec;else out<<char(c);}}out<<'"';return out.str();}
const char* Bool(bool value){return value?"true":"false";}
std::string Number(double value){std::ostringstream out;out.imbue(std::locale::classic());out<<std::fixed<<std::setprecision(3)<<value;return out.str();}
double RelativeMs(const Initial2xExperiment& e,int64_t qpc){return e.frequency>0?double(qpc-e.armQpc)*1000.0/double(e.frequency):0;}
void CallJson(std::ostream& out,const InitialCallSnapshot& c,bool full){out<<"{\"observed\":"<<Bool(c.observed)<<",\"timestamp\":"<<Number(c.timestampMs)<<",\"threadId\":"<<c.threadId;if(full)out<<",\"rsp\":"<<Quote(Hex(c.rsp))<<",\"r12\":"<<Quote(Hex(c.r12))<<",\"r13\":"<<Quote(Hex(c.r13))<<",\"r14\":"<<Quote(Hex(c.r14))<<",\"r15\":"<<Quote(Hex(c.r15))<<",\"rsi\":"<<Quote(Hex(c.rsi))<<",\"rdi\":"<<Quote(Hex(c.rdi))<<",\"r9\":"<<Quote(Hex(c.r9));out<<",\"operationWord0\":"<<Quote(Hex(c.operationWord0))<<'}';}
void Series(std::ostream& out,const std::vector<double>& values){out<<'[';for(size_t i=0;i<values.size();++i){if(i)out<<',';out<<Number(values[i]);}out<<']';}
bool AllMatched(const InitialReturnValidation& v){return v.rspMatched&&v.r12Matched&&v.r13Matched&&v.r14Matched&&v.r15Matched&&v.rsiMatched&&v.rdiMatched;}
void RecordCallTime(Initial2xExperiment& e,InitialCallSnapshot& call){call.timestampMs=RelativeMs(e,call.qpc);if(!e.initialCallTimestamps.empty())e.initialCallIntervalsMs.push_back(call.timestampMs-e.initialCallTimestamps.back());e.initialCallTimestamps.push_back(call.timestampMs);if(e.initialCallTimestamps.size()>1)e.initialCallDeltaMs=e.initialCallTimestamps[1]-e.initialCallTimestamps[0];}
}

bool ValidInitialCallCount(uint32_t value){return value>=MinInitialCalls&&value<=MaxInitialCalls;}
bool ParseInitialCallCount(const std::wstring& text,uint32_t& value){if(text.empty())return false;uint64_t parsed=0;for(wchar_t c:text){if(c<L'0'||c>L'9')return false;parsed=parsed*10+uint64_t(c-L'0');if(parsed>MaxInitialCalls)return false;}if(!ValidInitialCallCount(uint32_t(parsed)))return false;value=uint32_t(parsed);return true;}
Initial2xExperiment CreateInitial2xExperiment(const TargetInfo& target,bool producerAvailable,uint32_t targetCalls,AoeSkillFamily family,uint64_t prep,uint64_t returned){Initial2xExperiment e;e.skillFamily=family;const auto&r=target.runtime;if(r.workerEntryCoverage&&(!prep||!returned||!((prep==r.initialPrepRva&&returned==r.initialReturnRva)||(prep==r.alternateInitialPrepRva&&returned==r.alternateInitialReturnRva))))return e;if(family==AoeSkillFamily::Unknown||!ValidInitialCallCount(targetCalls)||!r.initialNxAvailable)return e;e.phase=Initial2xPhase::Waiting0209;e.armed=true;e.targetInitialCalls=targetCalls;e.producerObservationAvailable=producerAvailable;e.pid=target.pid;e.creationTime=target.creationTime;e.moduleBase=target.base;e.redirectTargetRva=prep?prep:r.initialPrepRva;e.expectedReturnRva=returned;e.imageSha256=target.image.sha256;e.armQpc=QpcNow();e.frequency=QpcFrequency();e.armTimestamp=UtcNow();return e;}
bool Initial2xSessionMatches(const Initial2xExperiment& e,const TargetInfo& t){const auto&r=t.runtime;const bool route=r.workerEntryCoverage?((e.redirectTargetRva==r.initialPrepRva&&e.expectedReturnRva==r.initialReturnRva)||(e.redirectTargetRva==r.alternateInitialPrepRva&&e.expectedReturnRva==r.alternateInitialReturnRva)):e.redirectTargetRva==r.initialPrepRva;return e.armed&&ValidInitialCallCount(e.targetInitialCalls)&&t.verified&&r.initialNxAvailable&&e.pid==t.pid&&e.creationTime==t.creationTime&&e.moduleBase==t.base&&e.imageSha256==t.image.sha256&&route;}
void AbortInitial2x(Initial2xExperiment& e,const std::string& reason){if(e.completed)return;e.phase=Initial2xPhase::Aborted;e.aborted=true;e.completed=false;e.repeatPending=false;e.replayInProgress=false;e.awaitingReplayedCall=false;e.redirectClaimed=false;e.abortReason=reason;}
InitialCallAction ObserveInitialCall(Initial2xExperiment& e,const InitialCallSnapshot& input){
    if(!e.armed||e.completed||e.aborted)return InitialCallAction::Ignore;
    if(input.ownershipRequired&&!input.ownershipVerified)return InitialCallAction::Ignore;
    if(input.operationReadable&&input.operationWord0==SkillContract(e.skillFamily).initial&&input.ownershipRequired&&(input.prepRva!=e.redirectTargetRva||input.returnRva!=e.expectedReturnRva)){AbortInitial2x(e,"AOE preparation route changed; normal validation required.");return InitialCallAction::Aborted;}
    if(input.operationReadable&&ClassifyOperationWord(input.operationWord0).classification==OperationClassification::Initial0209&&OperationSkillFamily(input.operationWord0)!=e.skillFamily){AbortInitial2x(e,"AOE skill changed; a new normal validation cast is required before ARM.");return InitialCallAction::Aborted;}
    if(e.phase==Initial2xPhase::Waiting0209){if(!input.operationReadable||input.operationWord0!=SkillContract(e.skillFamily).initial)return InitialCallAction::Ignore;e.firstInitialCall=input;e.firstInitialCall.observed=true;e.firstInitialCall.operation0209=true;RecordCallTime(e,e.firstInitialCall);e.firstThreadId=input.threadId;e.initialCallsObserved=1;e.repeatPending=true;e.phase=Initial2xPhase::WaitingFirstReturn;return InitialCallAction::FirstAccepted;}
    if(e.phase==Initial2xPhase::ReplayingSecondCall&&e.awaitingReplayedCall){if(input.threadId!=e.firstThreadId)return InitialCallAction::Ignore;if(!input.operationReadable||input.operationWord0!=SkillContract(e.skillFamily).initial){AbortInitial2x(e,"Replayed preparation did not produce the validated initial AOE skill.");return InitialCallAction::Aborted;}if(e.initialCallsObserved>=e.targetInitialCalls){AbortInitial2x(e,"Initial-call limit would be exceeded.");return InitialCallAction::Aborted;}InitialCallSnapshot call=input;call.observed=true;call.operation0209=true;RecordCallTime(e,call);++e.initialCallsObserved;e.awaitingReplayedCall=false;e.repeatPending=true;if(e.initialCallsObserved==2)e.secondInitialCall=call;return InitialCallAction::SecondObserved;}
    return InitialCallAction::Ignore;
}
InitialReturnAction ObserveInitialReturn(Initial2xExperiment& e,uint32_t tid,uint64_t rsp,uint64_t r12,uint64_t r13,uint64_t r14,uint64_t r15,uint64_t rsi,uint64_t rdi,uint64_t rbp){
    if(!e.armed||e.completed||e.aborted||tid!=e.firstThreadId||!e.repeatPending)return InitialReturnAction::Ignore;
    auto& v=e.returnValidation;v={};v.performed=true;v.rspMatched=rsp==e.firstInitialCall.rsp;v.r12Matched=r12==e.firstInitialCall.r12;v.r13Matched=r13==e.firstInitialCall.r13;v.r14Matched=r14==e.firstInitialCall.r14;v.r15Matched=r15==e.firstInitialCall.r15;v.rsiMatched=rsi==e.firstInitialCall.rsi;v.rdiMatched=rdi==e.firstInitialCall.rdi;
    if(!AllMatched(v)||(e.firstInitialCall.ownershipRequired&&rbp!=e.firstInitialCall.rbp)){++e.returnValidationsFailed;AbortInitial2x(e,"A return did not preserve RSP and all required nonvolatile preparation registers.");return InitialReturnAction::Aborted;}
    ++e.returnValidationsPassed;e.repeatPending=false;
    if(e.initialCallsObserved==e.targetInitialCalls){e.replayInProgress=false;e.completed=true;e.phase=Initial2xPhase::Completed;return InitialReturnAction::Completed;}
    if(e.initialCallsObserved>e.targetInitialCalls||e.redirectsPerformed>=e.targetInitialCalls-1||e.redirectClaimed){AbortInitial2x(e,"Strict initial-call redirect bound rejected another replay.");return InitialReturnAction::Aborted;}
    e.redirectClaimed=true;e.replayInProgress=true;e.phase=Initial2xPhase::ReplayingSecondCall;return InitialReturnAction::Redirect;
}
void CommitInitialRedirect(Initial2xExperiment& e,bool success,const std::string& error){if(!e.redirectClaimed)return;if(!success){AbortInitial2x(e,error.empty()?"SetThreadContext failed before the replay could start.":error);return;}if(e.redirectsPerformed>=e.targetInitialCalls-1){AbortInitial2x(e,"Strict redirect maximum was reached before commit.");return;}++e.redirectsPerformed;e.redirectCount=e.redirectsPerformed;e.ripRedirectPerformed=e.redirectsPerformed>0;e.redirectClaimed=false;e.awaitingReplayedCall=true;}
void InvalidateInitial2xSession(Initial2xExperiment& e,const std::string& reason){if(e.armed&&!e.completed)AbortInitial2x(e,reason);e.armed=false;e.repeatPending=false;e.replayInProgress=false;e.awaitingReplayedCall=false;e.pid=0;e.creationTime=0;e.moduleBase=0;e.imageSha256.clear();}
void RecordInitial2xProducer(Initial2xExperiment& e,bool readable,uint64_t operation,int64_t qpc){if(!e.armed||e.completed||e.aborted||!e.producerObservationAvailable)return;if(!readable){++e.producerOtherCount;return;}const double ms=RelativeMs(e,qpc);if(operation==SkillContract(e.skillFamily).initial){++e.producer0209Count;e.producer0209Timestamps.push_back(ms);}else if(operation==SkillContract(e.skillFamily).periodic){++e.producer020ACount;if(!e.producer020ATimestamps.empty())e.producer020ADeltas.push_back(ms-e.producer020ATimestamps.back());e.producer020ATimestamps.push_back(ms);}else ++e.producerOtherCount;}
std::string Initial2xStateName(const Initial2xExperiment& e){if(e.aborted)return "ABORTED";if(e.completed)return "COMPLETED - "+std::to_string(e.initialCallsObserved)+" / "+std::to_string(e.targetInitialCalls);if(e.initialCallsObserved)return "RUNNING - "+std::to_string(e.initialCallsObserved)+" / "+std::to_string(e.targetInitialCalls);if(e.armed)return "ARMED - TARGET "+std::to_string(e.targetInitialCalls)+"x";return "NOT ARMED";}
std::string Initial2xDetails(const Initial2xExperiment& e){std::ostringstream out;out<<"AOE skill: "<<SkillContract(e.skillFamily).name<<"\r\nAOE INITIAL Nx\r\n"<<Initial2xStateName(e)<<"\r\n\r\nTarget initial calls: "<<e.targetInitialCalls<<"\r\nObserved initial AOE calls: "<<e.initialCallsObserved<<"\r\nRIP redirects performed: "<<e.redirectsPerformed<<"\r\nInitial calls: "<<e.initialCallsObserved<<" / "<<e.targetInitialCalls<<"\r\n\r\nProducer observation: "<<(e.producerObservationAvailable?"AVAILABLE":"UNAVAILABLE")<<"\r\nInitial count: "<<e.producer0209Count<<"\r\nPeriodic count: "<<e.producer020ACount<<"\r\nother count: "<<e.producerOtherCount;if(!e.abortReason.empty())out<<"\r\n\r\nAbort reason: "<<e.abortReason;out<<"\r\n\r\n"<<Initial2xLimitation;return out.str();}
void WriteInitial2xJson(std::ostream& out,const Initial2xExperiment& e){out<<"{\"mode\":\"AOE Initial Nx\",\"pid\":"<<e.pid<<",\"skill\":"<<Quote(SkillContract(e.skillFamily).name)<<",\"initialOperation\":"<<SkillContract(e.skillFamily).initial<<",\"periodicOperation\":"<<SkillContract(e.skillFamily).periodic<<",\"creationTime\":"<<Quote(std::to_string(e.creationTime))<<",\"imageSha256\":"<<Quote(e.imageSha256)<<",\"moduleBase\":"<<Quote(Hex(e.moduleBase))<<",\"armed\":"<<Bool(e.armed)<<",\"configuredInitialCalls\":"<<e.targetInitialCalls<<",\"initialCallsObserved\":"<<e.initialCallsObserved<<",\"redirectsPerformed\":"<<e.redirectsPerformed<<",\"maximumCallLimit\":"<<MaxInitialCalls<<",\"completed\":"<<Bool(e.completed)<<",\"aborted\":"<<Bool(e.aborted)<<",\"abortReason\":"<<Quote(e.abortReason)<<",\"firstThreadId\":"<<e.firstThreadId<<",\"initialCallTimestamps\":";Series(out,e.initialCallTimestamps);out<<",\"initialCallIntervalsMs\":";Series(out,e.initialCallIntervalsMs);out<<",\"returnValidation\":{\"passed\":"<<e.returnValidationsPassed<<",\"failed\":"<<e.returnValidationsFailed<<",\"rspMatched\":"<<Bool(e.returnValidation.rspMatched)<<",\"r12Matched\":"<<Bool(e.returnValidation.r12Matched)<<",\"r13Matched\":"<<Bool(e.returnValidation.r13Matched)<<",\"r14Matched\":"<<Bool(e.returnValidation.r14Matched)<<",\"r15Matched\":"<<Bool(e.returnValidation.r15Matched)<<",\"rsiMatched\":"<<Bool(e.returnValidation.rsiMatched)<<",\"rdiMatched\":"<<Bool(e.returnValidation.rdiMatched)<<"},\"firstInitialCall\":";CallJson(out,e.firstInitialCall,true);out<<",\"ripRedirectPerformed\":"<<Bool(e.ripRedirectPerformed)<<",\"redirectTargetRva\":"<<Quote(Hex(e.redirectTargetRva))<<",\"producerObservationAvailable\":"<<Bool(e.producerObservationAvailable)<<",\"producer0209Count\":"<<e.producer0209Count<<",\"producer020ACount\":"<<e.producer020ACount<<",\"producerOtherCount\":"<<e.producerOtherCount<<",\"producer0209Timestamps\":";Series(out,e.producer0209Timestamps);out<<",\"producer020ATimestamps\":";Series(out,e.producer020ATimestamps);out<<",\"producer020ADeltas\":";Series(out,e.producer020ADeltas);out<<",\"limitation\":"<<Quote(Initial2xLimitation)<<'}';}
bool ExportInitial2xJson(const std::filesystem::path& path,const Initial2xExperiment& e,std::string& error){try{if(!e.armed){error="No armed AOE Initial Nx experiment is available for export.";return false;}if(!path.parent_path().empty())std::filesystem::create_directories(path.parent_path());std::ofstream output(path,std::ios::binary|std::ios::trunc);if(!output){error="Cannot open JSON destination: "+path.string();return false;}output.imbue(std::locale::classic());WriteInitial2xJson(output,e);output<<'\n';if(!output){error="Failed while writing Initial Nx JSON.";return false;}error.clear();return true;}catch(const std::exception& ex){error=std::string("Initial Nx JSON export failed: ")+ex.what();return false;}}
}
