#include "live_validation.hpp"
#include <sstream>

namespace aoe {
namespace {
bool RegistersMatch(const InitialCallSnapshot& call,uint64_t rsp,uint64_t r12,uint64_t r13,uint64_t r14,uint64_t r15,uint64_t rsi,uint64_t rdi){return call.rsp==rsp&&call.r12==r12&&call.r13==r13&&call.r14==r14&&call.r15==r15&&call.rsi==rsi&&call.rdi==rdi;}
const char* YesNo(bool value){return value?"YES":"NO";}
}

std::string LiveValidationProfileIdentity(const BuildProfile& profile){std::ostringstream out;out<<profile.targetSha256<<':'<<profile.schemaVersion<<':'<<Hex(profile.runtime.initialPrepRva)<<':'<<Hex(profile.runtime.initialCallRva)<<':'<<Hex(profile.runtime.initialReturnRva)<<':'<<Hex(profile.runtime.sharedWorkerRva)<<':'<<Hex(profile.runtime.producerCallRva)<<':'<<Hex(profile.runtime.producerRva);return out.str();}
bool LiveValidationSessionMatches(const LiveValidationState& state,const TargetInfo& target,const std::string& profileIdentity){return state.pid&&state.pid==target.pid&&state.creationTime==target.creationTime&&state.targetSha256==target.image.sha256&&state.profileIdentity==profileIdentity;}
bool EnsureLiveValidationSession(LiveValidationState& state,const TargetInfo& target,const std::string& profileIdentity){if(LiveValidationSessionMatches(state,target,profileIdentity)){state.moduleBase=target.base;return false;}state={};state.pid=target.pid;state.creationTime=target.creationTime;state.moduleBase=target.base;state.targetSha256=target.image.sha256;state.profileIdentity=profileIdentity;RecomputeLiveValidation(state);return true;}
void MarkLiveProfileFingerprintsPassed(LiveValidationState& state){state.profileFingerprintsPassed=true;RecomputeLiveValidation(state);}
void ObserveLivePrep(LiveValidationState& state,uint32_t,int64_t){state.seenPrepAnchor=true;++state.prepHitCount;RecomputeLiveValidation(state);}
void ObserveLiveCall(LiveValidationState& state,const OperationObservation& operation,const InitialCallSnapshot* registers){state.seenCallAnchor=true;++state.callHitCount;if(!operation.operationReadable){++state.unreadableOperationCount;RecomputeLiveValidation(state);return;}switch(operation.classification){case OperationClassification::Initial0209:state.seenInitial0209=true;++state.initial0209Count;state.validationCastInProgress=true;if(registers){state.validationInitialCall=*registers;state.pendingThreadId=registers->threadId;state.pendingClassification=operation.classification;state.awaitingReturn=true;state.pendingRegisterValidation=true;state.registerSemanticsValid=false;state.registerFailureReason.clear();}break;case OperationClassification::Periodic020A:state.seenPeriodic020A=true;++state.periodic020ACount;if(registers){state.pendingThreadId=registers->threadId;state.pendingClassification=operation.classification;state.awaitingReturn=true;state.pendingRegisterValidation=false;}break;case OperationClassification::Other:++state.otherOperationCount;break;default:++state.unreadableOperationCount;break;}RecomputeLiveValidation(state);}
void ObserveLiveReturn(LiveValidationState& state,uint32_t threadId,uint64_t rsp,uint64_t r12,uint64_t r13,uint64_t r14,uint64_t r15,uint64_t rsi,uint64_t rdi){state.seenReturnAnchor=true;++state.returnHitCount;if(state.awaitingReturn&&threadId==state.pendingThreadId){if(state.pendingClassification==OperationClassification::Initial0209&&state.pendingRegisterValidation){state.registerSemanticsValid=RegistersMatch(state.validationInitialCall,rsp,r12,r13,r14,r15,rsi,rdi);state.registerFailureReason=state.registerSemanticsValid?std::string{}:"Initial return did not preserve RSP and required nonvolatile registers.";}else if(state.pendingClassification==OperationClassification::Periodic020A)++state.periodic020AReturnCount;state.awaitingReturn=false;state.pendingRegisterValidation=false;state.pendingClassification=OperationClassification::Unreadable;}RecomputeLiveValidation(state);}
void ObserveLiveProducer(LiveValidationState& state,const OperationObservation& operation){if(!operation.operationReadable){++state.producerUnreadableCount;return;}switch(operation.classification){case OperationClassification::Initial0209:++state.producer0209Count;break;case OperationClassification::Periodic020A:++state.producer020ACount;break;default:++state.producerOtherCount;break;}}
void RecomputeLiveValidation(LiveValidationState& state){if(state.replayCriticalValidationPassed){state.validationCastComplete=true;state.validationCastInProgress=false;state.blockingReason.clear();return;}const bool periodicComplete=state.periodic020ACount>=RequiredPeriodic020AForLiveValidation&&state.periodic020AReturnCount>=RequiredPeriodic020AForLiveValidation;const bool passed=state.profileFingerprintsPassed&&state.seenPrepAnchor&&state.seenCallAnchor&&state.seenReturnAnchor&&state.seenInitial0209&&state.seenPeriodic020A&&state.registerSemanticsValid&&periodicComplete;if(passed){state.replayCriticalValidationPassed=true;state.validationCastComplete=true;state.validationCastInProgress=false;state.blockingReason.clear();return;}if(!state.profileFingerprintsPassed)state.blockingReason="Profile fingerprints not validated";else if(!state.seenPrepAnchor)state.blockingReason="Preparation anchor not yet observed";else if(!state.seenCallAnchor)state.blockingReason="Shared call anchor not yet observed";else if(!state.seenInitial0209)state.blockingReason="Initial 0x0209 not yet observed";else if(!state.seenReturnAnchor)state.blockingReason="Initial return anchor not yet observed";else if(!state.registerSemanticsValid)state.blockingReason=state.registerFailureReason.empty()?"Initial return register semantics not yet validated":state.registerFailureReason;else if(!state.seenPeriodic020A)state.blockingReason="Periodic 0x020A not yet observed";else if(state.periodic020ACount<RequiredPeriodic020AForLiveValidation)state.blockingReason="Waiting for periodic 0x020A observations ("+std::to_string(state.periodic020ACount)+" / "+std::to_string(RequiredPeriodic020AForLiveValidation)+")";else state.blockingReason="Waiting for periodic 0x020A returns ("+std::to_string(state.periodic020AReturnCount)+" / "+std::to_string(RequiredPeriodic020AForLiveValidation)+")";}
bool CanArmInitialNxFromValidation(const LiveValidationState& state,const TargetInfo& target,const std::string& profileIdentity){return LiveValidationSessionMatches(state,target,profileIdentity)&&state.replayCriticalValidationPassed&&state.validationCastComplete;}
bool ShouldAutoArmAfterValidation(const LiveValidationState& state,bool configuredAutoArm,bool alreadyArmed,bool validationRequired){return configuredAutoArm&&!alreadyArmed&&(!validationRequired||state.replayCriticalValidationPassed);}
std::string LiveValidationDetails(const LiveValidationState& state,bool configuredAutoArm,bool runtimeArmed,bool validationRequired){std::ostringstream out;out<<"LIVE VALIDATION:\r\nProfile fingerprints: "<<YesNo(state.profileFingerprintsPassed)<<"\r\nPrep observed: "<<YesNo(state.seenPrepAnchor)<<"\r\nCall observed: "<<YesNo(state.seenCallAnchor)<<"\r\nInitial 0x0209 observed: "<<YesNo(state.seenInitial0209)<<" (count="<<state.initial0209Count<<")\r\nReturn observed: "<<YesNo(state.seenReturnAnchor)<<"\r\nRegister semantics: "<<(state.registerSemanticsValid?"PASS":"WAITING")<<"\r\nPeriodic 0x020A observed: "<<YesNo(state.seenPeriodic020A)<<" (calls="<<state.periodic020ACount<<" / "<<RequiredPeriodic020AForLiveValidation<<", returns="<<state.periodic020AReturnCount<<" / "<<RequiredPeriodic020AForLiveValidation<<")\r\nReplay-critical validation: "<<(state.replayCriticalValidationPassed?"PASS":"WAITING")<<"\r\nBlocking reason: "<<(state.blockingReason.empty()?"none":state.blockingReason)<<"\r\n\r\nOPERATION OBSERVATION (shared call):\r\n0x0209 count: "<<state.initial0209Count<<"\r\n0x020A count: "<<state.periodic020ACount<<"\r\nother count: "<<state.otherOperationCount<<"\r\n\r\nPRODUCER BREAKPOINT OBSERVATION (+99240 path):\r\n0x0209 count: "<<state.producer0209Count<<"\r\n0x020A count: "<<state.producer020ACount<<"\r\nother count: "<<state.producerOtherCount<<"\r\n\r\nAUTO ARM:\r\nConfigured: "<<(configuredAutoArm?"ON":"OFF")<<"\r\nEligible: "<<YesNo(!validationRequired||state.replayCriticalValidationPassed)<<"\r\n\r\nINITIAL Nx:\r\n"<<(runtimeArmed?"ARMED FOR NEXT CAST":state.replayCriticalValidationPassed?"VALIDATED; WAITING FOR ARM":"WAITING FOR LIVE VALIDATION");return out.str();}
}
