#include "live_validation.hpp"
#include <sstream>

namespace aoe {
namespace {
bool RegistersMatch(const InitialCallSnapshot& call,uint64_t rsp,uint64_t r12,uint64_t r13,uint64_t r14,uint64_t r15,uint64_t rsi,uint64_t rdi){return call.rsp==rsp&&call.r12==r12&&call.r13==r13&&call.r14==r14&&call.r15==r15&&call.rsi==rsi&&call.rdi==rdi;}
const char* YesNo(bool value){return value?"YES":"NO";}
}

std::string LiveValidationProfileIdentity(const BuildProfile& profile){std::ostringstream out;out<<profile.targetSha256<<':'<<profile.schemaVersion<<':'<<Hex(profile.runtime.initialPrepRva)<<':'<<Hex(profile.runtime.initialCallRva)<<':'<<Hex(profile.runtime.initialReturnRva)<<':'<<Hex(profile.runtime.sharedWorkerRva)<<':'<<Hex(profile.runtime.producerCallRva)<<':'<<Hex(profile.runtime.producerRva);return out.str();}
bool LiveValidationSessionMatches(const LiveValidationState& state,const TargetInfo& target,const std::string& profileIdentity){return state.pid&&state.pid==target.pid&&state.creationTime==target.creationTime&&state.targetSha256==target.image.sha256&&state.profileIdentity==profileIdentity;}
bool EnsureLiveValidationSession(LiveValidationState& state,const TargetInfo& target,const std::string& profileIdentity){if(LiveValidationSessionMatches(state,target,profileIdentity)){state.moduleBase=target.base;return false;}state={};state.pid=target.pid;state.creationTime=target.creationTime;state.moduleBase=target.base;state.targetSha256=target.image.sha256;state.profileIdentity=profileIdentity;RecomputeLiveValidation(state);return true;}
void MarkLiveProfileFingerprintsPassed(LiveValidationState& state){state.profileFingerprintsPassed=true;RecomputeLiveValidation(state);}
bool BindLiveSkillFamily(LiveValidationState& s,AoeSkillFamily family){
    if(family==AoeSkillFamily::Unknown||s.skillFamily==family)return false;
    // Code/session identity stays valid; gameplay proof belongs to one skill.
    s.skillFamily=family;s.seenInitial0209=false;s.seenPeriodic020A=false;
    s.registerSemanticsValid=false;s.replayCriticalValidationPassed=false;
    s.validationCastInProgress=false;s.validationCastComplete=false;
    s.awaitingReturn=false;s.pendingRegisterValidation=false;s.pendingThreadId=0;
    s.pendingClassification=OperationClassification::Unreadable;
    s.initial0209Count=0;s.periodic020ACount=0;s.periodic020AReturnCount=0;
    s.producer0209Count=0;s.producer020ACount=0;s.producerOtherCount=0;s.producerUnreadableCount=0;
    s.validationInitialCall={};s.registerFailureReason.clear();RecomputeLiveValidation(s);return true;
}
void ObserveLivePrep(LiveValidationState& state,uint32_t,int64_t){state.seenPrepAnchor=true;++state.prepHitCount;RecomputeLiveValidation(state);}
void ObserveLiveCall(LiveValidationState& state,const OperationObservation& operation,const InitialCallSnapshot* registers){if(registers&&registers->ownershipRequired&&!registers->ownershipVerified){++state.otherOperationCount;return;}state.seenCallAnchor=true;++state.callHitCount;if(!operation.operationReadable){++state.unreadableOperationCount;RecomputeLiveValidation(state);return;}
if(operation.family!=AoeSkillFamily::Unknown){
    if(state.skillFamily==AoeSkillFamily::Unknown||operation.classification==OperationClassification::Initial0209)BindLiveSkillFamily(state,operation.family);
    if(operation.family!=state.skillFamily){++state.otherOperationCount;RecomputeLiveValidation(state);return;}
}
switch(operation.classification){case OperationClassification::Initial0209:
    if(!state.replayCriticalValidationPassed){state.periodic020ACount=0;state.periodic020AReturnCount=0;state.seenPeriodic020A=false;}
    state.seenInitial0209=true;++state.initial0209Count;state.validationCastInProgress=true;if(registers){state.validationInitialCall=*registers;state.pendingCall=*registers;state.pendingThreadId=registers->threadId;state.pendingClassification=operation.classification;state.awaitingReturn=true;state.pendingRegisterValidation=true;state.registerSemanticsValid=false;state.registerFailureReason.clear();}break;
case OperationClassification::Periodic020A:{
    const bool sameCaster=registers&&registers->ownershipRequired?registers->ownershipVerified&&state.validationInitialCall.ownershipVerified&&registers->localActor==state.validationInitialCall.localActor&&registers->casterId==state.validationInitialCall.casterId&&registers->rcx==state.validationInitialCall.rcx:registers&&registers->rdx==state.validationInitialCall.rdx;
    if(registers&&registers->ownershipRequired&&(!state.seenInitial0209||!sameCaster||registers->threadId!=state.validationInitialCall.threadId)){++state.otherOperationCount;break;}
    state.seenPeriodic020A=true;++state.periodic020ACount;
    if(registers&&state.seenInitial0209&&registers->threadId==state.validationInitialCall.threadId&&sameCaster){state.pendingCall=*registers;state.pendingThreadId=registers->threadId;state.pendingClassification=operation.classification;state.awaitingReturn=true;state.pendingRegisterValidation=false;}break;}
case OperationClassification::Other:++state.otherOperationCount;break;default:++state.unreadableOperationCount;break;}RecomputeLiveValidation(state);}
void ObserveLiveReturn(LiveValidationState& state,uint32_t threadId,uint64_t rsp,uint64_t r12,uint64_t r13,uint64_t r14,uint64_t r15,uint64_t rsi,uint64_t rdi,uint64_t rbp){state.seenReturnAnchor=true;++state.returnHitCount;if(state.awaitingReturn&&threadId==state.pendingThreadId){const bool matched=RegistersMatch(state.pendingCall,rsp,r12,r13,r14,r15,rsi,rdi)&&(!state.pendingCall.ownershipRequired||state.pendingCall.rbp==rbp);if(state.pendingClassification==OperationClassification::Initial0209&&state.pendingRegisterValidation){state.registerSemanticsValid=matched;state.registerFailureReason=state.registerSemanticsValid?std::string{}:"Initial return did not preserve RSP and required nonvolatile registers.";}else if(state.pendingClassification==OperationClassification::Periodic020A&&matched)++state.periodic020AReturnCount;state.awaitingReturn=false;state.pendingRegisterValidation=false;state.pendingClassification=OperationClassification::Unreadable;}RecomputeLiveValidation(state);}
void ObserveLiveProducer(LiveValidationState& state,const OperationObservation& operation){if(!operation.operationReadable){++state.producerUnreadableCount;return;}if(operation.family!=state.skillFamily){++state.producerOtherCount;return;}switch(operation.classification){case OperationClassification::Initial0209:++state.producer0209Count;break;case OperationClassification::Periodic020A:++state.producer020ACount;break;default:++state.producerOtherCount;break;}}
void RecomputeLiveValidation(LiveValidationState& state){if(state.replayCriticalValidationPassed){state.validationCastComplete=true;state.validationCastInProgress=false;state.blockingReason.clear();return;}const bool periodicComplete=state.periodic020ACount>=RequiredPeriodic020AForLiveValidation&&state.periodic020AReturnCount>=RequiredPeriodic020AForLiveValidation;const bool passed=state.skillFamily!=AoeSkillFamily::Unknown&&state.profileFingerprintsPassed&&state.seenPrepAnchor&&state.seenCallAnchor&&state.seenReturnAnchor&&state.seenInitial0209&&state.seenPeriodic020A&&state.registerSemanticsValid&&periodicComplete;if(passed){state.replayCriticalValidationPassed=true;state.validationCastComplete=true;state.validationCastInProgress=false;state.blockingReason.clear();return;}if(!state.profileFingerprintsPassed)state.blockingReason="Profile fingerprints not validated";else if(!state.seenPrepAnchor)state.blockingReason="Preparation anchor not yet observed";else if(!state.seenCallAnchor)state.blockingReason="Shared call anchor not yet observed";else if(!state.seenInitial0209)state.blockingReason="Initial AOE not yet observed: "+std::string(SkillContract(state.skillFamily).name);else if(!state.seenReturnAnchor)state.blockingReason="Initial return anchor not yet observed";else if(!state.registerSemanticsValid)state.blockingReason=state.registerFailureReason.empty()?"Initial return register semantics not yet validated":state.registerFailureReason;else if(!state.seenPeriodic020A)state.blockingReason="Periodic AOE not yet observed";else if(state.periodic020ACount<RequiredPeriodic020AForLiveValidation)state.blockingReason="Waiting for periodic AOE observations ("+std::to_string(state.periodic020ACount)+" / "+std::to_string(RequiredPeriodic020AForLiveValidation)+")";else state.blockingReason="Waiting for periodic AOE returns ("+std::to_string(state.periodic020AReturnCount)+" / "+std::to_string(RequiredPeriodic020AForLiveValidation)+")";}
bool CanArmInitialNxFromValidation(const LiveValidationState& state,const TargetInfo& target,const std::string& profileIdentity){return LiveValidationSessionMatches(state,target,profileIdentity)&&state.replayCriticalValidationPassed&&state.validationCastComplete;}
bool ShouldAutoArmAfterValidation(const LiveValidationState& state,bool configuredAutoArm,bool alreadyArmed,bool validationRequired){return configuredAutoArm&&!alreadyArmed&&(!validationRequired||state.replayCriticalValidationPassed);}
std::string LiveValidationDetails(const LiveValidationState& state,bool configuredAutoArm,bool runtimeArmed,bool validationRequired){std::ostringstream out;out<<"AOE skill: "<<SkillContract(state.skillFamily).name<<" (initial="<<Hex(SkillContract(state.skillFamily).initial)<<", periodic="<<Hex(SkillContract(state.skillFamily).periodic)<<")\r\nLIVE VALIDATION:\r\nProfile fingerprints: "<<YesNo(state.profileFingerprintsPassed)<<"\r\nPrep observed: "<<YesNo(state.seenPrepAnchor)<<"\r\nCall observed: "<<YesNo(state.seenCallAnchor)<<"\r\nInitial AOE observed: "<<YesNo(state.seenInitial0209)<<" (count="<<state.initial0209Count<<")\r\nReturn observed: "<<YesNo(state.seenReturnAnchor)<<"\r\nRegister semantics: "<<(state.registerSemanticsValid?"PASS":"WAITING")<<"\r\nPeriodic AOE observed: "<<YesNo(state.seenPeriodic020A)<<" (calls="<<state.periodic020ACount<<" / "<<RequiredPeriodic020AForLiveValidation<<", returns="<<state.periodic020AReturnCount<<" / "<<RequiredPeriodic020AForLiveValidation<<")\r\nReplay-critical validation: "<<(state.replayCriticalValidationPassed?"PASS":"WAITING")<<"\r\nBlocking reason: "<<(state.blockingReason.empty()?"none":state.blockingReason)<<"\r\n\r\nOPERATION OBSERVATION (shared call):\r\nInitial count: "<<state.initial0209Count<<"\r\nPeriodic count: "<<state.periodic020ACount<<"\r\nother count: "<<state.otherOperationCount<<"\r\n\r\nPRODUCER BREAKPOINT OBSERVATION:\r\nInitial count: "<<state.producer0209Count<<"\r\nPeriodic count: "<<state.producer020ACount<<"\r\nother count: "<<state.producerOtherCount<<"\r\n\r\nAUTO ARM:\r\nConfigured: "<<(configuredAutoArm?"ON":"OFF")<<"\r\nEligible: "<<YesNo(!validationRequired||state.replayCriticalValidationPassed)<<"\r\n\r\nINITIAL Nx:\r\n"<<(runtimeArmed?"ARMED FOR NEXT CAST":state.replayCriticalValidationPassed?"VALIDATED; WAITING FOR ARM":"WAITING FOR LIVE VALIDATION");return out.str();}
}
