#include "manager_state.hpp"
namespace aoe {
const wchar_t* ManagerTabName(ManagerTab tab){switch(tab){case ManagerTab::ResearchRecovery:return L"Research / Recovery";case ManagerTab::Profiles:return L"Profiles";default:return L"Play";}}
const char* SessionLifecycleName(SessionLifecycle phase){switch(phase){case SessionLifecycle::ProcessFound:return "PROCESS_FOUND";case SessionLifecycle::VerifyingTarget:return "VERIFYING_TARGET";case SessionLifecycle::ProfileLoading:return "PROFILE_LOADING";case SessionLifecycle::ProfileValidating:return "PROFILE_VALIDATING";case SessionLifecycle::Attaching:return "ATTACHING";case SessionLifecycle::Attached:return "ATTACHED";case SessionLifecycle::Arming:return "ARMING";case SessionLifecycle::Armed:return "ARMED";case SessionLifecycle::Running:return "RUNNING";case SessionLifecycle::SessionEnded:return "SESSION_ENDED";case SessionLifecycle::Invalidating:return "INVALIDATING";default:return "WAITING_FOR_PROCESS";}}
bool BeginManagerSession(const BuildProfile& profile,const TargetInfo& target,ManagerSession& session,std::string& error){const uint64_t previousGeneration=session.generation;ManagerSession fresh;fresh.generation=previousGeneration+1;fresh.lifecycle=SessionLifecycle::ProfileValidating;if(!ResolveAndValidateProfile(profile,target,fresh.anchors,error)){ManagerSession rejected;rejected.generation=previousGeneration;rejected.lifecycle=SessionLifecycle::WaitingForProcess;rejected.lastEndReason=error;session=std::move(rejected);return false;}fresh.active=true;fresh.profileValid=true;fresh.debuggerAttached=true;fresh.lifecycle=SessionLifecycle::Attached;fresh.pid=target.pid;fresh.creationTime=target.creationTime;fresh.moduleBase=target.base;fresh.sha256=target.image.sha256;fresh.runtime=profile.runtime;session=std::move(fresh);return true;}
bool ManagerSessionMatches(const ManagerSession& s,const TargetInfo& t){return s.active&&s.profileValid&&s.pid==t.pid&&s.creationTime==t.creationTime&&s.moduleBase==t.base&&s.sha256==t.image.sha256;}
void InvalidateManagerSession(ManagerSession& s,const std::string& reason){const uint64_t generation=s.generation;ManagerSession cleared;cleared.generation=generation;cleared.lifecycle=SessionLifecycle::Invalidating;cleared.lastEndReason=reason;s=std::move(cleared);}
void ApplyDebuggerSnapshot(ManagerSession& s,uint64_t processHandleValue,const std::vector<uint32_t>& threadIds,bool breakpointsInstalled,bool debugRegisterBookkeeping){s.processHandleValue=processHandleValue;s.threadIds=threadIds;s.breakpointsInstalled=breakpointsInstalled;s.debugRegisterBookkeeping=debugRegisterBookkeeping;}
bool MarkRuntimeArmed(ManagerSession& s,const Initial2xExperiment& experiment,std::string& error){if(!s.active||!s.profileValid||!s.debuggerAttached||!s.breakpointsInstalled||!experiment.armed||experiment.completed||experiment.aborted){s.runtimeArmed=false;s.lifecycle=s.active?SessionLifecycle::Attached:SessionLifecycle::WaitingForProcess;error="Current session does not have validated debugger and breakpoint state for Initial Nx.";return false;}s.experiment=experiment;s.runtimeArmed=true;s.lifecycle=SessionLifecycle::Armed;error.clear();return true;}
bool CanDisplayAutoArmed(const ManagerSession& s){return s.active&&s.profileValid&&s.debuggerAttached&&s.breakpointsInstalled&&s.runtimeArmed&&(s.lifecycle==SessionLifecycle::Armed||s.lifecycle==SessionLifecycle::Running);}
AutoAction NextAutoAction(const ManagerSettings& settings,bool processPresent,bool knownProfile,bool profileValid,bool attached,bool armed){if(settings.autoAttach&&!attached&&processPresent&&knownProfile)return AutoAction::Attach;if(settings.autoArm&&attached&&knownProfile&&profileValid&&!armed)return AutoAction::Arm;return AutoAction::None;}
}
