#include "profile.hpp"
#include <algorithm>
#include <cctype>
#include <fstream>
#include <optional>
#include <sstream>

namespace aoe {
namespace {
std::optional<std::string> Field(const std::string& json,const std::string& key){auto p=json.find("\""+key+"\"");if(p==std::string::npos)return{};p=json.find(':',p);if(p==std::string::npos)return{};++p;while(p<json.size()&&isspace(static_cast<unsigned char>(json[p])))++p;if(p>=json.size())return{};if(json[p]=='"'){auto e=json.find('"',p+1);if(e==std::string::npos)return{};return json.substr(p+1,e-p-1);}auto e=p;while(e<json.size()&&json[e]!=','&&json[e]!='}'&&!isspace(static_cast<unsigned char>(json[e])))++e;return json.substr(p,e-p);}
bool U64(const std::string& value,uint64_t& out){try{size_t used=0;out=std::stoull(value,&used,0);return used==value.size();}catch(...){return false;}}
bool Boolean(const std::string& value,bool& out){if(value=="true"){out=true;return true;}if(value=="false"){out=false;return true;}return false;}
bool Bytes(const std::string& text,std::vector<uint8_t>& out){out.clear();std::istringstream in(text);std::string token;while(in>>token){if(token.size()!=2)return false;try{size_t used=0;auto value=std::stoul(token,&used,16);if(used!=2||value>255)return false;out.push_back(uint8_t(value));}catch(...){return false;}}return !out.empty();}
bool Register(const std::string& text,X64RegisterId& out){for(unsigned i=0;i<16;++i)if(text==X64RegisterName(X64RegisterId(i))){out=X64RegisterId(i);return true;}out=X64RegisterId::Invalid;return false;}
bool IsExecutable(const TargetInfo& target,uint64_t rva){for(auto range:target.image.executableRanges)if(rva>=range.rva&&rva-range.rva<range.size)return true;return false;}
const char* RequiredV1[]={"initialPrepRva","initialCallRva","initialReturnRva","sharedWorkerRva","producerRva","templateLookupRva","wrapperRva","initialHandlerRva","dispatchRva","linkedActivationRva","periodicUpdateRva"};
const char* RequiredV2[]={"initialPrepRva","initialCallRva","initialReturnRva","sharedWorkerRva","producerRva","producerCallRva","typedActorLookupRva","targetBuilderRva","targetBuilderVectorRva","differentialParsedRva","idSerializationRva","typeSerializationRva","templateLookupRva","wrapperRva","initialHandlerRva","dispatchRva","linkedActivationRva","periodicUpdateRva","monsterCategoryWriteRva","charCategoryWriteRva","npcCategoryWriteRva","recallCategoryWriteRva"};
const char* RequiredV3[]={"initialPrepRva","initialCallRva","initialReturnRva","sharedWorkerRva","producerRva","producerCallRva","typedActorLookupRva","targetBuilderRva","targetBuilderVectorRva","differentialParsedRva","idSerializationRva","typeSerializationRva","templateLookupRva","locator_AoeLifecycleCaller","locator_AoeFunctionRecordDispatch","locator_SharedOperation020A","locator_TypedActorLookup","locator_SharedTypedActorCall","locator_OperationProducer","locator_ProducerCall","locator_RecordSerialization","locator_TemplateLookup","locator_LinkedAcquisitionPath","locator_AcquisitionType2Insertion","locator_AcquisitionRadiusGuard","locator_TargetVectorBuilder","locator_ParsedActionBoundary"};
bool NumberField(const std::string& json,const char* name,uint64_t& value,std::string& error){auto field=Field(json,name);if(!field||!U64(*field,value)){error=std::string("Missing or invalid profile field: ")+name;return false;}return true;}
bool ByteField(const std::string& json,const char* name,std::vector<uint8_t>& value,std::string& error){auto field=Field(json,name);if(!field||!Bytes(*field,value)){error=std::string("Missing or invalid fingerprint: ")+name;return false;}return true;}
void LegacyRuntime(BuildProfile& p,const std::string& json){auto a=[&](const char* n){auto* x=FindProfileAnchor(p,n);return x?x->rva:0;};auto& r=p.runtime;r.initialPrepRva=a("initialPrepRva");r.initialCallRva=a("initialCallRva");r.initialReturnRva=a("initialReturnRva");r.sharedWorkerRva=a("sharedWorkerRva");r.producerRva=a("producerRva");r.producerCallRva=0x7BB4B7;r.typedActorLookupRva=0x7B9BD0;r.targetBuilderVectorRva=0x6CC60;r.differentialParsedRva=0x6CC93;r.idSerializationRva=0x993DC;r.typeSerializationRva=0x993E6;r.targetVectorOffset=0x660;r.actorIdOffset=0x768;r.actorTypeOffset=0x7E1;r.actorEligibilityOffset=0x7CA;r.actorStatusOffset=0x7E4;r.localActorOffset=0x2710;r.actorPositionOffset=0xB0;r.actorTreeOffsets[1]=0x1140;r.actorTreeOffsets[2]=0x1120;r.actorTreeOffsets[7]=0x11B0;r.actorTreeOffsets[9]=0x1130;r.actorTreeOffsets[10]=0xC6FF00;r.actorTreeOffsets[11]=0x11A0;r.actorTreeOffsets[17]=0x1150;r.actorTreeOffsets[19]=0x11E0;r.targetRecordBytes=8;r.targetMaximumEntries=32;r.targetInspectorAvailable=true;r.initialNxAvailable=true;r.liveValidationRequired=false;if(auto f=Field(json,"initialPrepExpectedBytes"))Bytes(*f,r.initialPrepBytes);if(auto f=Field(json,"initialCallExpectedBytes"))Bytes(*f,r.initialCallBytes);if(auto f=Field(json,"initialReturnExpectedBytes"))Bytes(*f,r.initialReturnBytes);Bytes("41 54 41 55 41 56 41 57 48 81 EC 58 01 00 00",r.sharedWorkerBytes);Bytes("48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57",r.producerBytes);Bytes("E8 84 DD 8D FF",r.producerCallBytes);Bytes("85 D2 74 4A 41 0F B6 C0 FF C8 83 F8 12 77 3F",r.typedActorLookupBytes);Bytes("48 8D 8F 60 06 00 00",r.targetBuilderVectorBytes);Bytes("66 47 39 74 6F 3C",r.differentialParsedBytes);Bytes("48 8D 4C 24 28 E8 9A 66 95 00",r.idSerializationBytes);Bytes("48 8B C8 0F B6 D3 E8 0F 65 95 00",r.typeSerializationBytes);}
}

const ProfileAnchor* FindProfileAnchor(const BuildProfile& profile,const std::string& name){auto it=std::find_if(profile.anchors.begin(),profile.anchors.end(),[&](const auto& a){return a.name==name;});return it==profile.anchors.end()?nullptr:&*it;}
uint64_t ProfileTraceRva(const BuildProfile& profile,TraceMode mode){switch(mode){case TraceMode::Initial2x:case TraceMode::TargetInspector:return profile.runtime.initialCallRva;case TraceMode::TargetWriter:return profile.runtime.selectedTargetWriterRva;case TraceMode::Producer:case TraceMode::Tick100:return profile.runtime.producerRva;case TraceMode::Caller020A:return profile.runtime.sharedWorkerRva;default:return TraceRva(mode);}}
bool RuntimeLayoutSupportsInitialNx(const RuntimeLayout& r,std::string& reason){if(!r.initialNxAvailable){reason=r.initialNxUnavailableReason.empty()?"Initial Nx is disabled by this build profile.":r.initialNxUnavailableReason;return false;}const bool anchors=r.initialPrepRva&&r.initialCallRva&&r.initialReturnRva&&r.sharedWorkerRva&&r.producerRva&&r.producerCallRva&&r.typedActorLookupRva&&r.targetBuilderVectorRva&&r.idSerializationRva&&r.typeSerializationRva;const bool fingerprints=!r.initialPrepBytes.empty()&&!r.initialCallBytes.empty()&&!r.initialReturnBytes.empty()&&!r.sharedWorkerBytes.empty()&&!r.producerBytes.empty()&&!r.producerCallBytes.empty()&&!r.typedActorLookupBytes.empty()&&!r.targetBuilderVectorBytes.empty()&&!r.idSerializationBytes.empty()&&!r.typeSerializationBytes.empty();if(!anchors||!fingerprints){reason="Initial Nx requires every replay, producer, target-layout, and serialization anchor fingerprint.";return false;}auto direct=[&](uint64_t call,const std::vector<uint8_t>& bytes,uint64_t target){if(bytes.size()!=5||bytes[0]!=0xE8)return false;int32_t d=0;std::copy_n(bytes.data()+1,4,reinterpret_cast<uint8_t*>(&d));return int64_t(call+5)+d==int64_t(target);};if(!direct(r.initialCallRva,r.initialCallBytes,r.sharedWorkerRva)||!direct(r.producerCallRva,r.producerCallBytes,r.producerRva)){reason="Initial Nx direct-call fingerprints do not resolve to their profile anchors.";return false;}reason.clear();return true;}
bool RuntimeLayoutSupportsVisualSuppression(const RuntimeLayout& r,std::string& reason){if(!r.visualSuppressionAvailable){reason="Visual suppression is disabled by this build profile.";return false;}if(!r.visualReaderRva||!r.visualLookupRva||r.visualFieldOffset!=0x8C||r.visualBaseRegister==X64RegisterId::Invalid||r.visualReaderBytes.empty()){reason="Visual suppression requires a validated reader RVA, lookup target, base register, 0x8C field offset, and exact fingerprint.";return false;}reason.clear();return true;}
const char* ProfileValidationName(ProfileValidation value){switch(value){case ProfileValidation::KnownProfile:return "KNOWN PROFILE";case ProfileValidation::UnknownBuild:return "UNKNOWN BUILD";case ProfileValidation::Validating:return "VALIDATING";case ProfileValidation::Valid:return "VALID";case ProfileValidation::ValidationFailed:return "VALIDATION FAILED";case ProfileValidation::HashMismatch:return "HASH MISMATCH";default:return "NOT ATTACHED";}}

bool LoadBuildProfile(const std::filesystem::path& path,BuildProfile& profile,std::string& error){
    profile={};std::ifstream in(path,std::ios::binary);if(!in){error="Cannot open profile: "+path.string();return false;}std::string json((std::istreambuf_iterator<char>(in)),{});auto schema=Field(json,"schemaVersion"),sha=Field(json,"targetSha256");uint64_t parsed=0;if(!schema||!U64(*schema,parsed)||(parsed!=1&&parsed!=2&&parsed!=3)||!sha||sha->size()!=64){error="Profile schema or SHA-256 is invalid.";return false;}profile.schemaVersion=uint32_t(parsed);profile.targetSha256=*sha;std::transform(profile.targetSha256.begin(),profile.targetSha256.end(),profile.targetSha256.begin(),[](unsigned char c){return char(std::toupper(c));});if(auto value=Field(json,"created"))profile.created=*value;if(auto value=Field(json,"notes"))profile.notes=*value;
    const auto names=profile.schemaVersion==1?RequiredV1:profile.schemaVersion==3?RequiredV3:RequiredV2;const size_t count=profile.schemaVersion==1?std::size(RequiredV1):profile.schemaVersion==3?std::size(RequiredV3):std::size(RequiredV2);for(size_t i=0;i<count;++i){auto value=Field(json,names[i]);uint64_t rva=0;if(!value||!U64(*value,rva)||!rva){error=std::string("Missing or invalid profile anchor: ")+names[i];profile={};return false;}profile.anchors.push_back({names[i],rva});}
    if(profile.schemaVersion==1){LegacyRuntime(profile,json);error.clear();return true;}
    auto anchor=[&](const char* n){return FindProfileAnchor(profile,n)->rva;};auto& r=profile.runtime;r.initialPrepRva=anchor("initialPrepRva");r.initialCallRva=anchor("initialCallRva");r.initialReturnRva=anchor("initialReturnRva");r.sharedWorkerRva=anchor("sharedWorkerRva");r.producerRva=anchor("producerRva");r.producerCallRva=anchor("producerCallRva");r.typedActorLookupRva=anchor("typedActorLookupRva");r.targetBuilderVectorRva=anchor("targetBuilderVectorRva");r.differentialParsedRva=anchor("differentialParsedRva");r.idSerializationRva=anchor("idSerializationRva");r.typeSerializationRva=anchor("typeSerializationRva");
    uint64_t recordBytes=0,maxEntries=0;if(!NumberField(json,"targetVectorOffset",r.targetVectorOffset,error)||!NumberField(json,"actorIdOffset",r.actorIdOffset,error)||!NumberField(json,"actorTypeOffset",r.actorTypeOffset,error)||!NumberField(json,"actorEligibilityOffset",r.actorEligibilityOffset,error)||!NumberField(json,"actorStatusOffset",r.actorStatusOffset,error)||!NumberField(json,"localActorOffset",r.localActorOffset,error)||!NumberField(json,"targetRecordBytes",recordBytes,error)||!NumberField(json,"targetMaximumEntries",maxEntries,error))return false;if(auto position=Field(json,"actorPositionOffset"))U64(*position,r.actorPositionOffset);if(auto value=Field(json,"actorWorldLinkOffset"))U64(*value,r.actorWorldLinkOffset);if(auto value=Field(json,"actorWorldLinkOwnerOffset"))U64(*value,r.actorWorldLinkOwnerOffset);if(auto value=Field(json,"actorWorldPositionOffset"))U64(*value,r.actorWorldPositionOffset);if(auto value=Field(json,"gameContextPointerRva"))U64(*value,r.gameContextPointerRva);if(auto value=Field(json,"selectedTargetOffset"))U64(*value,r.selectedTargetOffset);if(auto value=Field(json,"selectedTargetWriterRva"))U64(*value,r.selectedTargetWriterRva);for(const char* name:{"selectedTargetReaderUiRva","selectedTargetReaderCombatRva"})if(auto value=Field(json,name)){uint64_t parsedRva=0;if(U64(*value,parsedRva)&&parsedRva)r.selectedTargetReaderRvas.push_back(parsedRva);}r.targetRecordBytes=size_t(recordBytes);r.targetMaximumEntries=size_t(maxEntries);if(r.targetRecordBytes!=8||!r.targetMaximumEntries||r.targetMaximumEntries>1024){error="Unsafe target-record size or maximum entry count.";return false;}
    for(auto [type,name]:std::initializer_list<std::pair<unsigned,const char*>>{{1,"type1TreeOffset"},{2,"type2TreeOffset"},{7,"type7TreeOffset"},{9,"type9TreeOffset"},{10,"type10TreeOffset"},{11,"type11TreeOffset"},{17,"type17TreeOffset"},{19,"type19TreeOffset"}})if(!NumberField(json,name,r.actorTreeOffsets[type],error))return false;
    auto inspector=Field(json,"targetInspectorAvailable"),nx=Field(json,"initialNxAvailable"),live=Field(json,"liveValidationRequired");if(!inspector||!Boolean(*inspector,r.targetInspectorAvailable)||!nx||!Boolean(*nx,r.initialNxAvailable)||!live||!Boolean(*live,r.liveValidationRequired)){error="Profile capability flags are missing or invalid.";return false;}if(auto visual=Field(json,"visualSuppressionAvailable")){if(!Boolean(*visual,r.visualSuppressionAvailable)){error="Invalid visualSuppressionAvailable capability";return false;}}if(auto reason=Field(json,"initialNxUnavailableReason"))r.initialNxUnavailableReason=*reason;if(!r.initialNxAvailable&&r.initialNxUnavailableReason.empty()){error="Disabled Initial Nx capability requires an explicit reason.";return false;}
    if(!ByteField(json,"initialPrepExpectedBytes",r.initialPrepBytes,error)||!ByteField(json,"initialCallExpectedBytes",r.initialCallBytes,error)||!ByteField(json,"initialReturnExpectedBytes",r.initialReturnBytes,error)||!ByteField(json,"sharedWorkerExpectedBytes",r.sharedWorkerBytes,error)||!ByteField(json,"producerExpectedBytes",r.producerBytes,error)||!ByteField(json,"producerCallExpectedBytes",r.producerCallBytes,error)||!ByteField(json,"typedActorLookupExpectedBytes",r.typedActorLookupBytes,error)||!ByteField(json,"targetBuilderVectorExpectedBytes",r.targetBuilderVectorBytes,error)||!ByteField(json,"differentialParsedExpectedBytes",r.differentialParsedBytes,error)||!ByteField(json,"idSerializationExpectedBytes",r.idSerializationBytes,error)||!ByteField(json,"typeSerializationExpectedBytes",r.typeSerializationBytes,error))return false;if(auto value=Field(json,"selectedTargetWriterExpectedBytes"))Bytes(*value,r.selectedTargetWriterBytes);
    if(auto value=Field(json,"aoeLocatorRequired"))if(!Boolean(*value,r.aoeLocatorRequired)){error="Invalid aoeLocatorRequired capability";return false;}if(r.visualSuppressionAvailable){if(!NumberField(json,"visualReaderRva",r.visualReaderRva,error)||!NumberField(json,"visualLookupRva",r.visualLookupRva,error)||!NumberField(json,"visualFieldOffset",r.visualFieldOffset,error)||!ByteField(json,"visualReaderExpectedBytes",r.visualReaderBytes,error))return false;auto base=Field(json,"visualBaseRegister");if(!base||!Register(*base,r.visualBaseRegister)){error="Missing or invalid visualBaseRegister";return false;}profile.anchors.push_back({"VisualSfxReader",r.visualReaderRva});if(!RuntimeLayoutSupportsVisualSuppression(r,error))return false;}
    error.clear();return true;
}

bool SelectBuildProfile(const std::filesystem::path& directory,const std::string& sha256,BuildProfile& profile,std::filesystem::path& selected,std::string& error){std::string normalized=sha256;std::transform(normalized.begin(),normalized.end(),normalized.begin(),[](unsigned char c){return char(std::toupper(c));});selected=directory/(std::wstring(normalized.begin(),normalized.end())+L".json");if(!std::filesystem::exists(selected)){profile={};error="NEW BUILD DETECTED · SHA-256 "+normalized+" · PROFILE RECOVERY REQUIRED";return false;}if(!LoadBuildProfile(selected,profile,error))return false;if(profile.targetSha256!=normalized){profile={};error="Profile filename/content SHA-256 mismatch.";return false;}return true;}
bool ResolveAndValidateProfile(const BuildProfile& profile,const TargetInfo& target,std::vector<ResolvedAnchor>& anchors,std::string& error){anchors.clear();if(!target.verified||!target.base||!target.size){error="No verified live target session.";return false;}if(profile.targetSha256!=target.image.sha256){error="Live target hash does not match the selected profile.";return false;}bool valid=true;for(const auto& anchor:profile.anchors){ResolvedAnchor item;item.name=anchor.name;item.rva=anchor.rva;item.inModule=anchor.rva<target.size&&target.base<=UINT64_MAX-anchor.rva;if(item.inModule)item.address=target.base+anchor.rva;item.executable=item.inModule&&IsExecutable(target,anchor.rva);valid=valid&&item.executable;anchors.push_back(item);}if(!valid){error="One or more required anchors are outside executable TClient sections.";return false;}error.clear();return true;}
}


