#include "settings.hpp"
#include "initial_2x.hpp"
#include <Windows.h>
#include <cctype>
#include <climits>
#include <fstream>
#include <optional>
#include <sstream>

namespace aoe {
namespace {
std::optional<std::string> RawValue(const std::string& json,const std::string& key){const auto marker="\""+key+"\"";auto p=json.find(marker);if(p==std::string::npos)return{};p=json.find(':',p+marker.size());if(p==std::string::npos)return{};++p;while(p<json.size()&&isspace(static_cast<unsigned char>(json[p])))++p;if(p>=json.size())return{};if(json[p]=='"'){auto e=json.find('"',p+1);if(e==std::string::npos)return{};return json.substr(p+1,e-p-1);}auto e=p;while(e<json.size()&&json[e]!=','&&json[e]!='}'&&!isspace(static_cast<unsigned char>(json[e])))++e;return json.substr(p,e-p);}
bool BoolValue(const std::string& json,const char* key,bool& value){auto raw=RawValue(json,key);if(!raw)return false;if(*raw=="true"){value=true;return true;}if(*raw=="false"){value=false;return true;}return false;}
bool IntValue(const std::string& json,const char* key,int& value){auto raw=RawValue(json,key);if(!raw||raw->empty())return false;try{size_t used=0;long long parsed=std::stoll(*raw,&used,10);if(used!=raw->size()||parsed<INT_MIN||parsed>INT_MAX)return false;value=int(parsed);return true;}catch(...){return false;}}
}
ManagerSettings SafeDefaultSettings(){return{};}
std::filesystem::path DefaultSettingsPath(){wchar_t buffer[32768]{};DWORD n=GetEnvironmentVariableW(L"LOCALAPPDATA",buffer,32768);std::filesystem::path root=n&&n<32768?std::filesystem::path(std::wstring(buffer,n)):std::filesystem::temp_directory_path();return root/L"4UnityAOEManager"/L"settings.json";}
bool ValidateSettings(ManagerSettings& s){bool valid=true;if(!ValidInitialCallCount(s.initialCalls)){s.initialCalls=2;valid=false;}if(s.lastSelectedTab<0||s.lastSelectedTab>2){s.lastSelectedTab=2;valid=false;}if(s.windowWidth<760||s.windowWidth>3840){s.windowWidth=1120;valid=false;}if(s.windowHeight<560||s.windowHeight>2160){s.windowHeight=760;valid=false;}return valid;}
bool LoadSettings(const std::filesystem::path& path,ManagerSettings& settings,std::string& diagnostic){settings=SafeDefaultSettings();std::ifstream input(path,std::ios::binary);if(!input){diagnostic="Settings missing; safe defaults loaded.";return true;}std::string json((std::istreambuf_iterator<char>(input)),{});int initial=0,tab=0,x=-1,y=-1,w=1120,h=760;bool aa=false,ar=false,sw=false,ma=false;if(!IntValue(json,"initialCalls",initial)||!BoolValue(json,"autoAttach",aa)||!BoolValue(json,"autoArm",ar)||!BoolValue(json,"startWithWindows",sw)||!BoolValue(json,"minimizeAfterAutoArm",ma)||!IntValue(json,"lastSelectedTab",tab)){diagnostic="Settings were corrupt or incomplete; safe defaults loaded.";return true;}IntValue(json,"windowX",x);IntValue(json,"windowY",y);IntValue(json,"windowWidth",w);IntValue(json,"windowHeight",h);settings.initialCalls=uint32_t(initial);settings.autoAttach=aa;settings.autoArm=ar;settings.startWithWindows=sw;settings.minimizeAfterAutoArm=ma;settings.lastSelectedTab=tab;settings.windowX=x;settings.windowY=y;settings.windowWidth=w;settings.windowHeight=h;const bool valid=ValidateSettings(settings);diagnostic=valid?"Settings loaded.":"Some settings were invalid and reset to safe defaults.";return true;}
bool SaveSettings(const std::filesystem::path& path,const ManagerSettings& source,std::string& error){ManagerSettings s=source;if(!ValidateSettings(s)){error="Refusing to save invalid manager settings.";return false;}try{std::filesystem::create_directories(path.parent_path());auto temporary=path;temporary+=L".tmp";std::ofstream out(temporary,std::ios::binary|std::ios::trunc);if(!out){error="Cannot create settings file.";return false;}out<<"{\n  \"schemaVersion\": 1,\n  \"initialCalls\": "<<s.initialCalls<<",\n  \"autoAttach\": "<<(s.autoAttach?"true":"false")<<",\n  \"autoArm\": "<<(s.autoArm?"true":"false")<<",\n  \"startWithWindows\": "<<(s.startWithWindows?"true":"false")<<",\n  \"minimizeAfterAutoArm\": "<<(s.minimizeAfterAutoArm?"true":"false")<<",\n  \"lastSelectedTab\": "<<s.lastSelectedTab<<",\n  \"windowX\": "<<s.windowX<<",\n  \"windowY\": "<<s.windowY<<",\n  \"windowWidth\": "<<s.windowWidth<<",\n  \"windowHeight\": "<<s.windowHeight<<"\n}\n";out.close();if(!out){error="Failed while writing settings.";return false;}std::error_code ec;std::filesystem::rename(temporary,path,ec);if(ec){std::filesystem::remove(path,ec);ec.clear();std::filesystem::rename(temporary,path,ec);}if(ec){error="Cannot replace settings file: "+ec.message();return false;}error.clear();return true;}catch(const std::exception& ex){error=ex.what();return false;}}
std::wstring StartupCommand(const std::filesystem::path& executable){return L"\""+executable.wstring()+L"\"";}
StartupRegistryIo WindowsStartupRegistryIo(){return{[](const std::wstring& command,std::string& error){HKEY key=nullptr;LONG code=RegCreateKeyExW(HKEY_CURRENT_USER,L"Software\\Microsoft\\Windows\\CurrentVersion\\Run",0,nullptr,0,KEY_SET_VALUE,nullptr,&key,nullptr);if(code!=ERROR_SUCCESS){error="Cannot open HKCU Run key: "+std::to_string(code);return false;}const auto bytes=DWORD((command.size()+1)*sizeof(wchar_t));code=RegSetValueExW(key,L"4UnityAOEManager",0,REG_SZ,reinterpret_cast<const BYTE*>(command.c_str()),bytes);RegCloseKey(key);if(code!=ERROR_SUCCESS){error="Cannot set startup entry: "+std::to_string(code);return false;}error.clear();return true;},[](std::string& error){HKEY key=nullptr;LONG code=RegOpenKeyExW(HKEY_CURRENT_USER,L"Software\\Microsoft\\Windows\\CurrentVersion\\Run",0,KEY_SET_VALUE,&key);if(code==ERROR_FILE_NOT_FOUND){error.clear();return true;}if(code!=ERROR_SUCCESS){error="Cannot open HKCU Run key: "+std::to_string(code);return false;}code=RegDeleteValueW(key,L"4UnityAOEManager");RegCloseKey(key);if(code!=ERROR_SUCCESS&&code!=ERROR_FILE_NOT_FOUND){error="Cannot remove startup entry: "+std::to_string(code);return false;}error.clear();return true;}};}
bool ApplyStartupSetting(const StartupRegistryIo& io,bool enabled,const std::filesystem::path& executable,std::string& error){if(enabled){if(executable.empty()){error="Executable path is unavailable.";return false;}return io.set(StartupCommand(executable),error);}return io.remove(error);}
}
