#include "target_inspector.hpp"
#include "initial_2x.hpp"
#include "operation_observer.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <map>
#include <sstream>

namespace aoe {
namespace {
std::string Json(const std::string& value){std::ostringstream out;out<<'"';for(unsigned char c:value){switch(c){case '"':out<<"\\\"";break;case '\\':out<<"\\\\";break;case '\n':out<<"\\n";break;case '\r':out<<"\\r";break;case '\t':out<<"\\t";break;default:if(c<0x20)out<<"\\u"<<std::hex<<std::setw(4)<<std::setfill('0')<<unsigned(c)<<std::dec;else out<<char(c);}}out<<'"';return out.str();}
template<size_t N> std::string Bytes(const std::array<uint8_t,N>& bytes){static constexpr char h[]="0123456789ABCDEF";std::string out;out.reserve(N*2);for(auto b:bytes){out.push_back(h[b>>4]);out.push_back(h[b&15]);}return out;}
bool ReadExact(const InspectorRead& read,uint64_t address,void* data,size_t size,uint32_t& error){error=0;return address&&read&&read(address,data,size,error);}
bool Add(uint64_t base,uint64_t offset,uint64_t& result){if(base>UINT64_MAX-offset)return false;result=base+offset;return true;}

bool TreeOffsetForType(const RuntimeLayout& layout,uint8_t type,uint64_t& offset){if(type>=layout.actorTreeOffsets.size()||!layout.actorTreeOffsets[type])return false;offset=layout.actorTreeOffsets[type];return true;}

const TargetInspectorEvent* FirstInitialForMarker(const TargetInspectorSession& session,uint64_t marker){for(const auto& event:session.events)if(event.markerId==marker&&event.initial0209)return &event;return nullptr;}
template<size_t N> uint64_t Scalar(const std::array<uint8_t,N>& bytes,size_t offset,size_t width){uint64_t value=0;if(width&&width<=8&&offset<=N&&width<=N-offset)memcpy(&value,bytes.data()+offset,width);return value;}
struct FieldDefinition {uint32_t offset,width;const char* label;};
constexpr FieldDefinition OperationFields[]={{0x00,4,"parsed dword 0"},{0x04,4,"parsed dword 1"},{0x08,4,"parsed dword 2"},{0x0C,2,"operation/template word"},{0x0E,2,"parsed word"},{0x14,4,"parsed dword 3"},{0x18,4,"parsed dword 4"},{0x1C,4,"parsed dword 5"},{0x20,4,"parsed dword 6"},{0x24,4,"outer parsed dword"},{0x28,1,"parsed byte 0"},{0x29,1,"parsed byte 1"},{0x2A,1,"parsed byte 2"},{0x2B,1,"parsed byte 3"},{0x2C,1,"parsed byte 4"},{0x2E,1,"parsed byte 5"}};
bool FrameAddress(uint64_t rbp,int64_t displacement,uint64_t& address){if(displacement<0){const uint64_t amount=uint64_t(-displacement);if(rbp<amount)return false;address=rbp-amount;return true;}return Add(rbp,uint64_t(displacement),address);}
}

bool IsCanonicalUserPointer(uint64_t value){return value>=0x10000&&value<=0x00007FFFFFFFFFFFull;}
bool InitialNxConflictsWithTargetInspector(const Initial2xExperiment& experiment){return experiment.armed&&!experiment.completed&&!experiment.aborted;}
bool ReleaseInitialNxForTargetInspector(Initial2xExperiment& experiment){const bool conflict=InitialNxConflictsWithTargetInspector(experiment);if(conflict)AbortInitial2x(experiment,"Stopped to prepare the read-only AOE Target Differential Inspector.");experiment={};return conflict;}

const char* TargetActorLookupStatusName(TargetActorLookupStatus status){switch(status){case TargetActorLookupStatus::Resolved:return "resolved";case TargetActorLookupStatus::InvalidKey:return "invalid key";case TargetActorLookupStatus::UnsupportedType:return "unsupported type";case TargetActorLookupStatus::NotFound:return "not found";case TargetActorLookupStatus::ReadError:return "read error";case TargetActorLookupStatus::TraversalLimit:return "traversal limit";default:return "not attempted";}}
const char* TargetActorTypeName(uint8_t type){switch(type){case 1:return "CTClientChar";case 2:return "CTClientMonster";case 3:return "CTClientNpc (not resolved by +7B9BD0)";case 7:return "CTClientRecall/CTClientPet namespace";case 11:return "CTClientRecall namespace (subtype unproven)";default:return "other/unknown actor namespace";}}

SpatialPoint CaptureSpatialPoint(const InspectorRead& read,uint64_t actorPointer,uint64_t positionOffset){
    SpatialPoint point;point.source="actor+"+Hex(positionOffset);point.confidence="profile-verified representation";
    if(!IsCanonicalUserPointer(actorPointer)||!positionOffset){point.reason="actor pointer or position offset unavailable";return point;}
    uint64_t address=0;if(!Add(actorPointer,positionOffset,address)){point.reason="position address overflow";return point;}
    std::array<uint32_t,4> raw{};if(!ReadExact(read,address,raw.data(),sizeof(raw),point.error)){point.reason="XYZ/W read failed";return point;}point.readable=true;
    for(size_t i=0;i<3;++i){point.raw[i]=raw[i];memcpy(&point.value[i],&raw[i],sizeof(float));}
    float w=0;memcpy(&w,&raw[3],sizeof(w));point.finite=std::isfinite(point.value[0])&&std::isfinite(point.value[1])&&std::isfinite(point.value[2])&&std::isfinite(w);
    point.plausible=point.finite&&std::fabs(double(point.value[0]))<=1000000.0&&std::fabs(double(point.value[1]))<=1000000.0&&std::fabs(double(point.value[2]))<=1000000.0&&std::fabs(double(w)-1.0)<=0.05;
    point.reason=point.plausible?"XYZ finite and homogeneous W near 1.0":point.finite?"finite XYZ but W/range validation failed":"non-finite XYZ/W";return point;
}

ActorSpatialSnapshot CaptureActorSpatial(const InspectorRead& read,const RuntimeLayout& layout,uint64_t actorPointer,const std::string& source,const std::string& confidence){
    ActorSpatialSnapshot snapshot;snapshot.pointer=actorPointer;snapshot.source=source;snapshot.confidence=confidence;
    if(!IsCanonicalUserPointer(actorPointer)){snapshot.reason="actor pointer unavailable";return snapshot;}uint64_t at=0;
    if(Add(actorPointer,layout.actorIdOffset,at)&&ReadExact(read,at,&snapshot.actorId,sizeof(snapshot.actorId),snapshot.error)&&Add(actorPointer,layout.actorTypeOffset,at)&&ReadExact(read,at,&snapshot.category,sizeof(snapshot.category),snapshot.error))snapshot.identityReadable=true;
    if(snapshot.identityReadable&&snapshot.category==2&&layout.actorWorldLinkOffset&&layout.actorWorldPositionOffset){uint64_t base=actorPointer,linkAt=0,link=0,ownerAt=0,owner=0;if(Add(actorPointer,layout.actorWorldLinkOffset,linkAt)&&ReadExact(read,linkAt,&link,sizeof(link),snapshot.error)&&IsCanonicalUserPointer(link)&&Add(link,layout.actorWorldLinkOwnerOffset,ownerAt)&&ReadExact(read,ownerAt,&owner,sizeof(owner),snapshot.error)&&owner==actorPointer)base=link;auto& point=snapshot.position;point.source="static actor world-position accessor-equivalent: validated link/base +"+Hex(layout.actorWorldPositionOffset);point.confidence="high static semantics; live monster-motion correlation still pending";uint64_t positionAt=0;if(Add(base,layout.actorWorldPositionOffset,positionAt)&&ReadExact(read,positionAt,point.raw.data(),sizeof(point.raw),point.error)){point.readable=true;for(size_t i=0;i<3;++i)memcpy(&point.value[i],&point.raw[i],4);point.finite=std::isfinite(point.value[0])&&std::isfinite(point.value[1])&&std::isfinite(point.value[2]);point.plausible=point.finite&&std::fabs(double(point.value[0]))<=1000000.0&&std::fabs(double(point.value[1]))<=1000000.0&&std::fabs(double(point.value[2]))<=1000000.0;point.reason=point.plausible?"finite bounded XYZ from accessor-equivalent path":point.finite?"finite XYZ outside world range":"non-finite XYZ";}else point.reason="actor world-position read failed";}else snapshot.position=CaptureSpatialPoint(read,actorPointer,layout.actorPositionOffset);
    snapshot.positionAvailable=snapshot.position.plausible;snapshot.reason=snapshot.positionAvailable?"validated actor XYZ snapshot":snapshot.position.reason;return snapshot;
}

ActorSpatialSnapshot CaptureSelectedTargetSpatial(const InspectorRead& read,const RuntimeLayout& layout,uint64_t gameContext,const std::string& source){
    ActorSpatialSnapshot snapshot;snapshot.source=source;snapshot.confidence="none";uint64_t storage=0,actor=0;uint32_t error=0;
    if(!IsCanonicalUserPointer(gameContext)||!Add(gameContext,layout.selectedTargetOffset,storage)||!ReadExact(read,storage,&actor,sizeof(actor),error)){snapshot.error=error;snapshot.reason="profiled current-selection storage is unreadable";return snapshot;}
    if(!actor){snapshot.reason="profiled current-selection storage is null";return snapshot;}
    snapshot=CaptureActorSpatial(read,layout,actor,source,"candidate: direct CTClientGame+0x2318 snapshot");
    if(!snapshot.identityReadable||snapshot.category!=2){snapshot.reason="current-selection candidate is not a readable category-2 actor";return snapshot;}
    const auto resolved=ResolveTargetActor(read,layout,gameContext,snapshot.actorId,snapshot.category);
    if(resolved.status!=TargetActorLookupStatus::Resolved||resolved.actorPointer!=actor){snapshot.positionAvailable=false;snapshot.reason="typed actor tree did not resolve identity back to the stored pointer";return snapshot;}
    snapshot.provenanceValidated=true;snapshot.confidence="high: direct pointer, category 2, typed actor tree agrees";snapshot.reason="validated current-selection snapshot";return snapshot;
}

OperationSpatialFields DecodeOperationSpatialFields(const std::array<uint8_t,DifferentialOperationRecordBytes>& record,bool readable){OperationSpatialFields result;result.readable=readable;if(!readable)return result;for(size_t i=0;i<3;++i){memcpy(&result.raw[i],record.data()+i*4,4);memcpy(&result.value[i],record.data()+i*4,4);}memcpy(&result.field24Raw,record.data()+0x24,4);result.finite=std::isfinite(result.value[0])&&std::isfinite(result.value[1])&&std::isfinite(result.value[2]);result.plausible=result.finite&&std::fabs(double(result.value[0]))<=1000000.0&&std::fabs(double(result.value[1]))<=1000000.0&&std::fabs(double(result.value[2]))<=1000000.0;return result;}

TargetActorResolution ResolveTargetActor(const InspectorRead& read,const RuntimeLayout& layout,uint64_t context,uint32_t actorId,uint8_t actorType){
    TargetActorResolution result;
    if(!actorId||!actorType||!IsCanonicalUserPointer(context)){result.status=TargetActorLookupStatus::InvalidKey;return result;}
    if(actorType==1){
        uint64_t localAddress=0,localActor=0;
        if(!Add(context,layout.localActorOffset,localAddress)||!ReadExact(read,localAddress,&localActor,sizeof(localActor),result.error)){result.status=TargetActorLookupStatus::ReadError;return result;}
        if(IsCanonicalUserPointer(localActor)){
            uint64_t idAddress=0;uint32_t localId=0;
            if(!Add(localActor,layout.actorIdOffset,idAddress)||!ReadExact(read,idAddress,&localId,sizeof(localId),result.error)){result.status=TargetActorLookupStatus::ReadError;return result;}
            if(localId==actorId){uint64_t typeAddress=0;uint8_t localType=0;if(!Add(localActor,layout.actorTypeOffset,typeAddress)||!ReadExact(read,typeAddress,&localType,sizeof(localType),result.error)){result.status=TargetActorLookupStatus::ReadError;return result;}result.status=TargetActorLookupStatus::Resolved;result.actorPointer=localActor;result.actorIdentityReadable=true;result.actorId=localId;result.actorType=localType;result.idMatches=true;result.typeMatches=localType==actorType;return result;}
        }
    }
    uint64_t treeOffset=0;if(!TreeOffsetForType(layout,actorType,treeOffset)){result.status=TargetActorLookupStatus::UnsupportedType;return result;}
    uint64_t treeField=0;if(!Add(context,treeOffset,treeField)||!ReadExact(read,treeField,&result.containerHeader,sizeof(result.containerHeader),result.error)){result.status=TargetActorLookupStatus::ReadError;return result;}
    if(!IsCanonicalUserPointer(result.containerHeader)){result.status=TargetActorLookupStatus::NotFound;return result;}
    uint64_t rootAddress=0,current=0,candidate=result.containerHeader;
    if(!Add(result.containerHeader,8,rootAddress)||!ReadExact(read,rootAddress,&current,sizeof(current),result.error)){result.status=TargetActorLookupStatus::ReadError;return result;}
    for(size_t depth=0;depth<TargetTreeTraversalLimit;++depth){
        if(!IsCanonicalUserPointer(current)){result.status=TargetActorLookupStatus::ReadError;return result;}
        uint8_t sentinel=0;uint64_t sentinelAddress=0;if(!Add(current,0x19,sentinelAddress)||!ReadExact(read,sentinelAddress,&sentinel,sizeof(sentinel),result.error)){result.status=TargetActorLookupStatus::ReadError;return result;}
        if(sentinel)break;
        uint32_t key=0;uint64_t keyAddress=0;if(!Add(current,0x20,keyAddress)||!ReadExact(read,keyAddress,&key,sizeof(key),result.error)){result.status=TargetActorLookupStatus::ReadError;return result;}
        uint64_t nextAddress=current;if(key>=actorId)candidate=current;else if(!Add(current,0x10,nextAddress)){result.status=TargetActorLookupStatus::ReadError;return result;}
        if(!ReadExact(read,nextAddress,&current,sizeof(current),result.error)){result.status=TargetActorLookupStatus::ReadError;return result;}
        if(depth+1==TargetTreeTraversalLimit){result.status=TargetActorLookupStatus::TraversalLimit;return result;}
    }
    if(candidate==result.containerHeader||!IsCanonicalUserPointer(candidate)){result.status=TargetActorLookupStatus::NotFound;return result;}
    uint8_t candidateSentinel=0;uint32_t candidateKey=0;uint64_t at=0;
    if(!Add(candidate,0x19,at)||!ReadExact(read,at,&candidateSentinel,sizeof(candidateSentinel),result.error)||!Add(candidate,0x20,at)||!ReadExact(read,at,&candidateKey,sizeof(candidateKey),result.error)){result.status=TargetActorLookupStatus::ReadError;return result;}
    if(candidateSentinel||candidateKey!=actorId){result.status=TargetActorLookupStatus::NotFound;return result;}
    result.node=candidate;if(!Add(candidate,0x28,at)||!ReadExact(read,at,&result.actorPointer,sizeof(result.actorPointer),result.error)){result.status=TargetActorLookupStatus::ReadError;return result;}
    if(!IsCanonicalUserPointer(result.actorPointer)){result.actorPointer=0;result.status=TargetActorLookupStatus::NotFound;return result;}
    uint64_t actorIdAddress=0,actorTypeAddress=0;
    if(!Add(result.actorPointer,layout.actorIdOffset,actorIdAddress)||!Add(result.actorPointer,layout.actorTypeOffset,actorTypeAddress)||!ReadExact(read,actorIdAddress,&result.actorId,sizeof(result.actorId),result.error)||!ReadExact(read,actorTypeAddress,&result.actorType,sizeof(result.actorType),result.error)){result.status=TargetActorLookupStatus::ReadError;return result;}
    result.actorIdentityReadable=true;result.idMatches=result.actorId==actorId;result.typeMatches=result.actorType==actorType;result.status=TargetActorLookupStatus::Resolved;return result;
}

TargetVectorCapture InspectPrimaryTargetVector(const InspectorRead& read,const RuntimeLayout& layout,uint64_t context,uint64_t entity,uint64_t r12){
    TargetVectorCapture capture;capture.entityPointer=entity;capture.addressFromR12=r12;
    if(!IsCanonicalUserPointer(entity)||!Add(entity,layout.targetVectorOffset,capture.expectedAddress)){capture.notes="invalid entity pointer";return capture;}
    capture.r12MatchesEntity660=r12==capture.expectedAddress;if(!capture.r12MatchesEntity660){capture.notes="R12 does not equal RDX+0x660; capture refused";return capture;}
    std::array<uint64_t,3> header{};if(!ReadExact(read,capture.expectedAddress,header.data(),sizeof(header),capture.error)){capture.notes="entity+0x660 header read failed";return capture;}
    capture.headerReadable=true;capture.begin=header[0];capture.end=header[1];capture.capacity=header[2];const bool allNull=!capture.begin&&!capture.end&&!capture.capacity;
    if(allNull){capture.structurallyValid=true;capture.countWithinLimit=true;capture.notes="empty entity+0x660 vector";return capture;}
    if(!IsCanonicalUserPointer(capture.begin)||!IsCanonicalUserPointer(capture.end)||!IsCanonicalUserPointer(capture.capacity)||capture.begin>capture.end||capture.end>capture.capacity){capture.notes="invalid entity+0x660 vector ordering or pointer";return capture;}
    const uint64_t used=capture.end-capture.begin,reserved=capture.capacity-capture.begin;if((used%8)||(reserved%8)){capture.notes="entity+0x660 vector byte span is not qword-aligned";return capture;}
    capture.structurallyValid=true;capture.count=used/8;capture.countWithinLimit=capture.count<=layout.targetMaximumEntries;capture.truncated=capture.count>layout.targetMaximumEntries;capture.notes=capture.countWithinLimit?"exact profile target vector":"count exceeds profile callsite limit; capture bounded";
    const size_t count=size_t(std::min<uint64_t>(capture.count,layout.targetMaximumEntries));capture.records.reserve(count);
    for(size_t i=0;i<count;++i){TargetRecord record;record.index=uint32_t(i);record.slotAddress=capture.begin+i*8;if(!ReadExact(read,record.slotAddress,&record.recordPointer,sizeof(record.recordPointer),record.error)){capture.records.push_back(record);continue;}record.pointerReadable=true;if(!IsCanonicalUserPointer(record.recordPointer)||!ReadExact(read,record.recordPointer,record.raw.data(),record.raw.size(),record.error)){capture.records.push_back(record);continue;}record.recordReadable=true;memcpy(&record.actorId,record.raw.data(),sizeof(record.actorId));record.actorType=record.raw[4];std::copy(record.raw.begin()+5,record.raw.end(),record.trailingBytes.begin());record.resolution=ResolveTargetActor(read,layout,context,record.actorId,record.actorType);capture.records.push_back(record);}
    return capture;
}

TargetInspectorEvent CaptureTargetInspectorEvent(const InspectorRead& read,const RuntimeLayout& layout,const TargetInspectorEvent& registers){
    TargetInspectorEvent event=registers;const auto operation=DecodeOperation(read,event.r9);event.operationReadable=operation.operationReadable;event.operationWord0=operation.operationWord;event.operationReadError=operation.readError;event.initial0209=operation.classification==OperationClassification::Initial0209;event.periodic020A=operation.classification==OperationClassification::Periodic020A;if(!event.initial0209)return event;
    event.operationRecordReadable=ReadExact(read,event.r8,event.operationRecord.data(),event.operationRecord.size(),event.operationRecordError);
    event.operationSpatial=DecodeOperationSpatialFields(event.operationRecord,event.operationRecordReadable);
    uint64_t address=0;if(Add(event.rdx,layout.actorIdOffset,address)&&ReadExact(read,address,&event.ownerActorId,sizeof(event.ownerActorId),event.ownerReadError)&&Add(event.rdx,layout.actorTypeOffset,address)&&ReadExact(read,address,&event.ownerCategory,sizeof(event.ownerCategory),event.ownerReadError)){event.ownerIdentityReadable=true;event.ownerCategoryReadable=true;}
    event.targetVector=InspectPrimaryTargetVector(read,layout,event.rcx,event.rdx,event.r12);event.spatial.player=CaptureActorSpatial(read,layout,event.rdx,"initial 0x0209 RDX owner/local actor","high: callsite owner identity and current-build +0x2710/+0xB0 writers");event.spatial.selectedTarget=CaptureSelectedTargetSpatial(read,layout,event.rcx,"initial 0x0209 CTClientGame+0x2318");
    if(event.operationRecordReadable){
        constexpr uint32_t idOffsets[]={0x00,0x04,0x08,0x14,0x18,0x1C,0x20,0x24};constexpr uint32_t typeOffsets[]={0x28,0x29,0x2A,0x2B,0x2C,0x2E};
        for(auto idOffset:idOffsets){const uint32_t id=uint32_t(Scalar(event.operationRecord,idOffset,4));if(!id)continue;for(auto typeOffset:typeOffsets){const uint8_t type=uint8_t(Scalar(event.operationRecord,typeOffset,1));if(!type||type>=layout.actorTreeOffsets.size()||(type!=1&&!layout.actorTreeOffsets[type]))continue;DifferentialActorProbe probe;probe.idOffset=idOffset;probe.typeOffset=typeOffset;probe.actorId=id;probe.actorType=type;auto resolved=ResolveTargetActor(read,layout,event.rcx,id,type);probe.error=resolved.error;probe.actorPointer=resolved.actorPointer;probe.resolved=resolved.status==TargetActorLookupStatus::Resolved&&resolved.idMatches&&resolved.typeMatches;if(probe.resolved&&Add(probe.actorPointer,layout.actorTypeOffset,address)&&ReadExact(read,address,&probe.category,sizeof(probe.category),probe.error)){probe.categoryReadable=true;probe.spatial=CaptureActorSpatial(read,layout,probe.actorPointer,"operation-record typed resolver candidate","conditional: promoted only after A/B/C changing category-2 proof");}event.actorProbes.push_back(probe);}}
    }
    return event;
}

ParsedInputCapture CaptureParsedInput(const InspectorRead& read,const RuntimeLayout& layout,const ParsedInputCapture& registers){ParsedInputCapture capture=registers;uint64_t at=0;capture.actorStatePointer=capture.operationRecordPointer;capture.resolvedActorPointer=capture.ownerPointer;if(FrameAddress(capture.rbp,-0x40,at))capture.operationReadable=ReadExact(read,at,&capture.operationWord,sizeof(capture.operationWord),capture.error);capture.operation0209=capture.operationReadable&&ClassifyOperationWord(capture.operationWord).classification==OperationClassification::Initial0209;if(FrameAddress(capture.rbp,-0x30,at))capture.semanticInput=ReadExact(read,at,&capture.parsedActorId,sizeof(capture.parsedActorId),capture.error)||capture.semanticInput;if(FrameAddress(capture.rbp,-0x3C,at))capture.semanticInput=ReadExact(read,at,&capture.parsedActorType,sizeof(capture.parsedActorType),capture.error)||capture.semanticInput;if(FrameAddress(capture.rbp,-0x3B,at))ReadExact(read,at,&capture.modeByte,sizeof(capture.modeByte),capture.error);if(FrameAddress(capture.rbp,-0x2C,at))ReadExact(read,at,&capture.outerField24,sizeof(capture.outerField24),capture.error);if(FrameAddress(capture.rbp,0x58,at))ReadExact(read,at,&capture.recordCount,sizeof(capture.recordCount),capture.error);if(FrameAddress(capture.rbp,0x40,at))ReadExact(read,at,&capture.gameContext,sizeof(capture.gameContext),capture.error);if(Add(capture.resolvedActorPointer,layout.actorIdOffset,at)&&ReadExact(read,at,&capture.ownerActorId,sizeof(capture.ownerActorId),capture.error)&&Add(capture.resolvedActorPointer,layout.actorTypeOffset,at)&&ReadExact(read,at,&capture.ownerCategory,sizeof(capture.ownerCategory),capture.error))capture.ownerIdentityReadable=true;return capture;}

bool MarkerHasInitial0209(const TargetInspectorSession& session,uint64_t markerId){return FirstInitialForMarker(session,markerId)!=nullptr;}
int ArmedTargetCaptureSlot(const TargetInspectorSession& session){for(size_t i=0;i<session.captureSlots.size();++i)if(session.captureSlots[i].state==TargetCaptureSlotState::ArmedForNext0209)return int(i);return -1;}
int NextTargetCaptureSlot(const TargetInspectorSession& session){if(ArmedTargetCaptureSlot(session)>=0)return -1;for(size_t i=0;i<session.captureSlots.size();++i)if(session.captureSlots[i].state==TargetCaptureSlotState::Empty)return int(i);return -1;}
bool CanMarkNextTargetCapture(const TargetInspectorSession& session){return (session.phase==TargetInspectorPhase::WaitingForAoe||session.phase==TargetInspectorPhase::Capturing)&&NextTargetCaptureSlot(session)>=0;}
bool ArmNextTargetCapture(TargetInspectorSession& session,const Marker& marker,std::string& error,const SpatialSnapshot* markerSpatial){
    if(session.phase!=TargetInspectorPhase::WaitingForAoe&&session.phase!=TargetInspectorPhase::Capturing){error="Target Differential Inspector is not waiting for an AOE marker.";return false;}
    if(ArmedTargetCaptureSlot(session)>=0){error="Wait for the current capture's first initial 0x0209 or cancel the current marker.";return false;}
    const int slot=NextTargetCaptureSlot(session);if(slot<0){error="Captures A through D are complete. Stop and export this session.";return false;}
    const uint64_t expectedId=uint64_t(slot)+1;if(marker.id!=expectedId){error="Marker ID does not match the next capture slot.";return false;}
    auto& capture=session.captureSlots[size_t(slot)];capture.state=TargetCaptureSlotState::ArmedForNext0209;capture.markerId=marker.id;capture.captureSequence=0;if(markerSpatial)session.markerSpatial[size_t(slot)]=*markerSpatial;session.markers.push_back(marker);session.phase=TargetInspectorPhase::Capturing;error.clear();return true;
}
bool CancelCurrentTargetCapture(TargetInspectorSession& session,std::string& error){
    const int slot=ArmedTargetCaptureSlot(session);if(slot<0){error="No capture marker is currently waiting for an initial 0x0209.";return false;}
    const uint64_t markerId=session.captureSlots[size_t(slot)].markerId;session.captureSlots[size_t(slot)]={};
    session.markers.erase(std::remove_if(session.markers.begin(),session.markers.end(),[&](const Marker& marker){return marker.id==markerId;}),session.markers.end());
    session.parsedInputs.erase(std::remove_if(session.parsedInputs.begin(),session.parsedInputs.end(),[&](const ParsedInputCapture& item){return item.markerId==markerId;}),session.parsedInputs.end());
    error.clear();return true;
}
const char* TargetCaptureSlotStateName(TargetCaptureSlotState state){switch(state){case TargetCaptureSlotState::ArmedForNext0209:return "ARMED FOR NEXT 0209";case TargetCaptureSlotState::Captured:return "CAPTURED";default:return "EMPTY";}}
bool RecordDifferentialEvent(TargetInspectorSession& session,TargetInspectorEvent event){
    if(session.phase!=TargetInspectorPhase::Capturing)return false;
    if(event.periodic020A){auto captured=session.captureSlots.rend();for(auto it=session.captureSlots.rbegin();it!=session.captureSlots.rend();++it)if(it->state==TargetCaptureSlotState::Captured){captured=it;break;}if(captured==session.captureSlots.rend()||session.periodicEvents.size()>=DifferentialEventLimit)return false;event.markerId=captured->markerId;session.periodicEvents.push_back(std::move(event));return true;}
    if(!event.initial0209||session.events.size()>=session.captureSlots.size())return false;const int slot=ArmedTargetCaptureSlot(session);if(slot<0)return false;auto& capture=session.captureSlots[size_t(slot)];event.markerId=capture.markerId;if(MarkerHasInitial0209(session,event.markerId))return false;const uint64_t sequence=event.sequence;session.events.push_back(std::move(event));capture.state=TargetCaptureSlotState::Captured;capture.captureSequence=sequence;return true;
}
bool RecordParsedInput(TargetInspectorSession& session,ParsedInputCapture capture){
    if(session.phase!=TargetInspectorPhase::Capturing||!capture.semanticInput)return false;int slot=ArmedTargetCaptureSlot(session);if(slot<0)for(int i=int(session.captureSlots.size())-1;i>=0;--i)if(session.captureSlots[size_t(i)].state==TargetCaptureSlotState::Captured){slot=i;break;}if(slot<0)return false;capture.markerId=session.captureSlots[size_t(slot)].markerId;if(std::any_of(session.parsedInputs.begin(),session.parsedInputs.end(),[&](const auto& item){return item.markerId==capture.markerId;}))return false;session.parsedInputs.push_back(std::move(capture));return true;
}

std::vector<DifferentialFieldComparison> CompareOperationFields(const TargetInspectorSession& session){std::vector<DifferentialFieldComparison> rows;for(const auto& definition:OperationFields){DifferentialFieldComparison row;row.offset=definition.offset;row.width=definition.width;row.label=definition.label;for(size_t marker=1;marker<=4;++marker)if(const auto* event=FirstInitialForMarker(session,marker);event&&event->operationRecordReadable){row.present[marker-1]=true;row.values[marker-1]=Scalar(event->operationRecord,row.offset,row.width);}if(row.present[0]&&row.present[1]){row.changed=row.values[0]!=row.values[1];if(row.present[2]){row.changed=row.changed||row.values[0]!=row.values[2]||row.values[1]!=row.values[2];row.allPairwiseDifferent=row.values[0]!=row.values[1]&&row.values[0]!=row.values[2]&&row.values[1]!=row.values[2];}}row.interpretation=row.offset==0x0C?"operation/template identity":row.changed?"changes across marked initial casts; candidate only":"unchanged in available captures";rows.push_back(std::move(row));}return rows;}

std::vector<DifferentialActorCandidate> CompareActorCandidates(const TargetInspectorSession& session){
    std::map<std::pair<uint32_t,uint32_t>,DifferentialActorCandidate> candidates;
    for(size_t marker=1;marker<=4;++marker){
        const auto* event=FirstInitialForMarker(session,marker);if(!event)continue;
        for(const auto& probe:event->actorProbes){
            auto& candidate=candidates[{probe.idOffset,probe.typeOffset}];candidate.idOffset=probe.idOffset;candidate.typeOffset=probe.typeOffset;const size_t index=marker-1;candidate.present[index]=true;candidate.resolved[index]=probe.resolved;candidate.categoryReadable[index]=probe.categoryReadable;candidate.ids[index]=probe.actorId;candidate.types[index]=probe.actorType;candidate.actors[index]=probe.actorPointer;candidate.categories[index]=probe.category;
        }
    }
    std::vector<DifferentialActorCandidate> result;
    for(auto& [key,candidate]:candidates){
        (void)key;
        if(candidate.present[0]&&candidate.present[1]){
            candidate.idsChange=candidate.ids[0]!=candidate.ids[1];candidate.actorsChange=candidate.actors[0]!=candidate.actors[1];
            if(candidate.present[2]){
                candidate.idsChange=candidate.idsChange&&candidate.ids[0]!=candidate.ids[2]&&candidate.ids[1]!=candidate.ids[2];candidate.actorsChange=candidate.actorsChange&&candidate.actors[0]!=candidate.actors[2]&&candidate.actors[1]!=candidate.actors[2];candidate.allMonsters=candidate.categoryReadable[0]&&candidate.categoryReadable[1]&&candidate.categoryReadable[2]&&candidate.categories[0]==2&&candidate.categories[1]==2&&candidate.categories[2]==2;
            }
        }
        candidate.provenForAbc=false; // Operation-record fields are legacy candidates, never selection provenance.
        result.push_back(candidate);
    }
    std::sort(result.begin(),result.end(),[](const auto& a,const auto& b){return a.provenForAbc>b.provenForAbc||(a.provenForAbc==b.provenForAbc&&a.idsChange>b.idsChange);});return result;
}

const char* SpatialClassificationName(SpatialClassification value){switch(value){case SpatialClassification::MatchesPlayerPosition:return "MATCHES_PLAYER_POSITION";case SpatialClassification::MatchesSelectedTargetPosition:return "MATCHES_SELECTED_TARGET_POSITION";case SpatialClassification::MatchesNeither:return "MATCHES_NEITHER";case SpatialClassification::Ambiguous:return "AMBIGUOUS";default:return "INSUFFICIENT_DATA";}}
const char* Field24CorrelationName(Field24Correlation value){switch(value){case Field24Correlation::MatchesActorId:return "matches selected actorId";case Field24Correlation::MatchesActorType:return "matches selected actorType";case Field24Correlation::MatchesPointerLow32:return "matches selected pointer low32";case Field24Correlation::DoesNotMatch:return "does not match selected identity";default:return "unknown";}}

SpatialAnalysis AnalyzeSpatialProvenance(const TargetInspectorSession& session){
    SpatialAnalysis result;result.captures.resize(4);result.selectedTargetSource="independent initial-0x0209 CTClientGame+0x2318 snapshot, category 2 and typed-tree validated";
    size_t complete=0;bool playerAll=true,targetAll=true,playerClose=true,targetClose=true,playerFar=true,targetFar=true;
    auto distance=[](const std::array<float,3>& a,const std::array<float,3>& b,bool horizontal){const double dx=double(a[0])-b[0],dy=double(a[1])-b[1],dz=double(a[2])-b[2];return std::sqrt(dx*dx+(horizontal?0.0:dy*dy)+dz*dz);};
    for(size_t i=0;i<4;++i){auto& row=result.captures[i];row.markerId=i+1;const auto* event=FirstInitialForMarker(session,i+1);if(!event)continue;row.captured=true;row.operationAvailable=event->operationSpatial.plausible;row.playerAvailable=event->spatial.player.positionAvailable;if(i<3&&row.operationAvailable&&row.playerAvailable){++complete;row.operationToPlayer3d=distance(event->operationSpatial.value,event->spatial.player.position.value,false);row.operationToPlayerHorizontal=distance(event->operationSpatial.value,event->spatial.player.position.value,true);playerClose=playerClose&&row.operationToPlayer3d<=SpatialMatchTolerance;playerFar=playerFar&&row.operationToPlayer3d>SpatialMatchTolerance;}else if(i<3)playerAll=false;
        const auto& target=event->spatial.selectedTarget;
        if(target.provenanceValidated&&target.positionAvailable){row.targetAvailable=true;row.operationToTarget3d=distance(event->operationSpatial.value,target.position.value,false);row.operationToTargetHorizontal=distance(event->operationSpatial.value,target.position.value,true);targetClose=targetClose&&row.operationToTarget3d<=SpatialMatchTolerance;targetFar=targetFar&&row.operationToTarget3d>SpatialMatchTolerance;const uint32_t low=uint32_t(target.pointer);const auto field=event->operationSpatial.field24Raw;row.field24Correlation=field==target.actorId?Field24Correlation::MatchesActorId:field==target.category?Field24Correlation::MatchesActorType:field==low?Field24Correlation::MatchesPointerLow32:Field24Correlation::DoesNotMatch;}else if(i<3)targetAll=false;
    }
    if(complete<3||!playerAll){result.reason="fewer than three valid initial-0x0209 operation/player snapshots";return result;}if(!targetAll){result.reason="player comparison available; selected-target comparison remains unavailable";return result;}
    if(playerClose&&targetClose){result.classification=SpatialClassification::Ambiguous;result.reason="operation is within tolerance of both player and selected target across A/B/C";}else if(playerClose&&targetFar){result.classification=SpatialClassification::MatchesPlayerPosition;result.reason="operation is within player tolerance and outside target tolerance across A/B/C";}else if(targetClose&&playerFar){result.classification=SpatialClassification::MatchesSelectedTargetPosition;result.reason="operation is within target tolerance and outside player tolerance across A/B/C";}else if(playerFar&&targetFar){result.classification=SpatialClassification::MatchesNeither;result.reason="operation is outside both tolerances across A/B/C";}else{result.classification=SpatialClassification::Ambiguous;result.reason="A/B/C distances do not support one consistent source";}return result;
}

std::vector<TargetCaptureComparison> CompareTargetCaptures(const TargetInspectorSession& session){
    std::vector<TargetCaptureComparison> result(4);const auto* first=FirstInitialForMarker(session,1);
    for(size_t captureIndex=0;captureIndex<result.size();++captureIndex){auto& comparison=result[captureIndex];comparison.markerId=captureIndex+1;const auto* event=FirstInitialForMarker(session,comparison.markerId);if(!event)continue;comparison.captured=true;comparison.count=int64_t(event->targetVector.count);comparison.countChangedFromA=first&&event->targetVector.count!=first->targetVector.count;const size_t rows=std::max(event->targetVector.records.size(),first?first->targetVector.records.size():size_t(0));comparison.records.reserve(rows);for(size_t i=0;i<rows;++i){TargetRecordComparison row;row.index=uint32_t(i);if(i<event->targetVector.records.size()){const auto& record=event->targetVector.records[i];row.present=true;row.raw=record.raw;row.actorId=record.actorId;row.actorType=record.actorType;row.actorPointer=record.resolution.actorPointer;}if(first&&i<first->targetVector.records.size()){const auto& baseline=first->targetVector.records[i];row.rawChangedFromA=!row.present||row.raw!=baseline.raw;row.idChangedFromA=!row.present||row.actorId!=baseline.actorId;row.typeChangedFromA=!row.present||row.actorType!=baseline.actorType;row.actorChangedFromA=!row.present||row.actorPointer!=baseline.resolution.actorPointer;}else if(first){row.rawChangedFromA=row.idChangedFromA=row.typeChangedFromA=row.actorChangedFromA=row.present;}comparison.records.push_back(row);}}
    return result;
}

std::string TargetRecordRawHex(const TargetRecord& record){return Bytes(record.raw);}
const char* TargetInspectorStateName(TargetInspectorPhase phase){switch(phase){case TargetInspectorPhase::WaitingForAoe:return "WAITING FOR AOE";case TargetInspectorPhase::Capturing:return "CAPTURING";case TargetInspectorPhase::Complete:return "COMPLETE";case TargetInspectorPhase::Error:return "ERROR";default:return "IDLE";}}
void InvalidateTargetInspector(TargetInspectorSession& session,const std::string& reason){session={};session.phase=TargetInspectorPhase::Error;session.error=reason;}

bool ExportTargetInspectorJson(const std::filesystem::path& path,const TargetInspectorSession& session,std::string& error){
    std::ofstream out(path,std::ios::binary);if(!out){error="Unable to create Target Differential Inspector JSON.";return false;}
    auto boolean=[&](bool value){out<<(value?"true":"false");};
    auto number=[&](float value){if(std::isfinite(value))out<<value;else out<<"null";};
    auto writeRegisters=[&](const TargetInspectorEvent& event){out<<"{\"RCX\":"<<Json(Hex(event.rcx))<<",\"RDX\":"<<Json(Hex(event.rdx))<<",\"R8\":"<<Json(Hex(event.r8))<<",\"R9\":"<<Json(Hex(event.r9))<<",\"R12\":"<<Json(Hex(event.r12))<<",\"R13\":"<<Json(Hex(event.r13))<<",\"R14\":"<<Json(Hex(event.r14))<<",\"R15\":"<<Json(Hex(event.r15))<<",\"RSP\":"<<Json(Hex(event.rsp))<<'}';};
    auto writePoint=[&](const SpatialPoint& point){out<<"{\"readable\":";boolean(point.readable);out<<",\"finite\":";boolean(point.finite);out<<",\"plausible\":";boolean(point.plausible);out<<",\"rawX\":"<<Json(Hex(point.raw[0]))<<",\"rawY\":"<<Json(Hex(point.raw[1]))<<",\"rawZ\":"<<Json(Hex(point.raw[2]))<<",\"x\":";number(point.value[0]);out<<",\"y\":";number(point.value[1]);out<<",\"z\":";number(point.value[2]);out<<",\"source\":"<<Json(point.source)<<",\"confidence\":"<<Json(point.confidence)<<",\"reason\":"<<Json(point.reason)<<'}';};
    auto writeActor=[&](const ActorSpatialSnapshot& actor){out<<"{\"available\":";boolean(actor.identityReadable);out<<",\"pointer\":"<<Json(Hex(actor.pointer))<<",\"identityReadable\":";boolean(actor.identityReadable);out<<",\"provenanceValidated\":";boolean(actor.provenanceValidated);out<<",\"actorId\":"<<actor.actorId<<",\"actorType\":"<<unsigned(actor.category)<<",\"category\":"<<unsigned(actor.category)<<",\"categoryName\":"<<Json(TargetActorTypeName(actor.category))<<",\"positionAvailable\":";boolean(actor.positionAvailable);out<<",\"position\":";writePoint(actor.position);out<<",\"source\":"<<Json(actor.source)<<",\"confidence\":"<<Json(actor.confidence)<<",\"reason\":"<<Json(actor.reason)<<'}';};
    auto writeEvent=[&](const TargetInspectorEvent& event){
        const auto& vector=event.targetVector;
        out<<"{\"sequence\":"<<event.sequence<<",\"markerId\":"<<event.markerId<<",\"timestampMs\":"<<event.timestampMs<<",\"threadId\":"<<event.threadId<<",\"operationWord0\":"<<event.operationWord0<<",\"operationReadable\":";boolean(event.operationReadable);out<<",\"classification\":"<<Json(event.initial0209?"0x0209":event.periodic020A?"0x020A":"other")<<",\"registers\":";writeRegisters(event);
        out<<",\"operationRecordReadable\":";boolean(event.operationRecordReadable);out<<",\"operationRecordRaw30\":"<<Json(Bytes(event.operationRecord))<<",\"operationSpatialCandidate\":{\"rawX\":"<<Json(Hex(event.operationSpatial.raw[0]))<<",\"rawY\":"<<Json(Hex(event.operationSpatial.raw[1]))<<",\"rawZ\":"<<Json(Hex(event.operationSpatial.raw[2]))<<",\"x\":";number(event.operationSpatial.value[0]);out<<",\"y\":";number(event.operationSpatial.value[1]);out<<",\"z\":";number(event.operationSpatial.value[2]);out<<",\"finite\":";boolean(event.operationSpatial.finite);out<<",\"plausible\":";boolean(event.operationSpatial.plausible);out<<"},\"candidateField24\":{\"raw\":"<<Json(Hex(event.operationSpatial.field24Raw))<<",\"semantic\":\"candidate only; not a target ID\"},\"playerSpatial\":";writeActor(event.spatial.player);out<<",\"owner\":{\"pointer\":"<<Json(Hex(event.rdx))<<",\"identityReadable\":";boolean(event.ownerIdentityReadable);out<<",\"actorId\":"<<event.ownerActorId<<",\"category\":"<<unsigned(event.ownerCategory)<<'}';
        out<<",\"actorProbes\":[";for(size_t i=0;i<event.actorProbes.size();++i){if(i)out<<',';const auto& probe=event.actorProbes[i];out<<"{\"idOffset\":"<<Json(Hex(probe.idOffset))<<",\"typeOffset\":"<<Json(Hex(probe.typeOffset))<<",\"actorId\":"<<probe.actorId<<",\"actorType\":"<<unsigned(probe.actorType)<<",\"resolved\":";boolean(probe.resolved);out<<",\"actorPointer\":"<<Json(Hex(probe.actorPointer))<<",\"categoryReadable\":";boolean(probe.categoryReadable);out<<",\"category\":"<<unsigned(probe.category)<<",\"spatial\":";writeActor(probe.spatial);out<<",\"readError\":"<<probe.error<<'}';}out<<']';
        out<<",\"entity660\":{\"roleConclusion\":\"caster/reference evidence; not selected-mob evidence unless later differential captures contradict it\",\"entityPointer\":"<<Json(Hex(vector.entityPointer))<<",\"expectedAddress\":"<<Json(Hex(vector.expectedAddress))<<",\"addressFromR12\":"<<Json(Hex(vector.addressFromR12))<<",\"r12MatchesEntity660\":";boolean(vector.r12MatchesEntity660);out<<",\"headerReadable\":";boolean(vector.headerReadable);out<<",\"structurallyValid\":";boolean(vector.structurallyValid);out<<",\"count\":"<<vector.count<<",\"records\":[";
        for(size_t j=0;j<vector.records.size();++j){if(j)out<<',';const auto& record=vector.records[j];const auto& resolution=record.resolution;out<<"{\"index\":"<<record.index<<",\"recordPointer\":"<<Json(Hex(record.recordPointer))<<",\"readable\":";boolean(record.recordReadable);out<<",\"raw8\":"<<Json(Bytes(record.raw))<<",\"actorId\":"<<record.actorId<<",\"actorType\":"<<unsigned(record.actorType)<<",\"actorTypeName\":"<<Json(TargetActorTypeName(record.actorType))<<",\"lookupStatus\":"<<Json(TargetActorLookupStatusName(resolution.status))<<",\"actorPointer\":"<<Json(Hex(resolution.actorPointer))<<'}';}out<<"]}}";
    };
    out<<"{\n\"mode\":\"AOE Target Differential Inspector\",\n\"readOnly\":true,\n\"comparisonPolicy\":\"first 0x0209 after each marker only; 0x020A stored separately\",\n\"captureSlots\":[";for(size_t i=0;i<session.captureSlots.size();++i){if(i)out<<',';const auto& slot=session.captureSlots[i];out<<"{\"capture\":"<<Json(std::string(1,char('A'+i)))<<",\"state\":"<<Json(TargetCaptureSlotStateName(slot.state))<<",\"markerId\":"<<slot.markerId<<",\"captureSequence\":"<<slot.captureSequence<<'}';}out<<"],\n\"sessionIdentity\":{\"pid\":"<<session.pid<<",\"creationTime\":"<<session.creationTime<<"},\n\"moduleBase\":"<<Json(Hex(session.moduleBase))<<",\n\"targetSha256\":"<<Json(session.targetSha256)<<",\n\"knownCallRva\":"<<Json(Hex(session.runtime.initialCallRva))<<",\n\"parsedInputRva\":"<<Json(Hex(session.runtime.differentialParsedRva))<<",\n\"boundedOperationRecordBytes\":"<<DifferentialOperationRecordBytes<<",\n\"knownVectorOffset\":"<<Json(Hex(session.runtime.targetVectorOffset))<<",\n\"knownResolverRva\":"<<Json(Hex(session.runtime.typedActorLookupRva))<<",\n\"state\":"<<Json(TargetInspectorStateName(session.phase))<<",\n\"markers\":[";
    for(size_t i=0;i<session.markers.size();++i){if(i)out<<',';const auto& marker=session.markers[i];out<<"{\"id\":"<<marker.id<<",\"capture\":"<<Json(std::string(1,char('A'+std::min<uint64_t>(marker.id-1,3))))<<",\"label\":"<<Json(marker.label)<<",\"timestampMs\":"<<marker.ms<<'}';}
    out<<"],\n\"initial0209Events\":[";for(size_t i=0;i<session.events.size();++i){if(i)out<<',';writeEvent(session.events[i]);}
    out<<"],\n\"periodic020AEvents\":[";for(size_t i=0;i<session.periodicEvents.size();++i){if(i)out<<',';writeEvent(session.periodicEvents[i]);}
    out<<"],\n\"parsedInputs\":[";for(size_t i=0;i<session.parsedInputs.size();++i){if(i)out<<',';const auto& capture=session.parsedInputs[i];out<<"{\"sequence\":"<<capture.sequence<<",\"markerId\":"<<capture.markerId<<",\"timestampMs\":"<<capture.timestampMs<<",\"threadId\":"<<capture.threadId<<",\"rip\":"<<Json(Hex(capture.rip))<<",\"rbp\":"<<Json(Hex(capture.rbp))<<",\"operationRecordPointer\":"<<Json(Hex(capture.operationRecordPointer))<<",\"ownerPointer\":"<<Json(Hex(capture.ownerPointer))<<",\"gameContext\":"<<Json(Hex(capture.gameContext))<<",\"resolvedActorPointer\":"<<Json(Hex(capture.resolvedActorPointer))<<",\"actorStatePointer\":"<<Json(Hex(capture.actorStatePointer))<<",\"operationWord\":"<<capture.operationWord<<",\"parsedSkillTemplateWord\":"<<capture.operationWord<<",\"operation0209\":";boolean(capture.operation0209);out<<",\"semanticInput\":";boolean(capture.semanticInput);out<<",\"operationRecordRaw30\":"<<Json(Bytes(capture.operationRecord))<<",\"parsedActorId\":"<<capture.parsedActorId<<",\"parsedActorType\":"<<unsigned(capture.parsedActorType)<<",\"modeByte\":"<<unsigned(capture.modeByte)<<",\"outerField24\":"<<capture.outerField24<<",\"recordCount\":"<<unsigned(capture.recordCount)<<",\"ownerActorId\":"<<capture.ownerActorId<<",\"ownerCategory\":"<<unsigned(capture.ownerCategory)<<'}';}
    out<<"],\n\"fieldComparison\":[";const auto fields=CompareOperationFields(session);for(size_t i=0;i<fields.size();++i){if(i)out<<',';const auto& field=fields[i];out<<"{\"offset\":"<<Json(Hex(field.offset))<<",\"width\":"<<field.width<<",\"label\":"<<Json(field.label)<<",\"A\":"<<(field.present[0]?Json(Hex(field.values[0])):"null")<<",\"B\":"<<(field.present[1]?Json(Hex(field.values[1])):"null")<<",\"C\":"<<(field.present[2]?Json(Hex(field.values[2])):"null")<<",\"changed\":";boolean(field.changed);out<<",\"allPairwiseDifferent\":";boolean(field.allPairwiseDifferent);out<<",\"interpretation\":"<<Json(field.interpretation)<<'}';}
    out<<"],\n\"actorCandidates\":[";const auto candidates=CompareActorCandidates(session);for(size_t i=0;i<candidates.size();++i){if(i)out<<',';const auto& candidate=candidates[i];out<<"{\"idOffset\":"<<Json(Hex(candidate.idOffset))<<",\"typeOffset\":"<<Json(Hex(candidate.typeOffset))<<",\"idsChange\":";boolean(candidate.idsChange);out<<",\"actorsChange\":";boolean(candidate.actorsChange);out<<",\"allMonsters\":";boolean(candidate.allMonsters);out<<",\"provenForAbc\":";boolean(candidate.provenForAbc);out<<",\"captures\":[";for(size_t j=0;j<4;++j){if(j)out<<',';out<<"{\"present\":";boolean(candidate.present[j]);out<<",\"actorId\":"<<candidate.ids[j]<<",\"actorType\":"<<unsigned(candidate.types[j])<<",\"resolved\":";boolean(candidate.resolved[j]);out<<",\"actorPointer\":"<<Json(Hex(candidate.actors[j]))<<",\"category\":"<<unsigned(candidate.categories[j])<<'}';}out<<"]}";}
    const auto spatial=AnalyzeSpatialProvenance(session);
    out<<"],\n\"spatialCaptures\":[";for(size_t i=0;i<4;++i){if(i)out<<',';const auto* event=FirstInitialForMarker(session,i+1);const Marker* marker=nullptr;for(const auto& item:session.markers)if(item.id==i+1){marker=&item;break;}out<<"{\"capture\":"<<Json(std::string(1,char('A'+i)))<<",\"markerTime\":{\"timestampMs\":"<<(marker?marker->ms:0)<<",\"playerSpatial\":";writeActor(session.markerSpatial[i].player);out<<",\"selectedTarget\":";writeActor(session.markerSpatial[i].selectedTarget);out<<"},\"initial0209Time\":";if(!event)out<<"null";else{const auto& comparison=spatial.captures[i];out<<"{\"timestampMs\":"<<event->timestampMs<<",\"operationSpatialCandidate\":{\"rawX\":"<<Json(Hex(event->operationSpatial.raw[0]))<<",\"rawY\":"<<Json(Hex(event->operationSpatial.raw[1]))<<",\"rawZ\":"<<Json(Hex(event->operationSpatial.raw[2]))<<",\"x\":";number(event->operationSpatial.value[0]);out<<",\"y\":";number(event->operationSpatial.value[1]);out<<",\"z\":";number(event->operationSpatial.value[2]);out<<",\"finite\":";boolean(event->operationSpatial.finite);out<<",\"plausible\":";boolean(event->operationSpatial.plausible);out<<"},\"playerSpatial\":";writeActor(event->spatial.player);out<<",\"selectedTarget\":";writeActor(event->spatial.selectedTarget);out<<",\"distances\":{\"operationToPlayer3d\":"<<(comparison.playerAvailable?std::to_string(comparison.operationToPlayer3d):"null")<<",\"operationToPlayerHorizontalXZ\":"<<(comparison.playerAvailable?std::to_string(comparison.operationToPlayerHorizontal):"null")<<",\"operationToSelectedTarget3d\":"<<(comparison.targetAvailable?std::to_string(comparison.operationToTarget3d):"null")<<",\"operationToSelectedTargetHorizontalXZ\":"<<(comparison.targetAvailable?std::to_string(comparison.operationToTargetHorizontal):"null")<<"},\"candidateField24\":{\"raw\":"<<Json(Hex(event->operationSpatial.field24Raw))<<",\"label\":\"candidate only\",\"correlation\":"<<Json(Field24CorrelationName(comparison.field24Correlation))<<"}}";}out<<'}';}
    out<<"],\n\"spatialConclusion\":{\"classification\":"<<Json(SpatialClassificationName(spatial.classification))<<",\"reason\":"<<Json(spatial.reason)<<",\"tolerance3d\":"<<SpatialMatchTolerance<<",\"horizontalPlane\":\"X/Z; Y is the statically and previously runtime-verified height component\",\"selectedTargetSource\":"<<Json(spatial.selectedTargetSource)<<"},\n\"legacyEntity660Comparison\":[";const auto comparisons=CompareTargetCaptures(session);for(size_t i=0;i<comparisons.size();++i){if(i)out<<',';const auto& capture=comparisons[i];out<<"{\"capture\":"<<Json(std::string(1,char('A'+i)))<<",\"captured\":";boolean(capture.captured);out<<",\"count\":"<<capture.count<<'}';}out<<"]\n}\n";
    if(!out){error="Failed while writing Target Differential Inspector JSON.";return false;}error.clear();return true;
}
}




